### PR TITLE
Fix submission info button when submission loaded dynamically

### LINKED ISSUE #8188: Submission info button not opening a modal
In the question preview page it seems the ℹ️ button for each submission that opens the modal with grading job info is not working. The button doesn't act at all, and only collapses the submission panel. I believe it may be related to recent changes in the JS assets for the page, investigating. [Raised on Slack](https://prairielearn.slack.com/archives/C266KEH9A/p1689363159243639).

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Fixes #8188.

### CODE REVIEW

File: apps/prairielearn/assets/scripts/question.ts [hunk 1]
```diff
@@ -120,7 +120,10 @@ function fetchResults(socket, submissionId) {
         answerContainer.closest('.grading-block').classList.remove('d-none');
       }
       if (msg.submissionPanel) {
-        document.getElementById('submission-' + submissionId).outerHTML = msg.submissionPanel;
+        // Using jQuery here because msg.submissionPanel may contain scripts
+        // that must be executed. Typical vanilla JS alternatives don't support
+        // this kind of script.
+        $('#submission-' + submissionId).replaceWith(msg.submissionPanel);
```
Comment (nwalters512) [inline apps/prairielearn/assets/scripts/question.ts:126]: For future reference, here's the part of jQuery that seems to handle script execution in `replaceWith`: https://github.com/jquery/jquery/blob/8be4c0e4f89d6c8f780e5937a0534921d8c7815e/src/manipulation/domManip.js

**Review by nwalters512 — APPROVED** [review]
