### PR TITLE
Fix accessibility issues in rubric settings component

### LINKED ISSUE #13749: Accessibility: rubric settings component has buttons without label or text
### Details

The rubric settings component includes multiple buttons that are labeled by nothing more than a FA icon. These include tooltip buttons, the button to extend the settings card, and the grabbing button used for reordering items. For accessibility these buttons [should either have a hidden text or an aria-label](https://dequeuniversity.com/rules/axe/4.10/button-name?application=axe-linter-vsc).

Caught by axe-linter vscode extension.

### PR DESCRIPTION
**Pull request by reteps**
# Description

Resolves #13749

This PR adds proper accessibility labels to all icon-only buttons in the RubricSettings component. Changes done by Claude.

# Testing

None

### CODE REVIEW

File: apps/prairielearn/src/components/RubricSettings.tsx [hunk 1]
```diff
@@ -988,29 +996,30 @@ function RubricRow({
               type="button"
               className="btn btn-sm btn-ghost"
               style={{ cursor: 'grab' }}
+              aria-label="Drag to reorder"
               draggable
               onDragStart={onDragStart}
             >
-              <i className="fas fa-arrows-up-down" />
+              <i className="fas fa-arrows-up-down" aria-hidden="true" />
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/components/RubricSettings.tsx:1001]: Does it make sense to add a label to this button? I'd imagine users that rely on aria labels would likely have limited ability to drag the button and would instead rely on the hidden buttons for moving up and down (next two buttons). Would it be better to make this button aria-hidden? I'm fine either way, just raising it for consideration.

**Review by jonatanschroeder — APPROVED** [review]

File: apps/prairielearn/src/components/RubricSettings.tsx (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/src/components/RubricSettings.tsx:1001]: Note that even if it's hidden, it'll still receive focus, which will be confusing. I think the work that was done in https://github.com/PrairieLearn/PrairieLearn/pull/13629 to add drag-and-drop is probably a better long term approach.
