### PR TITLE
Enforce group role permissions

### LINKED ISSUE #4161: Instructor access should override group member checks
Trying to view https://www.prairielearn.org/pl/course_instance/128491/assessment_instance/2391228/ as an instructor or admin gives an error `Not a group member`. This check should be overridden in this case.

### LINKED ISSUE #9105: Weird behaviour for start assessment button in group exams
In group homeworks, if the group rules have not been met yet (e.g., minimum group size, role settings, etc.), the "Start assessment" button is disabled (which is fine). In group exams, the button is disabled too, but because the honor pledge is shown, when the user confirms the honor pledge the button becomes disabled. Clicking the button fails with a CSRF fail (since the button was not in a form intended to actually do anything), but it shouldn't have been enabled in the first place.

### PR DESCRIPTION
**Pull request by jonatanschroeder**
This is a replacement to #8006.

* [x] Middleware check in instance question that blocks view for students with role that does not give access;
* [x] Middleware blocks access to question if role configuration is invalid (e.g., not balanced, minimum/maximum per role not reached);
* [x] Submission check and button that blocks submission for students with role that does not give access;
* [x] Helper button beside save/grade button explaining why buttons are hidden;
* [x] Assessment instance page: remove link (and show explanation) if student cannot view question due to roles;
* [x] Buttons for next/previous question: disable buttons if question cannot be viewed;
* [x] Show roles and permissions in a better view in the assessment instance page;
* [x] Show roles and permissions in a better view in the assessment page;
* [x] Fix #9105 
* [x] Test and ensure that groups without roles still work as expected;
* [x] Test and ensure that assessments without groups still work as expected;
* [x] Test and ensure that instructors still have access to student questions regardless of roles;
* [x] Review update process for roles (seems to be modified in #8006);
* [x] Update CI tests;
* [ ] Docs?
* [x] Fix #4161

### CODE REVIEW

File: apps/prairielearn/src/lib/groups.sql [hunk 1]
```diff
@@ -147,6 +147,17 @@ WHERE
   gr.assessment_id = $assessment_id
   AND gu.user_id = $user_id;
 
+-- BLOCK select_question_permissions
+SELECT
+  BOOL_OR(aqrp.can_view) AS can_view,
+  BOOL_OR(aqrp.can_submit) AS can_submit
+FROM
+  assessment_question_role_permissions AS aqrp
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/lib/groups.sql:155]: TODO check indices

File: apps/prairielearn/src/middlewares/selectAndAuthzInstanceQuestion.js [hunk 2]
```diff
@@ -1,23 +1,50 @@
...
     req_date: res.locals.req_date,
-  };
-  sqldb.query(sql.select_and_auth, params, function (err, result) {
-    if (ERR(err, next)) return;
-    if (result.rowCount === 0) return next(error.make(403, 'Access denied'));
-    _.assign(res.locals, result.rows[0]);
-    next();
   });
-};
+  if (result.rowCount === 0) throw error.make(403, 'Access denied');
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/middlewares/selectAndAuthzInstanceQuestion.js:19]: TODO this may be null

File: apps/prairielearn/src/pages/studentInstanceQuestionExam/studentInstanceQuestionExam.js [hunk 3]
```diff
@@ -24,6 +24,14 @@ function processSubmission(req, res, callback) {
   if (!res.locals.authz_result.active) {
     return callback(error.make(400, 'This assessment is not accepting submissions at this time.'));
   }
+  if (!res.locals.instance_question.group_role_permissions.can_submit) {
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/pages/studentInstanceQuestionExam/studentInstanceQuestionExam.js:27]: TODO also for homework

File: apps/prairielearn/src/pages/partials/questionFooter.ejs
Comment (jonatanschroeder) [inline apps/prairielearn/src/pages/partials/questionFooter.ejs:1]: This file had near-identical sections for freeform vs v2 questions. I rearranged the code to avoid this deduplication.

File: apps/prairielearn/src/lib/groups.sql [hunk 4]
```diff
@@ -150,16 +150,33 @@ WHERE
...
   gr.id as group_role_id
 FROM
-  users u
-  JOIN group_user_roles gu ON u.user_id = gu.user_id
-  JOIN group_roles gr ON gu.group_role_id = gr.id
+  group_users gu
+  JOIN users u ON gu.user_id = u.user_id
+  JOIN group_user_roles gur ON gu.group_id = gur.group_id
+  AND gu.user_id = gur.user_id
+  JOIN group_roles gr ON gur.group_role_id = gr.id
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/groups.sql:179]: Nit, conventions:

```suggestion
  group_users AS gu
  JOIN users u ON (gu.user_id = u.user_id)
  JOIN group_user_roles gur ON (
    gu.group_id = gur.group_id
    AND gu.user_id = gur.user_id
  )
  JOIN group_roles gr ON (gur.group_role_id = gr.id)
```

File: apps/prairielearn/src/pages/partials/groupRoleTable.ejs [hunk 5]
```diff
@@ -0,0 +1,81 @@
+<% const roleConfigProblems = (rolesInfo.validationErrors?.length ?? 0) + (rolesInfo.usersWithoutRoles.length > 0 ? 1 : 0) + (rolesInfo.rolesAreBalanced ? 0 : 1); %>
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/partials/groupRoleTable.ejs:1]: Nit, this should be equivalent and more consistent with the handling of `rolesInfo.validationErrors`?

From what I can tell in the TS types, we always expect `validationErrors` to be present. Is the optional chaining on it to get `length` necessary?

```suggestion
<% const roleConfigProblems = (rolesInfo.validationErrors?.length ?? 0) + rolesInfo.usersWithoutRoles.length + (rolesInfo.rolesAreBalanced ? 0 : 1); %>
```

File: apps/prairielearn/src/pages/partials/groupWorkInfoContainer.ejs [hunk 6]
```diff
@@ -9,7 +9,7 @@
       <p>
         <% if (groupConfig.minimum > 1) { %>
         This is a group assessment. Use your join code to invite others to join the group.
-        A group must have <% if (groupConfig.maximum) { %>between <%= groupConfig.minimum %> and <%= groupConfig.maximum %><% } else { %>at least <%= groupConfig.minimum %><% } %> students.
+        A group must have <% if (groupConfig.minimum === groupConfig.maximum) { %><%= groupConfig.minimum %><% } else if (groupConfig.maximum) { %>between <%= groupConfig.minimum %> and <%= groupConfig.maximum %><% } else { %>at least <%= groupConfig.minimum %><% } %> students.
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/partials/groupWorkInfoContainer.ejs:12]: Do we assert that `minimum` is present if `maximum` is? I'm just checking that these conditionals are sufficient.

File: apps/prairielearn/src/pages/partials/questionNavSideButton.ejs [hunk 7]
```diff
@@ -1,11 +1,13 @@
 <%
 let classes = ['btn', 'text-white', 'mb-3'];
-if (question.id && !question.sequence_locked) {
+let show_lock = false;
+if (question.id && !question.sequence_locked && (locals.group_role_permissions?.can_view ?? true)) {
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/partials/questionNavSideButton.ejs:4]: Nit, in my mind this would be easier to parse if we split it into the following conditions:

```ts
if (!question.id) {
  // IMO we should describe what this case is. Does this mean there's no question to link to?
  classes.push('btn-primary', 'disabled');
} else if (!question.sequence_locked && (locals.group_role_permissions?.can_view ?? true)) {
  classes.push('btn-primary');
} else {
  classes.push('btn-secondary', 'pl-sequence-locked');
  show_lock = true;
}
```

File: apps/prairielearn/src/pages/partials/studentGroupControls.ejs [hunk 8]
```diff
@@ -16,39 +16,8 @@
...
-        At least one user does not have a role. All users must have a role.
-      </div>
-    <% } %>
-    <% if (canViewRoleTable) { %>
-    <%- include('../shared/groupRoleSelectTable.ejs', {groupMembers: groupMembers, rolesInfo: rolesInfo}); %>
-    <% } %>
-  <% } %>
-  <% if (locals.assessment.type === 'Exam' && locals.assessment.require_honor_code) { %>
+  <%- include('./groupWorkInfoContainer.ejs'); %>
+  <% if (start && locals.assessment.type === 'Exam' && locals.assessment.require_honor_code) { %>
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/partials/studentGroupControls.ejs:20]: I can't wait til this is all strongly typed. It took me way too long to figure out what `start` is and where it comes from. (Also IMO that's a horrible name for this variable, though I know it was that way before you started.)

File: apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js [hunk 9]
```diff
@@ -29,25 +26,30 @@ async function ensureUpToDate(locals) {
...
       throw error.make(403, 'Not authorized', res.locals);
     }
+    if (
+      !res.locals.authz_result.authorized_edit &&
+      ['attach_file', 'attach_text', 'delete_file', 'timeLimitFinish', 'leave_group'].includes(
+        req.body.__action,
+      )
+    ) {
+      throw error.make(403, 'Action is only permitted to students, not staff', res.locals);
+    }
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js:42]: This is new; I'm curious why this ended up in this PR? I don't see the relation to everything else happening here.

File: apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js [hunk 10]
```diff
@@ -156,31 +161,40 @@ router.get(
       const groupConfig = await groupAssessmentHelper.getGroupConfig(res.locals.assessment.id);
       res.locals.groupConfig = groupConfig;
 
-      // Check whether the user is currently in a group in the current assessment by trying to get a group_id
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js:159]: Is this check now being performed somewhere else, or was it just not necessary?

File: apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js [hunk 11]
```diff
@@ -156,31 +161,40 @@ router.get(
...
-          const result = await groupAssessmentHelper.getAssessmentPermissions(
-            res.locals.assessment.id,
-            res.locals.user.user_id,
-          );
-          res.locals.canViewRoleTable = result.can_assign_roles_at_start;
+        res.locals.user_group_roles =
+          groupInfo.rolesInfo?.roleAssignments?.[res.locals.authz_data.user.uid]
+            ?.map((role) => role.role_name)
+            ?.join(', ') || 'None';
+        // Get the role permissions. If the authorized user is a staff member, then they have all permissions.
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js:188]: Maybe this is a dumb question: where is "they have all permissions" implemented? Are we just checking `res.locals.authz_data....` in the EJS template? Surely we don't want *all* staff members to have all permissions (that is, a student data viewer shouldn't be able to take actions)?

File: apps/prairielearn/src/tests/groupExamRolePermissions.test.sql [hunk 12]
```diff
@@ -0,0 +1,59 @@
...
+-- BLOCK generate_and_enroll_3_users
+SELECT
+  user_id,
+  uid,
+  name,
+  uin
+FROM
+  users_randomly_generate (3, 1)
+  LEFT JOIN course_instances AS ci on (ci.id = 1)
+  LEFT JOIN pl_courses AS c ON (c.id = ci.course_id)
```
Comment (nwalters512) [inline apps/prairielearn/src/tests/groupExamRolePermissions.test.sql:18]: What do these joins do for us?

File: apps/prairielearn/src/tests/groupExamRolePermissions.test.ts [hunk 13]
```diff
@@ -0,0 +1,583 @@
...
+  assessmentInstanceId: string,
+  questionId: string,
+): Promise<string> {
+  const result = await queryValidatedOneRow(
+    sql.select_instance_questions,
+    {
+      assessment_instance_id: assessmentInstanceId,
+      question_id: questionId,
+    },
+    QuestionIdSchema,
```
Comment (nwalters512) [inline apps/prairielearn/src/tests/groupExamRolePermissions.test.ts:192]: Nit: why not use `IdSchema` directly here?

File: apps/prairielearn/src/pages/partials/groupRoleTable.ejs (hunk 5 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/partials/groupRoleTable.ejs:1]: Indeed, if `rolesInfo` is not null, then `validationErrors` is not null. I'll remove the optional chaining.

As for the `usersWithoutRoles.length`, this comes from #8006, and is based on the fact that a single alert is created in this case. So it's a count of alerts, not a count of problems. Do you want to change this?

File: apps/prairielearn/src/pages/partials/groupWorkInfoContainer.ejs (hunk 6 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/partials/groupWorkInfoContainer.ejs:12]: Line 10 has a check for a minimum larger than 1, so yes, minimum is always present in this line.

File: apps/prairielearn/src/pages/partials/groupRoleTable.ejs (hunk 5 above)
Comment (nwalters512) [reply apps/prairielearn/src/pages/partials/groupRoleTable.ejs:1]: Ahh, I didn't read far enough down. I thought this was just for the conditional on the next line, but I see that we actually render a badge with this count. You can keep the count as it.

File: apps/prairielearn/src/pages/partials/groupWorkInfoContainer.ejs (hunk 6 above)
Comment (nwalters512) [reply apps/prairielearn/src/pages/partials/groupWorkInfoContainer.ejs:12]: Ah, great, thanks for pointing that out!

File: apps/prairielearn/src/pages/partials/questionNavSideButton.ejs (hunk 7 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/partials/questionNavSideButton.ejs]: Done in 2e83134.

File: apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js (hunk 9 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js:42]: There was a generic check on the lines before that blocked any POST when `authorized_edit` was false. However, I want to allow instructors to update roles, so I separated into two checks (the one before this and this one): the first causes a 403 if the user is neither an authorized student or a staff with edit permission; the second blocks retains the previous behaviour that blocks a staff member from posting for these particular kinds of actions.

File: apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js (hunk 10 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js:159]: It was trying to find the group based on the user instead of based on the assessment instance. This was a problem when the user was an instructor. This was changed to use the group from the assessment instance, which is presumed to always exist. This was copied from the assessment code (which needs to check if the group exists) without regard for the fact that the group in fact exists.

File: apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js (hunk 11 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/studentAssessmentInstance/studentAssessmentInstance.js]: The comment was misleading, but the implementation is correct. If a user has course instance view permission, then role restrictions don't apply. This is rephrased in 4ccba7e.

File: apps/prairielearn/src/tests/groupExamRolePermissions.test.sql (hunk 12 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/tests/groupExamRolePermissions.test.sql]: I copied this from #8006 and didn't change it. The same join is used in other tests. It seems this was blindly copied from the admin query that generates random users (which uses these joins) by one of the tests, then copied from one test to another without thinking. I removed this (and other related joins) in b544f3d67.

File: apps/prairielearn/src/tests/groupExamRolePermissions.test.ts (hunk 13 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/tests/groupExamRolePermissions.test.ts:192]: Again, I didn't rewrite the tests, so a few minor issues remained. This code (and one other call) was still using `queryValidatedOneRow`, so the object was returned with an id column instead of the single value. I replaced this in ba2016c41.

**Review by nwalters512 — APPROVED** [review]
Let's merge this and see what happens!
