### PR TITLE
Use correct branch name when performing git operations

### LINKED ISSUE #6145: Incorrect file edit resets when using `main` rather than `master`
PL allows course GitHub repos to use an arbitrary branch for syncing, which is normally set to either `'main'` (new repos) or `'master'` (legacy repos). The name of this branch is stored in: https://github.com/PrairieLearn/PrairieLearn/blob/5cd1fd81e15b0529a9e6af10be7da32462b500f0/database/tables/pl_courses.pg#L2

In some places we correctly use this branch name when resetting: https://github.com/PrairieLearn/PrairieLearn/blob/5cd1fd81e15b0529a9e6af10be7da32462b500f0/pages/shared/syncHelpers.js#L135

But there appear to be at least two places where we've kept the old hard-coded use of `'master'`: https://github.com/PrairieLearn/PrairieLearn/blob/5cd1fd81e15b0529a9e6af10be7da32462b500f0/lib/editors.js#L168
https://github.com/PrairieLearn/PrairieLearn/blob/5cd1fd81e15b0529a9e6af10be7da32462b500f0/pages/instructorFileEditor/instructorFileEditor.js#L771

These both need to be changed to use `course.branch` instead of `'master'`.

### PR DESCRIPTION
**Pull request by nwalters512**
This should fix #6145.

### CODE REVIEW

File: lib/editors.js [hunk 1]
```diff
@@ -165,7 +165,7 @@ class Editor {
           type: 'reset_from_git',
           description: 'Reset state to remote git repository',
           command: 'git',
-          arguments: ['reset', '--hard', 'origin/master'],
+          arguments: ['reset', '--hard', `origin/${this.course.branch}`],
```
Comment (mwest1066) [inline lib/editors.js:168]: I think I would have blindly written `locals` here as well, so I'm glad you got it right!

**Review by mwest1066 — APPROVED** [review]

File: lib/editors.js (hunk 1 above)
Comment (nwalters512) [reply lib/editors.js:168]: The benefits of local pattern-matching 😛
