### PR TITLE
Fix AuthzMismatch component for cases where `authzData` is not defined

### LINKED ISSUE #12957: Friendly auth error page breaks in certain contexts
### Details

The friendly auth error added in #12496 breaks on pages that don't have `authz_data`. We see the following error in that case:

```
[
  {
    "code": "invalid_type",
    "expected": "object",
    "received": "undefined",
    "path": [
      "authz_data"
    ],
    "message": "Required"
  }
]
```

The error originates here:

https://github.com/PrairieLearn/PrairieLearn/blob/9ae4283deb63924c3e2564382e6dc80fb35497bb/apps/prairielearn/src/lib/client/page-context.ts#L104

Sentry link: https://prairielearn-inc.sentry.io/issues/6895348921

## Reproduction steps

* As an admin, visit http://localhost:3000/pl/administrator/courses
* Click your name in the upper-right and click "Turn off administrator access"
* Observe the above error after the page reloads

### PR DESCRIPTION
**Pull request by reteps**
# Description

Closes #12957 . We discussed that in this case, we will just show the original error, since you can't clear the "is_administrator" flag without updating the "Clear Effective User" to also unset the associated cookie here.

# Testing

CleanShot 2025-09-22 at 20 42 07@2x

See attached issue.

### CODE REVIEW

File: apps/prairielearn/src/lib/client/page-context.ts [hunk 1]
```diff
@@ -81,17 +81,10 @@ export type PageContextWithAuthzData = z.infer<typeof PageContextWithAuthzDataSc
 export function getPageContext(
   resLocals: Record<string, any>,
   options?: {
-    withAuthzData?: true;
+    withAuthzData: boolean;
   },
 ): PageContextWithAuthzData;
 
-export function getPageContext(
```
Comment (reteps) [inline apps/prairielearn/src/lib/client/page-context.ts:88]: This signature was wrong.

Comment (nwalters512) [reply apps/prairielearn/src/lib/client/page-context.ts:88]: I don't think the new signature is correct either. The following code (modified from `home.tsx` passes type checking, though it shouldn't:

```ts
    const { authn_provider_name, __csrf_token, urlPrefix, authz_data } = getPageContext(res.locals, {
      withAuthzData: false,
    });
    console.log(authz_data.authn_mode)
```

File: apps/prairielearn/src/middlewares/authzHelper.tsx [hunk 2]
```diff
@@ -32,6 +32,7 @@ export const createAuthzMiddleware =
   (req: Request, res: Response, next: NextFunction) => {
     // This is special-cased because the middleware that sets authz_data
     // may not have run yet.
+    const hasAuthzData = res.locals.authz_data != null;
```
Comment (nwalters512) [inline apps/prairielearn/src/middlewares/authzHelper.tsx]: Nit, this code comes in between a comment and the thing the comment describes.

I'd be totally fine with you just inlining `res.locals.authz_data != null` in the `if` conditional below. One less thing to give a name to 🙂

Comment (reteps) [reply apps/prairielearn/src/middlewares/authzHelper.tsx]: I moved the comment in 319598e8db51c26bbaac8edcd4d52968ef4337db.

File: apps/prairielearn/src/lib/client/page-context.ts (hunk 1 above)
Comment (reteps) [reply apps/prairielearn/src/lib/client/page-context.ts:88]: I fixed this in 319598e8db51c26bbaac8edcd4d52968ef4337db.

File: apps/prairielearn/src/lib/client/page-context.ts [hunk 3]
```diff
@@ -87,8 +87,8 @@ export function getPageContext(
 
 export function getPageContext(
   resLocals: Record<string, any>,
-  options: {
-    withAuthzData: false;
+  options?: {
+    withAuthzData?: false;
   },
 ): PageContext;
```
[the remark this answers is not in the document]
Comment (reteps) [reply apps/prairielearn/src/lib/client/page-context.ts:93]: Fixed in [4ac6c2e](https://github.com/PrairieLearn/PrairieLearn/pull/12961/commits/4ac6c2e936f61e8a90b2fc9a0a5a854c1945c6dc).
