### PR TITLE
Fix External Grading for Shared Questions

### LINKED ISSUE #8500: Question Sharing - Error grading questions in consumer course that use external graders from producer course
When attempting to grade questions in the consumer course that use a custom external autograder in the producers course I get the following error: `Error: ENOENT: no such file or directory, lstat '/chunks/course-4011/serverFilesCourse/python_autograder/'`. Here is how the info.json files for the questions I am attempting to share are structured:
```json
{
    "uuid": "31adc93a-05f2-4280-8358-7b42852ceed8",
    "title": "Add two numbers",
    "topic": "Functions",
    "tags": [
        "code",
        "v3",
        "programming",
        "SP20_hw",
        "Base",
        "SU20_hw"
    ],
    "type": "v3",
    "singleVariant": true,
    "gradingMethod": "External",
    "externalGradingOptions": {
        "enabled": true,
        "image": "prairielearn/centos7-python",
        "serverFilesCourse": [
            "python_autograder/"
        ],
        "entrypoint": "/grade/serverFilesCourse/python_autograder/run.sh",
        "timeout": 20
    }
}


```

### PR DESCRIPTION
**Pull request by SethPoulsen**
fix #8500

### CODE REVIEW

File: apps/prairielearn/src/lib/externalGrader.sql [hunk 1]
```diff
@@ -10,7 +10,7 @@ FROM
   LEFT JOIN submissions AS s ON (s.id = gj.submission_id)
   LEFT JOIN variants AS v ON (v.id = s.variant_id)
   LEFT JOIN questions AS q ON (q.id = v.question_id)
-  LEFT JOIN pl_courses AS c ON (c.id = v.course_id)
+  LEFT JOIN pl_courses AS c ON (c.id = q.course_id)
```
Comment (SethPoulsen) [inline apps/prairielearn/src/lib/externalGrader.sql:13]: External grader should be passed the `question_course` to do the grading, not the `variant_course`!

Is there any reason we also need to grab the `variant_course` here? 

In a lot of places I am grabbing the info for both courses, so the `variant_course` can be used to report issues, but I can't find anywhere that issues related to external grading are being reported.

Comment (mwest1066) [reply apps/prairielearn/src/lib/externalGrader.sql:13]: Huh, that might be a separate problem if we aren't reporting failures as issues.

**Review by mwest1066 — APPROVED** [review]

**Comment by SethPoulsen** [comment]
There is a code point here where we are specifically not doing anything about external grader issues

https://github.com/PrairieLearn/PrairieLearn/blob/90e37d2af788a73901297a5c11ec2b91cf11dc11/apps/prairielearn/src/lib/question.js#L606-L631

I don't know if there is some other place where they are being handled, I couldn't find it. The word 'issues' is nowhere present in the grader-host codebase.
