### PR TITLE
Fix workspace proxy uncaught error

### LINKED ISSUE #2936: Proxy does not correctly handle socket disconnections
The workspace proxy code does not handle writes after connection end. See below for the stack trace. This might be related to https://github.com/chimurai/http-proxy-middleware/issues/346

```
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: events.js:292
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: throw er; // Unhandled 'error' event
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: ^
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: Error [ERR_STREAM_WRITE_AFTER_END]: write after end
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at writeAfterEnd (_stream_writable.js:266:14)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at Socket.Writable.write (_stream_writable.js:315:5)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at Socket.Writable.end (_stream_writable.js:585:10)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at Socket.end (net.js:590:31)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at ProxyServer.defaultErrorHandler (/PrairieLearn/node_modules/http-proxy-middleware/dist/handlers.js:59:9)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at ProxyServer.emit (/PrairieLearn/node_modules/eventemitter3/index.js:204:33)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at ClientRequest.onOutgoingError (/PrairieLearn/node_modules/http-proxy/lib/http-proxy/passes/ws-incoming.js:157:16)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at ClientRequest.emit (events.js:315:20)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at ClientRequest.EventEmitter.emit (domain.js:483:12)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at Socket.socketErrorListener (_http_client.js:426:9)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at Socket.emit (events.js:315:20)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at Socket.EventEmitter.emit (domain.js:483:12)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at emitErrorNT (internal/streams/destroy.js:92:8)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at processTicksAndRejections (internal/process/task_queues.js:84:21)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: Emitted 'error' event on Socket instance at:
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at errorOrDestroy (internal/streams/destroy.js:108:12)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at writeAfterEnd (_stream_writable.js:268:3)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at Socket.Writable.write (_stream_writable.js:315:5)
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: [... lines matching original stack trace ...]
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: at processTicksAndRejections (internal/process/task_queues.js:84:21) {
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: code: 'ERR_STREAM_WRITE_AFTER_END'
Aug 26 13:26:26 ip-10-0-0-229.us-east-2.compute.internal node[10366]: }
```

### PR DESCRIPTION
**Pull request by nicknytko**
In theory this should fix #2936, but I wasn't able to get the bug to occur locally

### CODE REVIEW

File: server.js [hunk 1]
```diff
@@ -204,6 +204,15 @@ const workspaceProxyOptions = {
             return 'not-matched';
         }
     },
+    onError: (err, req, res) => {
+        logger.err(`Error proxying workspace request: ${err}`);
```
Comment (mwest1066) [inline server.js:208]: Dumb question, but is this `logger.err()` or `logger.error()`?

File: server.js [hunk 2]
```diff
@@ -204,6 +204,15 @@ const workspaceProxyOptions = {
...
+        try {
+            res.writeHead(500, { 'Content-Type': 'text/plain' });
+            res.send('There was an error proxying this workspace request');
+        } catch (err2) {
```
Comment (mwest1066) [inline server.js:212]: Not that I really mind, but this could be just `err` again, right? I try and stick to the convention that the most recently used callback is always `callback` and the most recent error is `err` (unless there is some other good reason, of course).

File: server.js (hunk 1 above)
Comment (nicknytko) [reply server.js:208]: 😳
