### PR TITLE
Replace showdown with marked in all elements

### LINKED ISSUE #4231: Markdown support is missing/incomplete
I'm using this issue to track all markdown rendering issues.

## Headings

This works:
```
<markdown>
<h1>This is a heading</h1>

# This is also a heading
</markdown>
```

But this, does not work as expected (extra indent):
```
<markdown>
    <h1>This is a heading</h1>

# This is also a heading
</markdown>
```
Similarly, [this question](https://www.prairielearn.org/pl/course/108/question/4111573/preview) from the sample course doesn't show the `# Hello, World` rendered, but it **does** when you add a line break after opening the `<markdown>` tag. 

screen_shot_2022-08-03_at_12 12 59_pm_720

Oddly, the behaviour isn't consistent as this simple example does work:

```
<markdown>
# This is also a heading
</markdown>
```
screen_shot_2022-08-03_at_12 15 07_pm

## Table

I'm not sure if this is a CSS/formatting issue, but if in a `question.html` I write something like this:

```
<markdown>
| $\LaTeX$ | Use   | 
| ---------| ----- |
| $\mu_s$  | mu_s  | 
| $\mu_k$  | mu_k  |
| $g$      | g     |
| $\theta$ | theta |
</markdown>
```

It renders as: 

Screen Shot 2021-05-18 at 9 39 48 PM

It should instead render as a table with lines, rows, etc..:

| $\LaTeX$ | Use   | 
| ---------| ----- |
| $\mu_s$  | mu_s  | 
| $\mu_k$  | mu_k  |
| $g$      | g     |
| $\theta$ | theta |

### LINKED ISSUE #5986: Improper interpretation of code plus formatting in rich text editor
Reported by a student. When using pl-rich-text-editor with markdown format, combining code formatting with italics (or other formatting) causes the formatting in the middle to be interpreted as literal. So the student will, for example, use `<code><em>abc</em></code>` which will cause the `<em>` to be interpreted as text instead of as formatting. Initial debugging seems to be related to showdown not supporting formatting inside code tags, even though browsers typically support it:

image

This seems to be related to showdownjs/showdown#861.

### LINKED ISSUE #6480: Consider replacing showdown with remark/rehype
We're using two libraries for markdown processing: remark, in question markdown parsing; and showdown, in `pl-rich-text-editor` and the preview pane of `pl-file-editor`. Remark seems to be way more robust than showdown (particularly considering issues like #5986), and in combination with rehype can do anything we currently need from showdown, so I suggest we replace all use of showdown with remark/rehype.

### LINKED ISSUE #10026: `pl-richtext-editor` swallows extra line breaks
Definitely unrelated to the recent changes to pl-richtext-editor (#10017, #10012), it seems extra linebreaks are removed from the input.

The culprit might be this line based on the `DOMPurify()` package, but not 100% sure:

https://github.com/PrairieLearn/PrairieLearn/blob/161f7518acaf8aaf0ded29d645d9337e4ad7ce90/apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js#L93

Is this configurable to pass line breaks through ? 

Grading essays without (>1) line breaks will be rough to do 😬.

pl_richtext_space

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Extracted only the client-side code from #10539. Resolves #6480.

Replaces the use of showdown with marked. This package is smaller and easier to customize.

~~* [ ] pl-rich-text-editor: format=markdown no longer converts the submission format to markdown. The option is used only to convert the initial text from markdown to HTML. Pending: test to make sure that none of the HTML generated by quill will end up being interpreted by marked as anything other than raw HTML.~~ Moved to #11391.
* [x] The remark version (server-side) has special handling of math, to ensure `_` and `*` are interpreted by Latex, not markdown, when inside `$...$` blocks. Does this need to be ported to marked client-side?

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
> * Pending: test to make sure that none of the HTML generated by quill will end up being interpreted by marked as anything other than raw HTML.

I tested a bit locally, and the only situation where the output of quill would generate any actual like break is within a `pre` tag, all other HTML output is generated in a single line. I then tested adding markdown within separate blank lines within a `pre` object. This causes marked to, in some occasions, convert code that is not supposed to be converted. I'm working on a way to handle this.

```console
> marked.parse('abc *def* adsf')
'<p>abc <em>def</em> adsf</p>\n'
> marked.parse('<pre>abc *def* adsf</pre>')
'<pre>abc *def* adsf</pre>'
> marked.parse('<pre>abc\n\n*def*\n\nadsf</pre>')
'<pre>abc\n\n*def*\n\nadsf</pre>'
> marked.parse('<p>abc\n\n*def*\n\nadsf</p>')
'<p>abc\n\n<p><em>def</em></p>\n<p>adsf</p></p>\n'
> marked.parse('<p>abc</p><pre>abc\n\n*def*\n\nadsf</pre>')
'<p>abc</p><pre>abc\n\n<p><em>def</em></p>\n<p>adsf</pre></p>\n'
>
```

The issue is examplified in the Markdown specs: https://spec.commonmark.org/0.31.2/#example-148

**Comment by jonatanschroeder** [comment]
> * The remark version (server-side) has special handling of math, to ensure `_` and `*` are interpreted by Latex, not markdown, when inside blocks. Does this need to be ported to marked client-side?

This is already a problem in showdown, though it depends on the case. In the preview box of pl-file-editor, in showdown `$b*c*d$` will render as Math, $b *c* d$ will put the `c` in italics and not render math. In marked the `c` is in italics in both cases. It probably makes sense to take a look at it for consistency.

**Comment by jonatanschroeder** [comment]
> > * The remark version (server-side) has special handling of math, to ensure `_` and `*` are interpreted by Latex, not markdown, when inside blocks. Does this need to be ported to marked client-side?
> 
> This is already a problem in showdown, though it depends on the case. In the preview box of pl-file-editor, in showdown `$b*c*d$` will render as Math, `$b *c* d$` will put the `c` in italics and not render math. In marked the `c` is in italics in both cases. It probably makes sense to take a look at it for consistency.

This is now resolved in 8869b684e4fde1ba702eb71e81d9365459b81cf7. The preview includes an extension to marked that captures strings in the form `$...$` and escapes them to be interpreted by Markdown. Pending: deal with other Mathjax strings (e.g., `\(`) and potentially implement this in `pl-xss-safe` as well.

File: apps/prairielearn/elements/pl-file-editor/pl-file-editor.js [hunk 1]
```diff
@@ -292,12 +292,35 @@ window.PLFileEditor.prototype.b64EncodeUnicode = function (str) {
...
+        marked = (await import('marked')).marked;
+        const startMath = /(\$|\\\(|\\\[)/;
+        marked.use({
+          extensions: [
+            {
+              name: 'math',
+              level: 'inline',
+              start: (src) => src.match(startMath)?.index,
+              tokenizer(src) {
+                if (!src.match(startMath)?.index !== 0) return false;
```
[the remark this answers is not in the document]
Comment (jonatanschroeder) [reply apps/prairielearn/elements/pl-file-editor/pl-file-editor.js:307]: Fixed in bbb382d35397add59413a5f619caf6cfd1f8e538.

**Comment by jonatanschroeder** [comment]
> > * Pending: test to make sure that none of the HTML generated by quill will end up being interpreted by marked as anything other than raw HTML.
> 
> I tested a bit locally, and the only situation where the output of quill would generate any actual like break is within a `pre` tag, all other HTML output is generated in a single line. I then tested adding markdown within separate blank lines within a `pre` object. This causes marked to, in some occasions, convert code that is not supposed to be converted. I'm working on a way to handle this.

If #11385 is merged this point becomes moot.

**Comment by mwest1066** [comment]
> what should be done with `abcd \\$e*f*g\\$`? Markdown [interprets `\\` as `\`](https://www.markdownguide.org/basic-syntax/#characters-you-can-escape), so if I don't handle it properly, this becomes `\$a*b*c\$`, which again becomes non-Mathjax but with raw text (i.e., it shows `$e*f*g$` without formatting). In essence we have two escapes that contribute to each other.

Am I correct in thinking that we apply the `\$` escape as part of the initial math processing, before we do any markdown processing? That seems reasonable to me. In this case, `abcd \\$e*f*g\\$` would be processed as:
1. First our math processing escapes the `\$` sequences, giving `abcd \$e*f*g\$`. We don't process any of this as math.
2. Next, the markdown processing handles the `\` characters. My understanding is that `\` only escapes a certain set of characters, which doesn't include `$`, so `\$` will remain as `\$`.
3. Markdown interprets the `*` characters as italics, so we end up with `abcd \$efg\$` where the `f` is in italics.

This is exactly what GitHub does with this string: "abcd \\$e*f*g\\$"

**Comment by jonatanschroeder** [comment]
@mwest1066 the issue is that mathjax comes after this point and removes the extra backslash.  Should I add an extra slash to avoid that?

**Comment by jonatanschroeder** [comment]
So I tested on a question.html file with the following code:

```html
<p>$a*b*c$</p>
<p>\$a*b*c\$</p>
<p>\\$a*b*c\\$</p>
<p>\\\$a*b*c\\\$</p>
<p>\\\\$a*b*c\\\\$</p>
<p>\\\\\$a*b*c\\\\\$</p>

<hr/>

<div class="mathjax_ignore">
<p>$a*b*c$</p>
<p>\$a*b*c\$</p>
<p>\\$a*b*c\\$</p>
<p>\\\$a*b*c\\\$</p>
<p>\\\\$a*b*c\\\\$</p>
<p>\\\\\$a*b*c\\\\\$</p>
</div>

<hr/>

<markdown>
$a*b*c$

\$a*b*c\$

\\$a*b*c\\$

\\\$a*b*c\\\$

\\\\$a*b*c\\\\$

\\\\\$a*b*c\\\\\$
</markdown>
```

This was rendered to:

```html
<p>$a*b*c$</p>
<p>\$a*b*c\$</p>
<p>\\$a*b*c\\$</p>
<p>\\\$a*b*c\\\$</p>
<p>\\\\$a*b*c\\\\$</p>
<p>\\\\\$a*b*c\\\\\$</p>

<hr>

<div class="mathjax_ignore">
<p>$a*b*c$</p>
<p>\$a*b*c\$</p>
<p>\\$a*b*c\\$</p>
<p>\\\$a*b*c\\\$</p>
<p>\\\\$a*b*c\\\\$</p>
<p>\\\\\$a*b*c\\\\\$</p>
</div>

<hr>

<p>$a*b*c$</p>
<p>$a<em>b</em>c$</p>
<p>\$a*b*c\\$</p>
<p>\$a<em>b</em>c\$</p>
<p>\\$a*b*c\\\\$</p>
<p>\\$a<em>b</em>c\\$</p>
```

and rendered as:

image

It seems to me that:

* Mathjax is not only handling `$`, but is also escaping backslashes (`\\` becomes `\`). This is clearly done by Mathjax because this behaviour does not happen inside the `mathjax_ignore` class (I tested without `$` in a different part and saw the same result.
* The markdown processing server-side via remark/rehype also replaces `\\` with `\`, causing some double-escaping in Markdown cases. In a separate part I tested `\\\\` in Markdown, and it was rendered as `\\` in HTML and `\` in the final view, presumably since each pair was escaped by Markdown and the pair was then escaped by Mathjax.
* The use of `remark-math` to detect math blocks seems to provide some curious behaviour in the context above. In particular, `\\` is ignored inside math blocks. That said, it properly ignores `\$` in the same way as Mathjax, but because it removes the escape, Mathjax still triggers math mode in the context.

So the issue is: how do we make sure that the escaping of backslashes and Math delimiters (1) do not conflict with each other and (2) are not applied twice unnecessarily. This needs to be done both in server-side code (currently using remark-rehype) and in client-side code (the subject of this PR.

**Comment by jonatanschroeder** [comment]
A quick summary of what was discussed in the meeting:

* `$xyz$` should render as math (no question here).
* `\$` should render as `$`. The processing should be done in such a way that this is only escaped once, i.e., markdown should input whatever is necessary for Mathjax to do the proper thing here (either escape it to something like `\$` or force mathjax to ignore it, e.g., with `<span class="mathjax_ignore">$</span>`).
* `\\$` should ideally render as `\$`. Similar notes as item above.
* Any escaping done by markdown should be done in such a way that mathjax does not escape it again, including an isolated `\\` outside of math environments.
* Beyond two backslashes this is a bit of bikeshedding, provided it is consistent.
* Getting this clear client-side is a priority, since explaining the rules for instructors is easier than doing it for students, but eventually we may want to use similar rules server-side as well.

**Comment by jonatanschroeder** [comment]
I was able to get a pretty good implementation of a reasonable handling of escaped characters, by ensuring that any `text` token identified by marked that is not math is rendered with a `mathjax_ignore` class. This allows me to rely on the escaping created by marked and only trigger mathjax where appropriate, i.e., where math is expected to be rendered. I tested this with combination of elements, such as code spans, code blocks, formatting, links, headings, lists, tables, etc., as well as combination of math delimiters, such as `$` and `\(` for inline math and `$$` and `\[` for block math, and a combination of escape patterns, including HTML and Markdown special characters inside and outside math blocks, and it's all working consistently and predictably.

The next step now is to move the marked extension to a package, so it can be reused in multiple elements (such as pl-xss-safe and possibly pl-rich-text-editor). A future PR may use the same extension also in server-side code, but that may require some rewriting as the current implementation depends on MathJax being available (as a global) to perform the math "finding" process.

**Comment by mwest1066** [comment]
> I was able to get a pretty good implementation of a reasonable handling of escaped characters, by ensuring that any `text` token identified by marked that is not math is rendered with a `mathjax_ignore` class. This allows me to rely on the escaping created by marked and only trigger mathjax where appropriate, i.e., where math is expected to be rendered. I tested this with combination of elements, such as code spans, code blocks, formatting, links, headings, lists, tables, etc., as well as combination of math delimiters, such as `$` and `\(` for inline math and `$$` and `\[` for block math, and a combination of escape patterns, including HTML and Markdown special characters inside and outside math blocks, and it's all working consistently and predictably.

Very nice approach!

> The next step now is to move the marked extension to a package, so it can be reused in multiple elements (such as pl-xss-safe and possibly pl-rich-text-editor). A future PR may use the same extension also in server-side code, but that may require some rewriting as the current implementation depends on MathJax being available (as a global) to perform the math "finding" process.

In case it's helpful, I believe that we can run MathJax on the server as well. I've mainly seeing people doing this to pre-render the math, but perhaps the math-finding code can be used separately?

File: apps/prairielearn/elements/pl-file-editor/pl-file-editor.js [hunk 2]
```diff
@@ -292,12 +292,14 @@ window.PLFileEditor.prototype.b64EncodeUnicode = function (str) {
...
-
-    return async (value) => markdownRenderer.makeHtml(value);
+    let marked = null;
+    return async (value) => {
+      if (marked == null) {
+        marked = (await import('marked')).marked;
+        (await import('@prairielearn/marked-mathjax')).addMathjaxExtension(marked, MathJax);
+      }
+      return await marked.parse(value);
+    };
```
[the remark this answers is not in the document]
Comment (jonatanschroeder) [reply apps/prairielearn/elements/pl-file-editor/pl-file-editor.js:302]: `@prairielearn/marked-mathjax` takes care of this issue.

File: apps/prairielearn/elements/pl-xss-safe/pl-xss-safe.mustache [hunk 3]
```diff
@@ -1,17 +1,15 @@
...
     // confusion
     if (language == "markdown") {
-      let renderer = new showdown.Converter({
-        'literalMidWordUnderscores':true,
-        'literalMidWordAsterisks':true,
-      });
-      code = renderer.makeHtml(code);
+      const marked = (await import('marked')).marked;
+      (await import('@prairielearn/marked-mathjax')).addMathjaxExtension(marked, MathJax);
+      code = await marked.parse(code);
```
Comment (nwalters512) [inline apps/prairielearn/elements/pl-xss-safe/pl-xss-safe.mustache:12]: Does `marked.parse` return a promise or a value directly? The presence of `await` is inconsistent throughout this PR.

File: packages/marked-mathjax/src/index.ts [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+/**
+ * Adds an extension to marked to handle math in a manner compatible with our
+ * use of Mathjax in PrairieLearn.
+ *
+ * @param marked - The marked instance to extend.
+ * @param MathJax - The MathJax instance to use for rendering math. In
+ * client-side code, this is `window.MathJax`. In server-side code, this
+ * is the result of `require('mathjax-full').init()`.
+ */
+export function addMathjaxExtension(marked: Marked, MathJax: MathJaxObject) {
```
Comment (nwalters512) [inline packages/marked-mathjax/src/index.ts:15]: Can we write any tests for this function? IIRC the way math is handled isn't trivial, so it'd be great to see some examples of what it should do in different scenarios (in addition to all the usual benefits of tests).

File: packages/marked-mathjax/package.json [hunk 5]
```diff
@@ -0,0 +1,22 @@
...
+  },
+  "private": true,
+  "main": "./dist/index.js",
+  "scripts": {
+    "build": "tsc"
+  },
+  "devDependencies": {
+    "@prairielearn/tsconfig": "workspace:^",
+    "marked": "^15.0.7",
+    "mathjax-full": "^3.2.2",
```
Comment (nwalters512) [inline packages/marked-mathjax/package.json:18]: This package is 34MB. Say more about why we need this and not just the normal `mathjax` dependency we use elsewhere?

**Review by nwalters512 — COMMENTED** [review]
I'd really love to see tests before this is merged.

File: packages/marked-mathjax/package.json (hunk 5 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/package.json:18]: At this point it's mostly for typing, which is not available in `mathjax`. The `@types/mathjax` package is for the previous version of mathjax and is not suitable here.

A bigger extent of `mathjax-full` will become necessary if/when we implement server-side. If you'd prefer to push this for when it's actually needed I can remove this dependency and have MathJax be untyped (`any`) or copy just a subset of relevant types around. I can also take a brief look at other options, but I tried before and didn't find much.

File: packages/marked-mathjax/src/index.ts (hunk 4 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts:15]: This would require a bit of juggling to get a MathJax object passed as parameter. This is possible, but would probably require a limited version of server-side MathJax support (see other comment).

File: apps/prairielearn/elements/pl-xss-safe/pl-xss-safe.mustache (hunk 3 above)
Comment (jonatanschroeder) [reply apps/prairielearn/elements/pl-xss-safe/pl-xss-safe.mustache:12]: Good catch! `marked.parse` [can return a promise if `marked` is initialized with `async: true`](https://marked.js.org/using_pro#async), but this isn't done in this context, so I'll remove it where it's not needed.

File: packages/marked-mathjax/src/index.ts (hunk 4 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts]: I managed to do it, but MathJax does not support modules, so I had to work with a CJS require instead. I added a few tests, will continue with more tests tomorrow.

File: packages/marked-mathjax/package.json (hunk 5 above)
Comment (nwalters512) [reply packages/marked-mathjax/package.json]: I'm happy to either have it be untyped, or just inline the relevant part.

It's still not clear to me why `mathjax-full` is needed on the server. The normal `mathjax` package specifically shows usage in Node: https://www.npmjs.com/package/mathjax#using-mathjax-components-in-a-node-application

Comment (jonatanschroeder) [reply packages/marked-mathjax/package.json]: Indeed, I realized that later. The only minor issue (other than missing types) is that it doesn't support modules/import, so we need a `require('mathjax')` to make it work.

Comment (jonatanschroeder) [reply packages/marked-mathjax/package.json]: I have used `any` type in 9069240.

File: packages/marked-mathjax/src/index.ts (hunk 4 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts]: Tests added in 5814e73831111cf024f5892bdb003bace106893d and 5a8ff142bb28ca4147d4e56fa83825540ed2140a.

Comment (nwalters512) [reply packages/marked-mathjax/src/index.ts]: How are you running the tests? I'd expect to see a `test` script in `scripts` in the package's `package.json`; see most other packages for examples of this. You'd also want `mocha`, `tsx`, etc. as dev dependencies.

File: apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js [hunk 6]
```diff
@@ -110,26 +110,22 @@
...
-        literalMidWordAsterisks: true,
-      });
-    }
 
     if (options.markdownShortcuts && !options.readOnly) new QuillMarkdown(quill, {});
 
     let contents = atob(inputElement.val());
-    if (contents && renderer) contents = renderer.makeHtml(contents);
+    if (contents && options.format === 'markdown') {
+      const marked = (await import('marked')).marked;
```
Comment (jonatanschroeder) [inline apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js:118]: Since pl-rich-text-editor has some different ways to handle math, and assuming it's not expected to be available in the provided text from the question, I haven't added support for mathjax here.

File: apps/prairielearn/elements/pl-file-preview/pl-file-preview.js [hunk 7]
```diff
@@ -133,10 +133,6 @@
                     import('dompurify'),
                     import('notebookjs'),
                   ]).then(async ([Marked]) => {
-                    // Showdown has a small bug that doesn't allow it to be loaded dynamically.
-                    // This PR will fix it: https://github.com/showdownjs/showdown/pull/1017
-                    // Since the PR could take two weeks or two months, let's used Marked for now
-                    // and get this feature deployed.
                     nb.markdown = Marked.marked.parse;
```
Comment (jonatanschroeder) [inline apps/prairielearn/elements/pl-file-preview/pl-file-preview.js:136]: I haven't handled mathjax in the preview of notebook files, is it needed?

File: apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js [hunk 8]
```diff
@@ -165,7 +161,10 @@
       if (counter) {
         counter.update();
       }
-    });
+    };
+
+    quill.on('text-change', updateHiddenInput);
+    updateHiddenInput();
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js:167]: I noticed this just the other day while working on the `ai_grading` rendering for this element, I was going to make an issue. Nice fix!

File: packages/marked-mathjax/src/index.ts (hunk 4 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts]: Ah, I was running mocha directly in the test file. I'll add a test script.

Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts]: This is fixed in dabe61c628b4a6cec936e31b6f9dd59855bd265c and 13fa6d2178aefd1d7bf1cb863aa5cc031f45c59c.

File: packages/marked-mathjax/src/index.test.ts [hunk 9]
```diff
@@ -0,0 +1,111 @@
...
+
+async function testMarkdown(original: string, expected: string) {
+  const actual = await marked.parse(original);
+  assert.equal(actual.toString().trim(), expected);
+}
+
+describe('Markdown processing', () => {
+  before(async () => {
+    // MathJax does not support ESM, so we need to use CommonJS to load it.
+    const require = createRequire(import.meta.url);
```
[the remark this answers is not in the document]
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.test.ts:18]: image

`@types/mathjax` is out-of-date, it uses v2.x whereas `mathjax` is v3.x.

[the remark this answers is not in the document]
Comment (nwalters512) [reply packages/marked-mathjax/src/index.test.ts:18]: Why does that matter? `createRequire` + `require` doesn't give any more or less type safety. This is a great use case for `// @ts-expect-error`.

[the remark this answers is not in the document]
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.test.ts:18]: I was not aware that this could be ignored, TIL. Changed to an import in 52bb69e85caa397d0e0ce678db39540c12097cd3.

File: apps/prairielearn/elements/pl-file-preview/pl-file-preview.js (hunk 7 above)
Comment (nwalters512) [reply apps/prairielearn/elements/pl-file-preview/pl-file-preview.js:136]: It's already handled here, right?

https://github.com/PrairieLearn/PrairieLearn/blob/ad778ab3370b197aa413f2c69684f66e9f5c45b8/apps/prairielearn/elements/pl-file-preview/pl-file-preview.js#L150-L151

Comment (nwalters512) [reply apps/prairielearn/elements/pl-file-preview/pl-file-preview.js:135]: Ahhh, I see. Check `demo/workspace/jupyterlab` in the example course, it includes the following Markdown cell:

```
The Fibonacci numbers are 1, 1, 2, 3, 5, 8, ..., where each number is the sum of the two before it. These are numbered $F_1, F_2, \ldots$, and

$$F_n = F_{n-1} + F_{n-2}.$$
```

I think the underscores in there could be considered "math that can be interpreted as markdown".

Comment (jonatanschroeder) [reply apps/prairielearn/elements/pl-file-preview/pl-file-preview.js:139]: It was indeed needed, changing the math to add some spaces caused `_` to be interpreted as markdown. Updated in 03e677d4f7cb5e4aa7b8bcb137bf483f6051771c.

File: apps/prairielearn/elements/pl-file-preview/pl-file-preview.js [hunk 10]
```diff
@@ -132,10 +132,10 @@
                     import('dompurify'),
                     import('notebookjs'),
                   ]).then(async ([Marked]) => {
-                    // Showdown has a small bug that doesn't allow it to be loaded dynamically.
-                    // This PR will fix it: https://github.com/showdownjs/showdown/pull/1017
-                    // Since the PR could take two weeks or two months, let's used Marked for now
-                    // and get this feature deployed.
+                    (await import('@prairielearn/marked-mathjax')).addMathjaxExtension(
```
Comment (nwalters512) [inline apps/prairielearn/elements/pl-file-preview/pl-file-preview.js:135]: Consider moving the import up into `Promise.all`.

**Review by nwalters512 — COMMENTED** [review]
I went looking for usages of `showdown` to see if we could remove the dependency entirely. Unfortunately, a lot of courses forked `pl-rich-text-editor`, and the `showdown` usage came along with it. I opened https://github.com/PrairieLearn/PrairieLearn/issues/11900 to track that.

File: packages/marked-mathjax/src/index.test.ts [hunk 11]
```diff
@@ -0,0 +1,109 @@
...
+      },
+      loader: { load: ['input/tex'] },
+    });
+    addMathjaxExtension(marked, MathJax);
+  });
+
+  it('renders basic markdown correctly', async () => {
+    const question = '# Hello, world!\nThis **works**.';
+    const expected =
+      '<h1><span class="mathjax_ignore">Hello, world!</span></h1>\n<p><span class="mathjax_ignore">This </span><strong><span class="mathjax_ignore">works</span></strong><span class="mathjax_ignore">.</span></p>';
```
[the remark this answers is not in the document]
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.test.ts:33]: > Is is strictly necessary to wrap _all_ text with `<span class="mathjax_ignore">`? Can we do that only for strings that could potentially actually contain math (that is, one of the delimiters)?

Sure, I can try to handle that. I will include the math delimiters as well as any escape character (`\\`), since MathJax also tries to replace those.

[the remark this answers is not in the document]
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.test.ts]: Done in 375bdf1f67893b8b60d0dfca5fd6501d564a7e06.

File: apps/prairielearn/elements/pl-file-preview/pl-file-preview.js [hunk 12]
```diff
@@ -125,17 +125,15 @@
...
                 const text = await blob.text();
                 if (escapedFileName.endsWith('.ipynb')) {
-                  // importing the notebookjs library doesn't return an object, it sets the global variable 'ns'
-                  // importing DOMPurify sets the global variable DOMPurify.
                   await Promise.all([
                     import('marked'),
+                    import('@prairielearn/marked-mathjax'),
+                    // importing DOMPurify sets the global variable DOMPurify.
                     import('dompurify'),
+                    // importing the notebookjs library doesn't return an object, it sets the global variable 'ns'
```
Comment (nwalters512) [inline apps/prairielearn/elements/pl-file-preview/pl-file-preview.js:133]:
```suggestion
                    // importing the notebookjs library sets the global variable `nb`.
```

File: apps/prairielearn/elements/pl-file-preview/pl-file-preview.js [hunk 13]
```diff
@@ -125,17 +125,15 @@
               if (type === 'text/plain') {
                 const text = await blob.text();
                 if (escapedFileName.endsWith('.ipynb')) {
-                  // importing the notebookjs library doesn't return an object, it sets the global variable 'ns'
-                  // importing DOMPurify sets the global variable DOMPurify.
                   await Promise.all([
                     import('marked'),
+                    import('@prairielearn/marked-mathjax'),
+                    // importing DOMPurify sets the global variable DOMPurify.
```
Comment (nwalters512) [inline apps/prairielearn/elements/pl-file-preview/pl-file-preview.js:131]:
```suggestion
                    // importing DOMPurify sets the global variable `DOMPurify`.
```

File: apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js [hunk 14]
```diff
@@ -67,7 +67,7 @@
 
   Quill.register('modules/clipboard', PotentiallyDisabledClipboard, true);
 
-  window.PLRTE = function (uuid) {
+  window.PLRTE = async function (uuid) {
```
Comment (nwalters512) [inline apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js:70]: Nit, the Mustache template has something like this:

```js
var rte = window.PLRTE(...);
```

Maybe best to just remove the variable assignment?

I'm mildly uneasy about using async functions at the top level (either called in a `<script>` tag or in `$(() => { ... })`) mainly because of error handling, but in practice this shouldn't really cause problems even if there are errors. That uneasiness is probably just coming from experience with Node where we really don't want unhandled errors/rejections.

File: packages/marked-mathjax/src/index.ts [hunk 15]
```diff
@@ -0,0 +1,76 @@
...
+ * Adds an extension to marked to handle math in a manner compatible with our
+ * use of Mathjax in PrairieLearn.
+ *
+ * @param marked - The marked instance to extend.
+ * @param MathJax - The MathJax instance to use for rendering math. In
+ * client-side code, this is `window.MathJax`. In server-side code, this
+ * is the result of `require('mathjax-full').init()`.
+ */
+export function addMathjaxExtension(marked: Marked, MathJax: any) {
+  const mathjaxInput = MathJax.startup.getInputJax() ?? [];
```
Comment (nwalters512) [inline packages/marked-mathjax/src/index.ts:15]: Is there any potential for a race condition here where this is undefined? This isn't part of the `MathJax.startup` object that we ourselves attach to the window, so I this is always relying on MathJax having loaded:

https://github.com/PrairieLearn/PrairieLearn/blob/537588c0d86d9c5e5a53bd303f26cb7e448cd16d/apps/prairielearn/assets/scripts/lib/mathjax.ts#L46-L67

File: packages/marked-mathjax/src/index.ts [hunk 16]
```diff
@@ -0,0 +1,76 @@
...
+      // * Text inside some elements (e.g., list items) will call the renderer
+      //   with child tokens for preprocessing, we return false so the default
+      //   renderer renders the children individually.
+      // * After child tokens are rendered, this renderer is called again with
+      //   the result (and escaped set to true). At that point the text is
+      //   already rendered with escape characters as needed, so nothing to do.
+      text: (token) => {
+        if (token.type === 'text' && (token.tokens || token.escaped)) return false;
+        if (token.text.match(/[$\\]/)) {
+          return `<span class="mathjax_ignore">${token.text}</span>`;
```
Comment (nwalters512) [inline packages/marked-mathjax/src/index.ts:31]: Does this do the right thing if `token.text` itself contains HTML entities? seeing things interpolated directly into an HTML string raises some small alarm bells for me but MathJax could just be doing the correct thing here. Just want to double check.

Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts:31]: It does. In that case, there are two options:

* In most cases, if there is a string like `abc<em>def</em>ghi`, this function will be called separately with the tokens `abc`, `def` and `ghi`. The `<em>def</em>` token will be considered an html token, and the inner text `def` is a child of that token.
* In some cases (e.g., when a list is created), this is called with the whole text unbroken, but with `token.tokens` set to a list of child tokens. This is handled a couple of lines up, by returning false. In that case, the return false will cause the default renderer to be called, and that renderer will call this function again for each individual token, as listed above.

So in essence, if `token.tokens` and `token.escaped` are both falsy, then the text itself is already HTML-free.

image
image

Comment (nwalters512) [reply packages/marked-mathjax/src/index.ts:31]: Thanks for the explanation! Maybe worth a test case if we don't have one already?

Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts:31]: We have tests for these issues individually, I added a few combinations of cases in 803cac9cc2e72a98b7adbedb967c5480ae4f3b9f.

File: apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js (hunk 14 above)
Comment (jonatanschroeder) [reply apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js:70]: Removed variable in 357a91d8c2ad9e1718e060607ff5eebddde91e5c. I also added a comment that we're deliberately calling an async function without await. An alternative to this model could be a selector-observer in the JS file itself that is called when the element is loaded into the DOM, but I think that may be unnecessary complexity.

File: packages/marked-mathjax/src/index.ts (hunk 15 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts:16]: To ensure we don't end up with a race condition I have added a call to `MathJax.typesetPromise()` before every call to `addMathjaxExtension` in ee943d3cf684c2c070c1f0e3a280749f7c484a32.

I considered making this call inside `addMathjaxExtension` itself, but this could be a problem because, AFAIK, mathjax replaces `window.MathJax` with a new object instead of updating it, meaning the argument to `addMathjaxExtension` would no longer match `window.Mathjax` if the promise was unresolved on call.

Comment (nwalters512) [reply packages/marked-mathjax/src/index.ts:16]: `MathJax.startup.promise` is probably a better thing to await. That'll resolve once things are up and running without actually re-typesetting the entire document.

Agreed that we shouldn't do that in `addMathjaxExtension`. I think that would in theory complicate server-side things.

File: packages/marked-mathjax/src/index.ts [hunk 17]
```diff
@@ -0,0 +1,77 @@
...
+
+/**
+ * Adds an extension to marked to handle math in a manner compatible with our
+ * use of Mathjax in PrairieLearn.
+ *
+ * @param marked - The marked instance to extend.
+ * @param MathJax - The MathJax instance to use for rendering math. In
+ * client-side code, this is `window.MathJax` (ensure `Mathjax.typesetPromise()`
+ * has been resolved). In server-side code, this is the result of
+ * `require('mathjax-full').init()`.
```
Comment (nwalters512) [inline packages/marked-mathjax/src/index.ts:13]: We're no longer using `mathjax-full`.

File: packages/marked-mathjax/src/index.ts (hunk 15 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts:16]: Good point, I forgot that there were two different promises in play. Changed in 4d5ebe79d5c516b50025de71ee40b6829230c853.

File: packages/marked-mathjax/src/index.ts (hunk 17 above)
Comment (jonatanschroeder) [reply packages/marked-mathjax/src/index.ts]: Updated in 4d5ebe79d5c516b50025de71ee40b6829230c853.

**Comment by nwalters512** [comment]
While this is basically ready to go, I'm going to hold off approving + merging until we're clear of finals season.

**Comment by jonatanschroeder** [comment]
I believe UIUC finals are done, right? Can we proceed with this?

**Review by nwalters512 — APPROVED** [review]
Let's do it!
