### PR TITLE
Fix file preview handling of TS files

### LINKED ISSUE #14250: Content preview support for TypeScript files
### Details

I am working on an external grader for TypeScript files, but students are unable to use the `show preview` feature for these files. This is designated as a bug because these are just text files and should be renderable as plain text, no highlighting is required (unless there is a JavaScript source renderer which almost certainly would highlight TypeScript files as well). 

Could TypeScript files be added to the supported preview types, even if only as text?

Image

### PR DESCRIPTION
**Pull request by jonatanschroeder**
# Description

Fixes #14250. The video/mp2t mime-type is associated to the .ts extension, which is also used by TypeScript files. This PR removes this mime-type from allowed media prefixes, since it is uncommon enough (and particularly significantly less common than TypeScript), so that the decision is based on if the file is binary or not.

Functionality created without AI. Unit test created with GPT-5.3 codex.

# Testing

Created a question with file upload (or editor, or workspace) with a .ts extension. In master this will not allow preview, in this branch it should preview the text.

### CODE REVIEW

File: apps/prairielearn/src/pages/submissionFile/submissionFile.ts [hunk 1]
```diff
@@ -15,6 +15,10 @@ import { selectAndAuthzVariant } from '../../models/variant.js';
 const sql = sqldb.loadSqlEquiv(import.meta.url);
 
 const MEDIA_PREFIXES = ['image/', 'audio/', 'video/', 'application/pdf'];
+// The video/mp2t mime uses a .ts extension, which conflicts with Typescript files.
+// In such cases we fallback to a verification if a file is binary or not
+// instead of a blindly trusting the mimetype from the name.
+const MEDIA_PREFIX_EXCEPTIONS = ['video/mp2t'];
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/pages/submissionFile/submissionFile.ts:21]: An alternative to this is to use a package like https://github.com/humphd/browser-mime instead of mime to only accept image/audio/video formats that are typically supported by browsers, which would reject mp2t anyway, as well as other obscure file types. Since the idea of having these is to allow browsers to parse them, I don't think there's a strong reason to support media files not accepted by browsers anyway.

Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/submissionFile/submissionFile.ts:21]: The problem with that approach is that browser-mime is unmaintained (last release 2019), and I couldn't find any more recent package. So we either add these exceptions, or keep a whitelist of accepted image/video/audio files (see https://developer.mozilla.org/en-US/docs/Web/HTTP/Guides/MIME_types#image_types, https://developer.mozilla.org/en-US/docs/Web/Media/Guides/Formats/Containers#index_of_media_container_formats_file_types).

File: exampleCourse/questions/element/fileUpload/question.html [hunk 2]
```diff
@@ -16,7 +16,7 @@
 
   A single <code>pl-file-upload</code> element can use any combination of mandatory and optional file names and patterns. For example, the following element requires the upload of a Python file named "solution.py" and 2 additional Python files, and also allows an optional "explanation.txt" file and arbitrarily many additional Python files to be uploaded. 
 
-  <pl-file-upload file-names="solution.py" file-patterns="*.py,*.py" optional-file-names="explanation.txt" optional-file-patterns="*.py"></pl-file-upload>
+  <pl-file-upload file-names="solution.ts" file-patterns="*.py,*.py" optional-file-names="explanation.txt" optional-file-patterns="*.py"></pl-file-upload>
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply exampleCourse/questions/element/fileUpload/question.html]: This comment is correct. Presumably this change is left over from testing?

File: apps/prairielearn/src/pages/submissionFile/submissionFile.ts (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/src/pages/submissionFile/submissionFile.ts:21]: I think the approach you already took in this PR is fine, but I'm also not opposed to specific allowlists. The lists don't look too long and MDN seems like a good source for them.

Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/submissionFile/submissionFile.ts:21]: Discussed on Slack. We'll keep the current blacklist approach for now, if the problem recurs we may investigate other options. One alternative considered was to maintain a list of types supported by browsers (populated with (canPlayType)[https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement/canPlayType] on a modern browser, or something similar, but that requires maintaining this list if browsers end up supporting new types. Since the TS video type is typically only used in streaming, not in regular files, it should be safe to consider it an exception.

File: exampleCourse/questions/element/fileUpload/question.html (hunk 2 above)
[the remark this answers is not in the document]
Comment (jonatanschroeder) [reply exampleCourse/questions/element/fileUpload/question.html]: Indeed it was added by mistake. Removed in 46f26d4b1de8d84d237988da148a7b46432e3573.

**Review by nwalters512 — APPROVED** [review]
