### PR TITLE
Fix check for blank answer in pl-rich-text-editor

### LINKED ISSUE #10011: pl-richtext-editor element does not mark submissions as invalid if a previous submission was valid
I think this is a bug, but might be a deliberate choice so reporting the issue here for discussion.

I've just noticed that if a submission to a `pl-richtext-editor` element is valid (i.e. put in any text), then if you remove that text and try another submission, the submission doesn't get flagged as invalid. In fact, the format_error is also removed even from the first submission.

Here's a gif of what I mean:

pl_richtext_bug

This is in contrast to the `integer-input` element, which behaves as expected under the same conditions

Screenshot 2024-06-13 at 12 50 38 AM

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Resolves #10011. In essence ensures that if the content is blank, then a blank answer is sent to the input, so that the appropriate check can be done for missing answer. This was not the case if you type something then delete it.

This uses `quill.editor.isBlank()` as a means to identify if the answer is empty or not. This is an undocumented API, so the code is written to have a bit of control so that, if the function ceases to exist in the future, the code doesn't break.

The code will be considered blank in the same scenarios where Quill shows the placeholder, so things like adding a space or an empty list item will not be considered blank.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
For context: using `quill.getText()` generates a false positive if there is an image, so is not a good option.

File: apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js [hunk 1]
```diff
@@ -48,7 +48,9 @@
     quill.setContents(quill.clipboard.convert({ html: contents }));
 
     quill.on('text-change', function () {
-      let contents = rtePurify.sanitize(quill.getSemanticHTML(), rtePurifyConfig);
+      let contents = quill.editor?.isBlank?.()
```
Comment (nwalters512) [inline apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js:51]: I opened https://github.com/slab/quill/issues/4254 to see if they'd be willing to commit to this as part of the public API. That said, I'd like to see the reason for the optional chaining documented here, probably with a link to that issue.

IMO it'd also be nice to inline some of the context from your PR:

- Why we need the check for `isBlank()`
- Why we can't use `getText().trim() === ''`
- The caveat that this won't do quite what's expected if e.g. someone starts a bulleted list but doesn't put any text in the list items

**Review by nwalters512 — APPROVED** [review]

File: apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js (hunk 1 above)
Comment (jonatanschroeder) [reply apps/prairielearn/elements/pl-rich-text-editor/pl-rich-text-editor.js:70]: Done in b3ed477a7.
