### PR TITLE
handle case if old qid contains spaces

### LINKED ISSUE #11277: Question QID change fails if the old QID contained spaces
Reported by Margaret Fleck: https://prairielearn.slack.com/archives/C266KEH9A/p1738379519300039

Steps to reproduce in local dev:
1. Copy `testCourse/questions/partialCredit1` to `partial Credit 1` (with spaces), edit the new `info.json` to change the UUID, and sync it.
2. In the Settings page for `partial Credit 1`, edit the QID to `partialCredit1test` and click Save.
3. The error below is reported.

Image

### PR DESCRIPTION
**Pull request by mylesw27**
Closes #11277. Currently, if a question path is changed manually to contain a space, this changes the qid changes to  then also contain a space. We then cannot read the existing file in the question settings page and modifying that file will fail. This updates to handle the case of that modification and also prevents sync if the question id contains a space.

### CODE REVIEW

File: apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts [hunk 1]
```diff
@@ -295,14 +294,17 @@ router.get(
...
-    const infoPath = encodePath(path.join('questions', res.locals.question.qid, 'info.json'));
-
-    const fullInfoPath = path.join(res.locals.course.path, infoPath);
-    const questionInfoExists = await fs.pathExists(fullInfoPath);
+    const infoPath = path.join(
+      res.locals.course.path,
+      'questions',
+      res.locals.question.qid,
+      'info.json',
+    );
```
Comment (mylesw27) [inline apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts:302]: I removed `encodePath` here as it was causing the issues of changing a space to '%20'.  However, I realize there is probably a reason we were using `encodePath`. Is there a specific reason we were using this and should I handle this differently here?

File: apps/prairielearn/src/sync/fromDisk/questions.ts [hunk 2]
```diff
@@ -68,6 +68,9 @@ export async function sync(
   courseData: CourseData,
 ): Promise<Record<string, string>> {
   const questionParams = Object.entries(courseData.questions).map(([qid, question]) => {
+    if (qid.includes(' ')) {
+      throw new Error(`Question ID contains a space: ${qid}`);
+    }
```
Comment (mylesw27) [inline apps/prairielearn/src/sync/fromDisk/questions.ts:73]: Currently sync works if a qid contains a space, which from my understanding should not be correct. Let me know if I'm incorrect or if we should error somewhere else because of this.

File: apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts:302]: Ah, so this was the root of the problem? Nice find! Are any other editor pages impacted similarly?

`encodePath` is necessary because `infoPath` is passed to `InstructorQuestionSettings` and then used to construct a URL, where the space -> `%20` conversion is actually important. However, I think we should move the `encodePath` to where it's actually needed (that is, where it's used in the URL). Doing it here is, I think, a remnant of EJS where we couldn't easily call `encodePath` in the template itself.

File: apps/prairielearn/src/sync/fromDisk/questions.ts (hunk 2 above)
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/questions.ts:73]: No, we definitely support this and need to continue supporting it because people have questions in the wild with QIDs that include spaces.

Comment (mylesw27) [reply apps/prairielearn/src/sync/fromDisk/questions.ts]: Removed this in [23832d1](https://github.com/PrairieLearn/PrairieLearn/pull/11284/commits/23832d1d3b35e16175cf4d9bfc345090835b4411).

File: apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts (hunk 1 above)
Comment (mylesw27) [reply apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.ts]: That makes sense. It looks like `encodePath` is being used in the `instructorAssessmentSettings` page in a similar way. I can update that in a subsequent PR. For now, I have moved `encodePath` here to where it is used to construct the URL.

**Review by nwalters512 — APPROVED** [review]
