### PR TITLE
Sync explicitly-created default assessment module

### LINKED ISSUE #8344: Sync error when assessment module is titled "Default"
It seems the sync process ends up in a broken state if one of the assessment modules listed in the course is called "Default" (see https://us.prairielearn.com/pl/course_instance/136540/instructor/edit_error/456925 and discussion on Slack). Not sure if the same error would be caused for sets with this name?

### PR DESCRIPTION
**Pull request by nwalters512**
The syncing code previously assumed that a course would always have an `assessment_modules` row with `number = 0`. However, if an instructor explicitly added an assessment module named "Default", that row would have a non-zero `number`.

This PR changes the assessment syncing code to instead look for some row with `name = 'Default'`, which is guaranteed to have been created by the assessment module syncing code.

Fixes #8344.

### CODE REVIEW

File: apps/prairielearn/src/sprocs/sync_assessment_modules.sql [hunk 1]
```diff
@@ -50,9 +50,13 @@ BEGIN
...
-    INSERT INTO assessment_modules (
-              number, course_id
-    ) VALUES (0,      syncing_course_id)
+    --
+    -- If the instructor has explicitly created a module named "Default",
+    -- we'll use that, including whatever number they've assigned to it.
+    INSERT INTO
+        assessment_modules (name, number, course_id)
+    VALUES
+        ('Default', 0, syncing_course_id)
```
Comment (nwalters512) [inline apps/prairielearn/src/sprocs/sync_assessment_modules.sql:59]: `'Default'` is the default for the `name` column in the table schema, but I figured that adding an explicit `name` here would make it more obvious what's going on.

File: apps/prairielearn/src/tests/sync/assessmentModulesSync.test.js [hunk 2]
```diff
@@ -77,4 +77,29 @@ describe('Assessment modules syncing', () => {
     const syncedCourse = syncedCourses.find((c) => c.short_name === courseData.course.name);
     assert.match(syncedCourse?.sync_warnings, /Found duplicates in 'assessmentModules'/);
   });
+
+  it('uses explicitly-created default assessment module', async () => {
```
Comment (nwalters512) [inline apps/prairielearn/src/tests/sync/assessmentModulesSync.test.js:81]: This test fails on `master` with the exact error that we say in production.

**Review by jonatanschroeder — APPROVED** [review]

File: apps/prairielearn/src/sprocs/sync_assessments.sql [hunk 3]
```diff
@@ -566,11 +566,13 @@ BEGIN
...
 
-    -- Ensure all assessments have an assessment module, default number=0.
+    -- Ensure all assessments have an assessment module. We'll use the "Default"
+    -- module if one is not specified. The assessment module syncing code will
+    -- ensure that such a module exists.
     UPDATE assessments AS a
     SET
         assessment_module_id = COALESCE(a.assessment_module_id,
-            (SELECT id FROM assessment_modules WHERE number = 0 AND course_id = syncing_course_id))
+            (SELECT id FROM assessment_modules WHERE name = 'Default' AND course_id = syncing_course_id))
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/sprocs/sync_assessments.sql:575]: Curiously, this more closely matches what the docs list...

https://github.com/PrairieLearn/PrairieLearn/blob/a7bed786b11dfd79ea92964e2e73207b8c41fbb9/docs/assessment.md?plain=1#L39

Comment (nwalters512) [reply apps/prairielearn/src/sprocs/sync_assessments.sql:575]: This was also the intention of the existing code, which would correctly do that if `"Default"` was created automatically (we explicitly set `number = 0` in that case). But yes, the new code is definitely more correct!
