### PR TITLE
Exclude saved-but-not-graded submissions from question stats

### LINKED ISSUE #1415: instance_questions_calculate_stats incorrectly includes saved-but-not-graded submissions
In `instance_questions_calculate_stats.sql` the first SQL SELECT includes all submissions, but it should filter on `WHERE s.graded_at IS NOT NULL`.

This causes `submission_score_array` to include NULL values for saved-but-not-graded submissions, and sometimes values such as `first_submission_score` might also be NULL.

### PR DESCRIPTION
**Pull request by reteps**
# Description

Fixes #1415. The `select_submissions_for_stats` query includes all gradable submissions when computing instance question statistics, but saved-but-not-graded submissions have NULL scores that pollute `submission_score_array` and downstream aggregations like `array_avg`. This adds a `s.graded_at IS NOT NULL` filter to only include graded submissions.

Majority of implementation assisted by Claude AI.

# Testing

Updated existing test expectations in `exam.test.ts` to reflect that saved-but-not-graded submissions are no longer included in stats arrays.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
This conflicts with #13175 and #13222, with some overlap in changes. Any chance those could be finally reviewed first?

**Comment by jonatanschroeder** [comment]
Now that #13222 is merged this should now be relatively easier to implement. From that PR there is a comment that may apply here:

> Pending potential discussion: for the incremental_submissions_[score|points]_array columns, I'm not convinced of the value of having those stats in play in the way they are currently computed. In particular, their main use is to inform the calculation of the equivalent columns in the assessment questions table, which takes the average for the score and points across each attempt (e.g., average score for first submission, for second submission, etc.). The problem is that this currently includes save-only and non-gradable submissions, which means that a student that saves a submission without grading and then grades it will have their score counted in the second index, while a student that grades right away will have it counted in the first. We may want to revisit these columns and their application to either make them more meaningful and clear or drop them altogether. Also, their functionality is aimed mostly at exam assessments, and the meaning for homework assessments (particularly multi-variant questions) can be a bit muddied.

I believe what you're doing here already handles this concern, though if there's something missing let me know and I can add an issue.

**Comment by jonatanschroeder** [comment]
> Looks like a simple enough change. I'm assuming that dropping `NULL` values from the various statistics arrays won't have any bad downstream impact? cc @mwest1066 if you'd like to look at this.

IMO it actually fixes some inconsistencies downstream, see my other comment.

File: apps/prairielearn/src/lib/question-points.sql [hunk 1]
```diff
@@ -60,6 +60,7 @@ FROM
 WHERE
   v.instance_question_id = $instance_question_id
   AND s.gradable IS TRUE
+  AND s.graded_at IS NOT NULL
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/lib/question-points.sql:63]: If `graded_at` is not null, then `score` is also not null. This could mean this query always returns non-nullable scores, which can simplify some of the logic in the stats calculation process in question-points.ts. I can update these in a follow up PR if you don't want to address it here.

Comment (reteps) [reply apps/prairielearn/src/lib/question-points.sql:63]: That would be great if you can pull this out into a follow-up PR.
