### PR TITLE
Disable AI grading when question does not use manual grading

### LINKED ISSUE #13929: Improve AI grading interface when question does not use manual grading
If one navigates to an assessment question that doesn't have manual points (that is, `max_manual_points` isn't set), one can still enable AI grading mode and perform AI grading and submission grouping. However, both immediately fail with an error message:

https://github.com/PrairieLearn/PrairieLearn/blob/48a743e548afca2402c3a812d574b6b6dad3593a/apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts#L177-L179

Note that even though the server job failed, the job status update alert remained on the page until it was refreshed.

There are two separate things to consider here:

- Make sure that job status updates immediately propagate back to clients via websocket.
- Consider if we should put prevent people from even taking these actions on pages where we know they'll fail.

### PR DESCRIPTION
**Pull request by miguelaenlle**
# Description

Partially resolves #13929 . 
- Disabled AI grading and AI submission grouping on questions that do not use manual grading.

Screenshot 2026-01-27 at 11 57 19 PM

Screenshot 2026-01-27 at 11 57 28 PM

- `aiGrade` throws if the assessment question does not use manual grading before starting the server job.

# Testing

- Perform AI grading on an assessment question that does not use manual grading, e.g. a completely auto-graded question. 
- The AI grading and AI submission grouping dropdowns should be disabled.

### CODE REVIEW

File: apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts
Comment (nwalters512) [inline apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts]: The check that was added above is duplicated here. Should we remove this one in favor of an earlier check (like the one you added in this PR) that can fail before the server job is even started/created?

I think we'd want to apply a similar change to AI submission grouping.

File: apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts [hunk 1]
```diff
@@ -89,6 +89,13 @@ export async function aiGrade({
   instance_question_ids?: string[];
   model_id: AiGradingModelId;
 }): Promise<string> {
+  if (!assessment_question.max_manual_points) {
+    throw new error.HttpStatusError(
+      400,
+      'AI grading is only available on assessment questions that use manual grading.',
+    );
+  }
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts:108]: This check is reasonable, it matches the one used elsewhere:

https://github.com/PrairieLearn/PrairieLearn/blob/48a743e548afca2402c3a812d574b6b6dad3593a/apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts#L177-L179

File: apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts
Comment (miguelaenlle) [reply apps/prairielearn/src/ee/lib/ai-grading/ai-grading.ts]: > Should we remove this one in favor of an earlier check (like the one you added in this PR) that can fail before the server job is even started/created?

I think this is the way to go. 

> I think we'd want to apply a similar change to AI submission grouping.

Sounds good, I'll add this too 👍

File: apps/prairielearn/src/ee/lib/ai-instance-question-grouping/ai-instance-question-grouping.ts [hunk 2]
```diff
@@ -187,6 +187,13 @@ export async function aiInstanceQuestionGrouping({
     throw new HttpStatusError(403, 'Feature not available.');
   }
 
+  if (!assessment_question.max_manual_points) {
+    throw new HttpStatusError(
+      400,
+      'AI submission grouping is only available on assessment questions that use manual grading.',
+    );
+  }
```
[the remark this answers is not in the document]
Comment (miguelaenlle) [reply apps/prairielearn/src/ee/lib/ai-instance-question-grouping/ai-instance-question-grouping.ts:195]: We want it to be rejected if that's the case.

**Comment by miguelaenlle** [comment]
Based on discussion over Zoom, I made the following changes: 
- If an instructor is on an assessment question that does not use manual grading, they'll see this popup if they click "AI grading mode".

AI grading mode appears disabled, but if the user clicks it, they'll see the popup.

Screenshot 2026-02-01 at 8 32 44 PM

Screenshot 2026-02-01 at 8 33 31 PM

- AI grading and AI submission grouping dropdowns are hidden on assessment questions without manual grading.

Also, we decided to not propagate `job.fail` messages to the user via WebSockets yet, since both AI grading `job.fail` calls will be propagated to the user:
- The `job.fail` if `assessmentQuestion.max_manual_points === 0` was moved outside the server job. 
- The `job.fail` if more than one AI grading fails is already handled.

**Comment by miguelaenlle** [comment]
I didn't mean to auto-merge, that was a misclick.

File: apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/components/AssessmentQuestionTable.tsx [hunk 3]
```diff
@@ -720,7 +720,7 @@ export function AssessmentQuestionTable({
         }}
         headerButtons={
           hasCourseInstancePermissionEdit ? (
-            aiGradingMode ? (
+            aiGradingMode && assessmentQuestion.max_manual_points ? (
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/components/AssessmentQuestionTable.tsx]: Nit, consider resolving `aiGradingMode` upstream of this on the server and taking `max_manual_points` into account there. That would simplify this a bit.

File: apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/components/AiGradingUnavailableModal.tsx [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+      </Modal.Header>
+      <Modal.Body>
+        <p>
+          AI grading is only supported for questions with a manually graded portion. To enable
+          manual grading, set <code>manualPoints</code> to a non-zero value.
+        </p>
+        <p className="mb-0">
+          See the{' '}
+          <a
+            href="https://prairielearn.readthedocs.io/en/latest/manualGrading/#configuring-a-question-for-manual-grading"
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/components/AiGradingUnavailableModal.tsx]: Nit, slight preference to just link to the page instead of a specific header:

```suggestion
            href="https://prairielearn.readthedocs.io/en/latest/manualGrading/"
```

File: apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx [hunk 5]
```diff
@@ -118,21 +123,26 @@ function AssessmentQuestionManualGradingInner({
...
+            >
               <input
                 className="form-check-input"
                 type="checkbox"
                 role="switch"
                 id="switchCheckDefault"
-                checked={aiGradingMode}
-                disabled={setAiGradingModeMutation.isPending || !hasCourseInstancePermissionEdit}
-                onChange={() =>
+                checked={aiGradingMode && isAiGradingAvailable}
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx]: Nit, would also be simplified if `aiGradingMode` already took into account `max_manual_points`.

File: apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx [hunk 6]
```diff
@@ -118,21 +123,26 @@ function AssessmentQuestionManualGradingInner({
         </nav>
         {aiGradingEnabled && (
           <div className="card px-3 py-2 mb-0">
-            <div className="form-check form-switch mb-0">
+            <div
+              className={`form-check form-switch mb-0 ${isAiGradingAvailable ? 'opacity-100' : 'opacity-50'}`}
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx]: I worry that the contrast with `opacity-50` is too low. Maybe `opacity-75` would be a bit better?

File: apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx (hunk 5 above)
Comment (miguelaenlle) [reply apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx]: This has been resolved: https://github.com/PrairieLearn/PrairieLearn/pull/13933/changes/82f34b5c51b6383479ae6eb1e3303aceb3e86e9f..731399e90c3b6af9da0057b74d1f9a165ffac058#diff-49078079d31215f843b1ab7a2693eab1741c66b247499c3a9b8e124693297ade

File: apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/components/AssessmentQuestionTable.tsx (hunk 3 above)
Comment (miguelaenlle) [reply apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/components/AssessmentQuestionTable.tsx]: I made this change: https://github.com/PrairieLearn/PrairieLearn/pull/13933/changes/82f34b5c51b6383479ae6eb1e3303aceb3e86e9f..731399e90c3b6af9da0057b74d1f9a165ffac058#diff-49078079d31215f843b1ab7a2693eab1741c66b247499c3a9b8e124693297ade

File: apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx (hunk 6 above)
Comment (miguelaenlle) [reply apps/prairielearn/src/pages/instructorAssessmentManualGrading/assessmentQuestion/AssessmentQuestionManualGrading.html.tsx]: I increased the opacity to 75: https://github.com/PrairieLearn/PrairieLearn/pull/13933/changes/82f34b5c51b6383479ae6eb1e3303aceb3e86e9f..731399e90c3b6af9da0057b74d1f9a165ffac058#diff-49078079d31215f843b1ab7a2693eab1741c66b247499c3a9b8e124693297ade
