### PR TITLE
Restore access to assessments column in questions page

### LINKED ISSUE #4682: Weird Incorrect Behavior From New Search Box
Peek 2021-08-20 11-27

the question `Big-O-blocks` will show up if I search `blocks` but not if I search `big`

the question `addHTMLtable` shows up if I search `add` but not if I search `addH`

### PR DESCRIPTION
**Pull request by jonatanschroeder**
#3020 changed where authorized course_instances were found, but questions page was not updated to account for this new location. This PR restore access to the assessments columns in the questions page.

Also fixes #4682.

### CODE REVIEW

File: pages/instructorQuestions/instructorQuestions.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ router.get('/', function(req, res, next) {
             };
             sqldb.query(sql.questions, params, function(err, result) {
                 if (ERR(err, callback)) return;
-                const ci_ids = _.map(res.locals.course_instances, ci => ci.id);
+                const ci_ids = _.map(res.locals.authz_data.course_instances, ci => ci.id);
```
Comment (mwest1066) [inline pages/instructorQuestions/instructorQuestions.js:37]: Do we also want `|| []` here?

Comment (jonatanschroeder) [reply pages/instructorQuestions/instructorQuestions.js:37]: `_.map` accepts nullish as an empty array.

Comment (mwest1066) [reply pages/instructorQuestions/instructorQuestions.js:37]: cool

**Review by mwest1066 — APPROVED** [review]
