### PR TITLE
Fix news item lock contention

### LINKED ISSUE #9428: News item lock contention during server start
News item updates on server start currently cause lock contention. There are at least three problems:
1. We use a [`waitLock` for news item initialization](https://github.com/PrairieLearn/PrairieLearn/blob/78bca9745ff9e17b46765c927ccb98f4aacf7736/apps/prairielearn/src/news_items/index.js#L55) so all servers block, waiting for the first one that got the lock. Maybe we could switch to a `tryLock` so only one server will actually do the news item initialization.
2. We [synchronously wait for news item initialization](https://github.com/PrairieLearn/PrairieLearn/blob/78bca9745ff9e17b46765c927ccb98f4aacf7736/apps/prairielearn/src/server.js#L2369) during server start. I think we could just do this in the background?
3. The `sync_news_items` sproc is calling `users_are_instructors_in_any_course` for every user! 😱

I think that fixing (1) and (2) would solve our immediate problems and should be fairly easy.

### PR DESCRIPTION
**Pull request by nwalters512**
Closes #9428.

### CODE REVIEW

File: apps/prairielearn/src/news_items/index.js [hunk 1]
```diff
@@ -1,65 +1,96 @@
...
+      throw new Error(`News item index ${index} is used in multiple news items: ${directories}`);
+    }
+  });
 
   return _.sortBy(news_items, 'directory');
 }
 
-module.exports.initAsync = async function (notify_with_new_server) {
-  const lockName = 'news_items';
-  const lock = await namedLocks.waitLockAsync(lockName, {});
```
Comment (nwalters512) [inline apps/prairielearn/src/news_items/index.js:55]: While implementing this, I noticed something that's a little suspect: `waitLockAsync` does not appear to actually wait for the lock. The only time we don't use `SKIP LOCKED` is when a timeout is set, but in this case, the timeout is zero.

https://github.com/PrairieLearn/PrairieLearn/blob/8c1b71e9c7e187bafeefa4186e14f659f738a5e3/packages/named-locks/src/index.ts#L236-L238

This feels wrong to me, and also doesn't match how we've documented this functionality:

https://github.com/PrairieLearn/PrairieLearn/blob/8c1b71e9c7e187bafeefa4186e14f659f738a5e3/packages/named-locks/src/index.ts#L20-L21

I think we need to make one of two choices here (there may also be other options I haven't thought of):

- Decide that we like the current behavior and update the documentation to reflect that. This may be a reasonable choice; maybe we don't ever want locks to wait forever?
- Change the semantics of `timeout` as follows:
  - `timeout > 0`: don't use `SKIP LOCKED`, wait for `timeout` to acquire the lock
  - `timeout == 0`: use `SKIP LOCKED`, no waiting
  - `timeout == -1`: don't use `SKIP LOCKED`, disable the lock timeout entirely
 
On top of that, to bikeshed: all of this got me thinking that we might not even want `tryWithLock` to exist anymore, since it's just a very narrow wrapper around `doWithLock` that just sets `onNotAcquired` to return `null` if the lock couldn't be acquired, and in all but one usage of `tryWithLock` we already set `onNotAcquired` to something else.

Comment (mwest1066) [reply apps/prairielearn/src/news_items/index.js:55]: I tend to think that we never want to wait forever to acquire a lock and instead we should always handle failure in some way in application code (even if just by throwing an uncaught exception and crashing). That is, I think the code is working as we want and it's just the comment describing `timeout` that needs to be adjusted.

Regarding the bike-shedding, I agree that we don't want `tryWithLock` (it's confusingly similar to `doWithLock`).

I actually think we should bike-shed even harder and eliminate `tryLock`/`tryLockAsync` and `waitLock`/`waitLockAsync`. These made sense before we had `doWithLock`, but at this point I think we should always call `doWithLock`. If we really need extra control then we should call `getLock` directly, and in any case `tryLock`/`waitLock` are very thin wrappers around `getLock`. If we do eliminate `tryLock`/`waitLock` then we should ensure that `doWithLock` still defaults to `timeout: 0`, of course.

**Review by mwest1066 — APPROVED** [review]

File: apps/prairielearn/src/news_items/index.js (hunk 1 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/news_items/index.js:55]: > Regarding the bike-shedding, I agree that we don't want `tryWithLock` (it's confusingly similar to `doWithLock`).

This was actually a point of confusion for me in the recent past, as `tryWithLock` (`doWithLock` with a default of do nothing on not acquired) has nothing to do with `tryLock` (`getLock` with a timeout of 0), and there is no relationship between them.

I agree with eliminating tryLock/waitLock. I just did a quick check, and `tryLock` is only used (outside of the named-locks package itself) in the cron process, and `waitLock` is only used in news items, so eliminating should be very straightforward. `tryWithLock` is used in a few places but should also be easy enough to replace.

Comment (nwalters512) [reply apps/prairielearn/src/news_items/index.js:55]: I opened #9479 to do this. It'll have to wait until after this PR, which removed the final usage of `waitLockAsync`.
