### PR TITLE
Handle request for new variant when assessment is not available

### LINKED ISSUE #1718: Fix “assessment instance is not open” error message
If we try to view a never-before-viewed question on a closed assessment (normally an exam), we get the error `assessment instance is not open` when we try and create a new variant. This is because we do lazy variant creation (on first view).

This is a problem in several situations:

* Student never views a question during an exam, but they click on the question during a review session.
* Student never views a question during an exam, and an instructor is trying to view their exam.
* An instructor is testing an exam, and comes back to it after some time when it has automatically closed. Normally instructor permissions would override everything, but the open-instance check catches them.

In all cases there are workarounds, but this error is scary and makes it look like the question is broken. We should either make the error message clearer, or allow variant creation on closed assessments (at least in the case where there is no variant at the moment).

### LINKED ISSUE #9030: New variants can be created when assessment is not active
Steps to reproduce:

- Switch to "Student view" (_not_ "Student view without access restrictions").
- Start HW1 in the test course. Do not open any questions.
- Edit the assessment access rule to be just `"active": false`; sync the course.
- Click one of the questions.
- Observe that a new variant is created even though the assessment isn't active.

This can be reproduced for exams as well.

This behavior is not necessarily problematic, as students won't be able to do anything that gives them points (that is, they can't submit to it). However, this behavior would be confusing to anyone who is reviewing the assessment instance log, of if creating a variant generates an issue when the assessment isn't active. Instructors might rightfully consider that `"active": false` implies that an assessment is immutable.

It is possible that this behavior is intentional, but I suspect it's just sort of an accident of how things work.

If this is _not_ intentional behavior, I'd like to propose some changes that will fix it:

- If an assessment is not active and a user opens a question for which there is no existing variant, display a page stating that new variants can't be created.
- If a Homework assessment is not active and user opens a question for which there _is_ at least one existing variant, show the most recent variant instead of generating a new one.
  - This behavior is necessary because visiting the `pl/course_instance/##/instance_question/##` route will create a new variant if there are not any open variants. In _general_ this is acceptible behavior, but I'm proposing that it's undesirable when an assessment is not active.

### PR DESCRIPTION
**Pull request by echau01**
Resolves #9030, resolves #1718.

If an assessment is not open or not active, and a student clicks a question in the assessment:

- If the student has opened the question before (thus creating a variant), show them the most recent variant that is not broken.
- If the student has never opened the question before, show them this page:

no-variant-exists

In both cases, we avoid generating a new variant.

Note: in my implementation, we do not show a broken variant. Not sure if this is right, but we can discuss it.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
> Resolves #9030 and #1718.

Nice to see you again, @echau01! In order to link the PR to the issue you will need to repeat the keyword: Resolves #9030, resolves #1718. Can you update the description?

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js [hunk 1]
```diff
@@ -280,10 +283,34 @@ router.get(
...
   asyncHandler(async (req, res) => {
-    const variant_id =
+    let variant_id =
       res.locals.assessment.type === 'Exam' || typeof req.query.variant_id !== 'string'
         ? null
         : req.query.variant_id;
+
+    const isAssessmentAvailable =
+      _.get(res.locals, 'assessment_instance.open', true) &&
+      _.get(res.locals, 'authz_result.active', true);
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:293]: My understanding is that these variables are always set at this point, so this can be simpler:

```suggestion
    const isAssessmentAvailable =
      res.locals,assessment_instance.open &&
      res.locals.authz_result.active;
```

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js [hunk 2]
```diff
@@ -280,10 +283,34 @@ router.get(
...
+
+    if (variant_id === null && !isAssessmentAvailable) {
+      // We can't generate a new variant in this case, so we
+      // fetch and display the most recent non-broken variant.
+      // If no such variant exists, we tell the user that a new variant
+      // cannot be generated.
+      const result = await sqldb.queryZeroOrOneRowAsync(sql.select_last_variant_id, {
+        instance_question_id: res.locals.instance_question.id,
+      });
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:302]: We have been moving towards newer Zod-validated queries in new code.
```suggestion
      const last_variant_id = await sqldb.queryOptionalRow(
        sql.select_last_variant_id,
        { instance_question_id: res.locals.instance_question.id },
        IdSchema,
      });
```
You will need to import `IdSchema` from lib/db-types.ts, and change the code after this point to use `last_variant_id` instead of `result`. `last_variant_id` will be null if it does not exist.

**Review by jonatanschroeder — COMMENTED** [review]
Not a full review, only a first pass.

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js (hunk 2 above)
Comment (echau01) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js]: Done

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js (hunk 1 above)
Comment (echau01) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js]: Can confirm, they would be set in selectAndAuthzInstanceQuestion.

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ejs [hunk 3]
```diff
@@ -37,6 +39,17 @@
...
+      <div class="card mb-4">
+        <div class="card-header bg-primary text-white">
+          <%- include('../partials/questionTitle', {question_context: assessment.type === 'Exam' ? 'student_exam' : 'student_homework'}); %>
+        </div>
+        <div class="card-body">
+          A new variant cannot be created because the assessment is closed.
+        </div>
+      </div>
+      <%- include('../partials/questionNavSideButtonGroup') %>
+      <% } else { %>
```
[the remark this answers is not in the document]
Comment (echau01) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ejs]: I agree. I've changed the page to this:

no-variant-exists

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ejs [hunk 4]
```diff
@@ -37,6 +39,17 @@
 
     <%- include('../partials/navbar', {navPage: ''}); %>
     <main id="content" class="container">
+      <% if (typeof new_variant_forbidden !== 'undefined') { %>
+      <div class="card mb-4">
+        <div class="card-header bg-primary text-white">
+          <%- include('../partials/questionTitle', {question_context: assessment.type === 'Exam' ? 'student_exam' : 'student_homework'}); %>
+        </div>
+        <div class="card-body">
+          A new variant cannot be created because the assessment is closed.
```
[the remark this answers is not in the document]
Comment (echau01) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ejs]: I've changed the wording to what you suggested.

File: apps/prairielearn/src/tests/activeAccessRestriction.test.ts [hunk 5]
```diff
@@ -152,11 +155,25 @@ describe('Exam and homework assessment with active access restriction', function
...
+      headers,
+    });
+    assert.isTrue(questionResponse.ok);
+  });
+
+  step('count number of variants generated', async () => {
+    const countVariantsResult = await sqldb.queryOneRowAsync(sql.count_variants, {
+      assessment_instance_id: helperClient.parseAssessmentInstanceId(context.examInstanceUrl),
+    });
+    context.numberOfVariants = countVariantsResult.rows[0].count;
```
Comment (nwalters512) [inline apps/prairielearn/src/tests/activeAccessRestriction.test.ts:175]: Nit, I'd prefer to use Zod-validated queries both here and elsewhere in the file (Prettier formatting of the below will be necessary).

```suggestion
    context.numberOfVariants = await sqldb.queryRow(sql.count_variants, {
      assessment_instance_id: helperClient.parseAssessmentInstanceId(context.examInstanceUrl),
    }, z.number());
```

File: apps/prairielearn/src/tests/activeAccessRestriction.test.ts [hunk 6]
```diff
@@ -186,6 +203,27 @@ describe('Exam and homework assessment with active access restriction', function
...
+    assert.lengthOf(response.$('button.question-grade'), 0);
+  });
+
+  step('access question without existing variant when exam is closed', async () => {
+    const response = await helperClient.fetchCheerio(context.examQuestionWithoutVariantUrl, {
+      headers,
+    });
+    assert.equal(response.status, 403);
+
+    const result = response.$('div.card-body:contains(' + VARIANT_FORBIDDEN_STRING + ')');
```
Comment (nwalters512) [inline apps/prairielearn/src/tests/activeAccessRestriction.test.ts:223]: Nit, we generally prefer to use templates literals; you can make this change elsewhere as well:

```suggestion
    const result = response.$(`div.card-body:contains(${VARIANT_FORBIDDEN_STRING })`);
```

File: apps/prairielearn/src/tests/activeAccessRestriction.test.ts [hunk 7]
```diff
@@ -186,6 +203,27 @@ describe('Exam and homework assessment with active access restriction', function
...
+    assert.lengthOf(result, 1);
```
Comment (nwalters512) [inline apps/prairielearn/src/tests/activeAccessRestriction.test.ts:224]: Nit, we don't gain much be assigning the Cheerio result to a variable:

```suggestion
    assert.lengthOf(response.$('div.card-body:contains(' + VARIANT_FORBIDDEN_STRING + ')'), 1);
```

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js [hunk 8]
```diff
@@ -280,10 +284,35 @@ router.get(
...
+      const last_variant_id = await sqldb.queryOptionalRow(
+        sql.select_last_variant_id,
+        { instance_question_id: res.locals.instance_question.id },
+        IdSchema,
+      );
+      if (last_variant_id == null) {
+        res.locals.no_variant_exists = true;
+        res.status(403).render(__filename.replace(/\.js$/, '.ejs'), res.locals);
+        return;
+      }
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:309]: This will not log a page view. I think this is OK; just making sure that we've thought about this and decided that this is the desired behavior. cc @jonatanschroeder

**Review by nwalters512 — APPROVED** [review]
A few stylistic nits, nothing blocking though. @echau01 let me know when you're ready for this to be merged.

File: apps/prairielearn/src/tests/activeAccessRestriction.test.ts (hunk 5 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/tests/activeAccessRestriction.test.ts:175]: This query actually performs a `COUNT`, which IIRC results in a bigint, so `z.number()` will not work. This will either need to be `z.coerce.number()` or the query will need to be updated to `COUNT(v.*)::INT`.

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js (hunk 8 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:309]: That's a good point. I don't see a problem either way, though current behaviour (if I'm not mistaken) also does not log a page view in this context.

File: apps/prairielearn/src/tests/activeAccessRestriction.test.ts (hunk 5 above)
Comment (nwalters512) [reply apps/prairielearn/src/tests/activeAccessRestriction.test.ts:175]: Good point, `::integer` is the way we usually handle that.

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js (hunk 8 above)
Comment (nwalters512) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:309]: Correct, currently we don't, though I think that's strictly because the current behavior is to error out hard (that is, I think this isn't ever behavior we specifically thought about or designed).

Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:309]: Indeed, I meant that logging it would add a new log entry which didn't exist before, so it's not something an instructor would expect to find before this change, and we don't have reports of this being needed before.

File: apps/prairielearn/src/tests/activeAccessRestriction.test.ts (hunk 5 above)
Comment (echau01) [reply apps/prairielearn/src/tests/activeAccessRestriction.test.ts]: Done

File: apps/prairielearn/src/tests/activeAccessRestriction.test.ts (hunk 7 above)
Comment (echau01) [reply apps/prairielearn/src/tests/activeAccessRestriction.test.ts]: Done

**Comment by nwalters512** [comment]
@echau01 there's a failing test that you'll need to fix before this can be merged.

**Comment by echau01** [comment]
@nwalters512 I think everything's ready for merging now.

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js (hunk 8 above)
Comment (echau01) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:309]: We _could_ log the page view here, but I don't think it is necessary. It's not something that an instructor would need to pay attention to.

Comment (nwalters512) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.js:309]: I think we're all in agreement, no need to log here!

**Review by nwalters512 — APPROVED** [review]
