### PR TITLE
Fix course syncing bugs

### LINKED ISSUE #11325: Cannot sync course with only implicit, non-default assessment sets
Consider a course with an empty `assessmentSets` array in `infoCourse.json`, a single course instance, and a single assessment using an implicit, non-default assessment set like `X`. We'll fail to sync with an error like the following:

```
error: null value in column "number" of relation "assessment_sets" violates not-null constraint
    at /Users/nathan/git/PrairieLearn/node_modules/pg/lib/client.js:535:17
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async PostgresPool.queryWithClientAsync (/Users/nathan/git/PrairieLearn/packages/postgres/src/pool.ts:319:22)
    at async PostgresPool.queryAsync (/Users/nathan/git/PrairieLearn/packages/postgres/src/pool.ts:534:14)
    at async PostgresPool.callAsync (/Users/nathan/git/PrairieLearn/packages/postgres/src/pool.ts:604:20)
    at async PostgresPool.callOneRowAsync (/Users/nathan/git/PrairieLearn/packages/postgres/src/pool.ts:621:20)
    at async Module.sync (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/fromDisk/assessmentSets.ts:46:3)
    at async timed (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/syncFromDisk.ts:94:20)
    at async <anonymous> (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/syncFromDisk.ts:136:5)
    at async timed (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/syncFromDisk.ts:94:20)
    at async syncDiskToSqlWithLock (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/syncFromDisk.ts:122:3)
    at async <anonymous> (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/syncFromDisk.ts:207:14)
    at async Module.doWithLock (/Users/nathan/git/PrairieLearn/packages/named-locks/src/index.ts:131:12)
    at async syncDiskToSql (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/syncFromDisk.ts:196:18)
    at async Module.syncOrCreateDiskToSql (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/sync/syncFromDisk.ts:220:10)
    at async <anonymous> (/Users/nathan/git/PrairieLearn/apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts:52:26)

{
  "sqlError": {
    "length": 1526,
    "name": "error",
    "severity": "ERROR",
    "code": "23502",
    "detail": "Failing row contains (7296, X, X, X (Auto-generated from use in an assessment; add this assessment..., gray1, null, 6, t).",
    "where": "SQL statement \"WITH new_assessment_sets AS (\n        INSERT INTO assessment_sets (\n            course_id,\n            name,\n            abbreviation,\n            heading,\n            color,\n            number,\n            implicit\n        ) SELECT\n            syncing_course_id,\n            name,\n            name,\n            concat(name, ' (Auto-generated from use in an assessment; add this assessment set to your infoCourse.json file to customize)'),\n            'gray1',\n            (array_length(used_assessment_set_names, 1) + (row_number() OVER ())),\n            TRUE\n        FROM\n            (SELECT UNNEST(assessment_set_names) EXCEPT SELECT UNNEST(used_assessment_set_names))\n            AS t(name)\n        ORDER BY name\n        ON CONFLICT (course_id, name) DO UPDATE\n        SET\n            abbreviation = EXCLUDED.abbreviation,\n            heading = EXCLUDED.heading,\n            color = EXCLUDED.color,\n            number = EXCLUDED.number,\n            implicit = EXCLUDED.implicit\n        RETURNING name\n    )\n    SELECT array_agg(name)                                    FROM new_assessment_sets\"\nPL/pgSQL function sync_assessment_sets(boolean,boolean,jsonb[],text[],bigint) line 55 at SQL statement",
    "schema": "public",
    "table": "assessment_sets",
    "column": "number",
    "file": "execMain.c",
    "line": "1993",
    "routine": "ExecConstraints",
    "message": "null value in column \"number\" of relation \"assessment_sets\" violates not-null constraint"
  },
  "sql": "SELECT * FROM \"sync_assessment_sets\"($1,$2,$3,$4,$5);",
  "sqlParams": [
    true,
    true,
    [],
    [
      "X"
    ],
    "6"
  ]
}
```

This is caused by `used_assessment_set_names` being `NULL` on this line:

https://github.com/PrairieLearn/PrairieLearn/blob/1931f8cab3298daf52f4bfa36295caea5afee95f/apps/prairielearn/src/sprocs/sync_assessment_sets.sql#L76

`array_length(NULL, 1)` is `NULL`, so we end up with an expression like `NULL + 1` for `number`, which is of course `NULL`.

This, in turn, is caused by this line, where `array_agg(name)` produces `NULL` if there are no input rows:

https://github.com/PrairieLearn/PrairieLearn/blob/1931f8cab3298daf52f4bfa36295caea5afee95f/apps/prairielearn/src/sprocs/sync_assessment_sets.sql#L49

The easy fix is to make two changes:

- Change `array_length(...)` to `COALESCE(array_length(...), 0)`
- Change `array_agg(name)` to `COALESCE(array_agg(name), '{}'::text[])` (this isn't required for fixing the bug reported here, but it does fix another bug: if a course is using zero assessment sets, we won't delete any of the ones in the DB during sync. This is because `... != ANY(NULL)` works out to be `NULL`).

The probably better fix is to rewrite most of this syncing code in TypeScript, where we don't have to deal with all this `NULL` stuff.

Note that syncing for tags, topics, and modules is probably impacted by the same bug. We should write failing test cases for all these, and the implement an appropriate fix.

### PR DESCRIPTION
**Pull request by nwalters512**
Closes #11325. This PR introduces a number of failing test cases and revamps the syncing code to get them passing. Syncing of tags, topics, and assessment modules is now handles mostly by TypeScript, with just a bit of boilerplate SQL to handle insertions/updates/deletions.

### CODE REVIEW

File: apps/prairielearn/src/sync/fromDisk/tags.ts [hunk 1]
```diff
@@ -1,11 +1,31 @@
...
+import { TagSchema, type Tag } from '../../lib/db-types.js';
 import { type CourseData } from '../course-db.js';
 import * as infofile from '../infofile.js';
 
+import { determineOperationsForEntities } from './entity-list.js';
+
+const sql = loadSqlEquiv(import.meta.url);
+
+interface DesiredTag {
+  // TODO: this must be non-null in the database schema.
```
Comment (nwalters512) [inline apps/prairielearn/src/sync/fromDisk/tags.ts:21]: See #11338.

File: apps/prairielearn/src/sync/fromDisk/topics.ts [hunk 2]
```diff
@@ -1,8 +1,22 @@
...
+import { TopicSchema } from '../../lib/db-types.js';
 import { type CourseData } from '../course-db.js';
 import * as infofile from '../infofile.js';
 
+import { determineOperationsForEntities } from './entity-list.js';
+
+const sql = loadSqlEquiv(import.meta.url);
+
+interface DesiredTopic {
+  // TODO: this must be non-null in the database schema.
```
Comment (nwalters512) [inline apps/prairielearn/src/sync/fromDisk/topics.ts:12]: See #11338.

File: apps/prairielearn/src/sync/fromDisk/assessmentSets.ts [hunk 3]
```diff
@@ -39,13 +33,73 @@
...
+      color: 'gray1',
+      implicit: true,
+    }),
     isInfoCourseValid,
     deleteUnused,
-    courseAssessmentSets,
-    assessmentSetNames,
-    courseId,
-  ]);
+  });
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/assessmentSets.ts]: This is intentional, the `determineOperationsForEntities(...)` function manages these properties for us.

File: apps/prairielearn/src/sync/fromDisk/assessmentSets.ts [hunk 4]
```diff
@@ -1,8 +1,20 @@
...
+import { determineOperationsForEntities } from './entity-list.js';
+
+const sql = loadSqlEquiv(import.meta.url);
+
+interface DesiredAssessmentSet {
+  name: string;
+  abbreviation: string;
+  heading: string;
+  color: string;
+}
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/assessmentSets.ts]: This is intentional, the determineOperationsForEntities(...) function manages these properties for us.

File: apps/prairielearn/src/sync/fromDisk/tags.sql [hunk 5]
```diff
@@ -0,0 +1,63 @@
...
+  $course_id,
+  (t ->> 0)::text,
+  (t ->> 1)::text,
+  (t ->> 2)::text,
+  (t ->> 3)::integer,
+  (t ->> 4)::boolean
+FROM
+  UNNEST($tags::jsonb[]) AS t
+RETURNING
+  *;
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/tags.sql:31]: `color` and `number` intentionally don't have any specific ranges. `color` values are handled and verifies at the application level, and numbers can be any valid integer (and are also handled by the application and are not user-controlled).

File: apps/prairielearn/src/sync/fromDisk/tags.ts [hunk 6]
```diff
@@ -34,22 +47,79 @@ export async function sync(
...
+    tagIdsByName.set(tag.name, tag);
+  }
 
   const questionTagsParam: string[] = [];
   Object.entries(courseData.questions).forEach(([qid, question]) => {
     if (infofile.hasErrors(question)) return;
     const dedupedQuestionTagNames = new Set<string>();
     (question.data?.tags ?? []).forEach((t) => dedupedQuestionTagNames.add(t));
-    const questionTagIds = [...dedupedQuestionTagNames].map((t) => tagIdsByName.get(t));
+    const questionTagIds = [...dedupedQuestionTagNames].map((t) => tagIdsByName.get(t)?.id);
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/tags.ts]: Good points! I resolved this in 52fb079.

File: apps/prairielearn/src/tests/sync/util.ts [hunk 7]
```diff
@@ -15,16 +15,16 @@ interface CourseOptions {
   devModeFeatures: Record<string, boolean> | string[];
 }
 
-interface Tag {
+export interface Tag {
```
Comment (nwalters512) [inline apps/prairielearn/src/tests/sync/util.ts:18]: I'd consider this to be temporary, we'll be able to use a single shared type in #11024.

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts [hunk 8]
```diff
@@ -0,0 +1,113 @@
...
+
+  // If `infoCourse.json` is invalid, keep all existing assessment sets in place.
+  // Otherwise, sync whatever is in the JSON file.
+  if (isInfoCourseValid) {
+    for (const entity of courseEntities) {
+      desiredEntities.set(entity.name, {
+        ...entity,
+        implicit: false,
+        number: desiredEntities.size + 1,
+      });
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/entity-list.ts:49]: If courses have even a million tags/topics/etc., we're already in trouble, we'll never get close to this. Let's ignore for now. We can add limits on the number of tags/topics/etc. per course in the future.

**Review by mylesw27 — APPROVED** [review]
Tested syncing asessment sets, modules, topics and tags locally. Everything worked as expected.

**Review by miguelaenlle — APPROVED** [review]
I also tested syncing assessment sets, modules, tags, and topics on a test course, and everything works as expected! Also, all of the code looks good to me 👍.

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts [hunk 9]
```diff
@@ -0,0 +1,113 @@
...
+  implicit: boolean;
+};
+
+type ExtraEntity<Entity> = Entity & {
+  implicit: boolean;
+};
+
+type DesiredEntity<Entity> = Entity & { number: number; implicit: boolean };
+
+export function determineOperationsForEntities<Entity extends NamedEntity>({
```
Comment (mwest1066) [inline apps/prairielearn/src/sync/fromDisk/entity-list.ts:17]: Maybe add some comments for this function? I think I understood everything by looking at a caller, but I struggled when reading this function in isolation.

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts [hunk 10]
```diff
@@ -0,0 +1,113 @@
...
+
+  // Based on the set of desired assessment entities, determine which ones must be
+  // added, updated, or deleted.
+  const entitiesToAdd = new Map<string, DesiredEntity<Entity>>();
+  const entitiesToUpdate = new Map<string, DesiredEntity<Entity>>();
+  const entitiesToDelete = new Set<string>();
+
+  for (const [name, entity] of desiredEntities) {
+    if (existingEntityNames.has(name)) {
+      // TODO: check for equality, skip update if not needed.
```
Comment (mwest1066) [inline apps/prairielearn/src/sync/fromDisk/entity-list.ts:93]: This would be very nice! But I do agree that the new code is no worse than the old (ON CONFLICT DO UPDATE) code.

**Review by mwest1066 — APPROVED** [review]
Much nicer than the old code!

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts [hunk 11]
```diff
@@ -0,0 +1,113 @@
...
+  deleteUnused: boolean;
+}): {
+  entitiesToCreate: DesiredEntity<Entity>[];
+  entitiesToUpdate: DesiredEntity<Entity>[];
+  entitiesToDelete: string[];
+} {
+  const existingEntityNames = new Set(existingEntities.map((entity) => entity.name));
+  const desiredEntities = new Map<string, DesiredEntity<Entity>>();
+
+  // If `infoCourse.json` is invalid, keep all existing assessment sets in place.
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/entity-list.ts:69]: Resolved in aaec0d2.

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts (hunk 9 above)
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/entity-list.ts:29]: Done in 55c1b83, how do those look?

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts (hunk 10 above)
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/entity-list.ts]: I did end up implementing this in 55c1b83 (with tests!).

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts (hunk 11 above)
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/entity-list.ts]: Oops, actually resolved in ccac31c.

File: apps/prairielearn/src/sync/fromDisk/entity-list.ts (hunk 10 above)
Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/entity-list.ts]: Ugh, seems like things are still broken, even with tests. Investigating.

Comment (nwalters512) [reply apps/prairielearn/src/sync/fromDisk/entity-list.ts]: Turns out the test itself was broken! Fixed in 1e8ee65.
