### PR TITLE
Feat: add indent grid lines to pl-order-blocks and subtle bug fixes

### LINKED ISSUE #4921: Add vertical lines to pl-order-blocks to show indentation points
(e.g., https://github.com/ace-lab/berk-parsons/blob/79cd59dca70e0ac8156c9386bc8c0b1fcbd94fc0/app/static/vendors/parsons/parsons.js#L1470-L1477, https://github.com/RunestoneInteractive/RunestoneComponents/blob/05d5a5d0a03369fb7726474d68f07b7dbd2d7c26/runestone/parsons/css/parsons.css#L100-L109)

originall suggested by @nathanielweinman over at https://github.com/PrairieLearn/PrairieLearn/issues/3476

### PR DESCRIPTION
**Pull request by Frozemint**
This PR implements the indent grid line feature request in #4921 for `pl-order-blocks`, and also includes a small subtle HTML bug fix for the grid line feature implementation to work properly as detailed in #7971. This PR will close #4921 and close #7971.

image

Visually, the grid line look like the screenshot above. The grid lines are only visible while dragging a block. The implementation is in javascript, as the number of grid lines depends on the variable `maxIndent`.

### CODE REVIEW

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js [hunk 1]
```diff
@@ -131,6 +131,27 @@ window.PLOrderBlocks = function (uuid, options) {
       placePairingIndicators();
       setAnswer();
     },
+    start: function () {
+      if (enableIndentation) {
+        $(dropzoneElementId)[0].style.background =
+          'linear-gradient(#000, #000) no-repeat border-box, '.repeat(+maxIndent + 1).slice(0, -2);
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:137]: > 'linear-gradient(#000, #000) no-repeat border-box

This seems really complicated to just draw a line, is there no simpler way? I'm not super familiar with this part of CSS but my guess is that there is a simpler way. I could be wrong but it would be nice to know at least.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js [hunk 2]
```diff
@@ -131,6 +131,27 @@ window.PLOrderBlocks = function (uuid, options) {
...
+        $(dropzoneElementId)[0].style.backgroundSize = '1px 100%, '
+          .repeat(+maxIndent + 1)
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:139]: you don't need the + on `+maxIndent`

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js [hunk 3]
```diff
@@ -131,6 +131,27 @@ window.PLOrderBlocks = function (uuid, options) {
       placePairingIndicators();
       setAnswer();
     },
+    start: function () {
+      if (enableIndentation) {
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:135]: I would prefer you take all this code and put it in its own function with a name, so that people reading the codebase know what the code does without having to read it all. Call it something helpeful like `function drawIndentLocationLines` or something.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js (hunk 1 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:137]: This was taken straight from the original issue #4921. I could check if there are simpler ways of drawing a line. If there is anyone else who knows a more elegant way, please do chime in 👀

Comment (SethPoulsen) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:137]: you should be able to just set the background to be a specific color instead of using the `linear-gradient` function. That seems very unneccessary. I'm also not sure what `no-repeat` and `border-box` do or if they are necessary.

I would also prefer it to have some opacity so it looks more gray instead of just the strong black color.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js [hunk 4]
```diff
@@ -131,6 +131,27 @@ window.PLOrderBlocks = function (uuid, options) {
...
+          let pos_string = '';
+          while (counter <= maxIndent) {
+            pos_string += `${
+              +$(dropzoneElementId).css('padding-left').slice(0, -2) + TABWIDTH * counter
+            }px 0, `;
+            counter += 1;
+          }
+          console.log(pos_string);
+          return pos_string.slice(0, -2);
+        })();
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:152]: We can definitely get this code much shorter and easier to read. Maybe something like 
```
$(dropzoneElementId)[0].style.backgroundPosition = Array.from({length: maxIndent}, (value, index => {
  `$(dropzoneElementId).css('padding-left').slice(0, -2) + TABWIDTH * counter}px 0`
}).join(' , ')
```
(I haven't tested this, it might need to be tweaked a little).

**Review by SethPoulsen — COMMENTED** [review]
Looks good overall. I would slightly prefer creating the CSS in the python so that its already in the HTML when it gets to the client, but that's not that big a deal to me. 

I did leave some suggestions on improving the Javascript code.

I don't like that the lines disappear when you aren't interacting with the UI because its a little confusing, I think the lines should stay there always. I would also like them to be a bit lighter colored, you could try making them gray or just setting opacity somewhere in 0.3-0.5

**Comment by Frozemint** [comment]
Thanks for taking a look and reviewing the code, I will clean things up as suggested. Do others also want to chime in about the exact behaviour and appearance of the grid line feature? I didn't fully flush out (or thought of) the smaller details, like the exact appearance or the visibility behaviour of the lines, because I thought there is probably a discussion to be had about this with others.

**Comment by Frozemint** [comment]
Sorry about that, I was working on my laptop and didn't realise the git author config is outdated.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js (hunk 4 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js]: Your code works, just needed to use `maxIndent + 1` in the length to account for the default indent: for future reference in case someone digs this up 5 years from now, `maxIndent` specifies how many times a block can be indented to the right, and the fact that blocks can be indented by 0 times is implicit; this means using `maxIndent` only results in an off by 1 with the rightmost indent line missing.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js (hunk 3 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js]: Done, also added some comments to the grid line drawing code.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css [hunk 5]
```diff
@@ -23,6 +23,7 @@ li.pl-order-blocks-code {
   margin-bottom: 0px !important;
 }
 
+
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css:26]: I would prefer to not add this unneccessary extra white space

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css [hunk 6]
```diff
@@ -51,6 +52,11 @@ li.ui-state-highlight {
   margin-bottom: 0px;
 }
 
+div.pl-order-blocks-container {
+  display: flex;
+  flex-direction: column;
+}
+
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css:59]: This should go into the `div.pl-order-blocks-container` declaration below so that we don't have two seperate declarations for the same class.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js [hunk 7]
```diff
@@ -119,6 +119,22 @@ window.PLOrderBlocks = function (uuid, options) {
...
+    // set the appearance (thickness) of the grid lines
+    $(dropzoneElementId)[0].style.backgroundSize = '1px 100%, '.repeat(maxIndent + 1).slice(0, -2);
+    // translate the grid lines to the correct positions
+    $(dropzoneElementId)[0].style.backgroundPosition = Array.from(
+      { length: maxIndent + 1 },
+      (value, index) => {
+        return `${+$(dropzoneElementId).css('padding-left').slice(0, -2) + TABWIDTH * index}px 0`;
+      }
+    ).join(', ');
+  }
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:136]: Looks much improved from before!

Minor improvements I would suggest: 
- I still don't think its necessary to use `linear-gradient`, can't you just make the background be a solid color? It should be the same things as giving it a constant gradient like here, but will make shorter, simpler code
- I don't really like these kinds of comments that just say exactly what the next line does, I think they just get in the way. Its easier to just read the code
- Why not just pass `$(dropzoneElementId)[0]` as the parameter to the function? That will clean up the code a little more

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js [hunk 8]
```diff
@@ -131,6 +147,13 @@ window.PLOrderBlocks = function (uuid, options) {
       placePairingIndicators();
       setAnswer();
     },
+    start: function () {
+      // the start event is only called once when user starts dragging
+      // this is suitable for drawing the indent grid lines, which is static
+      if (enableIndentation) {
+        drawIndentLocationLines(dropzoneElementId);
+      }
+    },
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:156]: I really think this should be in the `create` function. The lines should be created only once at the begining, and then left there. 

I don't like having them appear and disappear for at least a few reasons:
- its is distracting for students to have the lines flashing on and off while working on the problem
- you may want to look at the lines even when you aren't in the middle of dragging a block

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js [hunk 9]
```diff
@@ -142,8 +165,9 @@ window.PLOrderBlocks = function (uuid, options) {
       // when the user stops interacting with the list
       let leftDiff = calculateIndent(ui, ui.item.parent());
       ui.item[0].style.marginLeft = leftDiff + 'px';
-      setAnswer();
+      $(dropzoneElementId)[0].style.background = null;
 
+      setAnswer();
       correctPairing(ui);
```
Comment (SethPoulsen) [inline apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:171]: after moving the creation of the lines to the `create` function, this change should be reverted.

**Review by SethPoulsen — CHANGES_REQUESTED** [review]
This code is looking much better, but I think there are still a few things we need to change. The main ones are:

- make the lines a lighter color so they don't look so harsh. Before I suggested either making them gray, or making them black with some opacity. I realized that making them gray will be better because it has a higher chance of looking OK if/when we implement dark mode in the future
- the lines should always be present, they should not appear and disappear

I made a few other minor comments as well. I will be happy to approve this ones the changes I have requested in this round are met.

**Comment by SethPoulsen** [comment]
Sorry it took so long for me to respond, I've had a crazy week.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css (hunk 5 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css:26]: Oops, I think this got in there by mistake when I was copying and cutting things while changing the CSS.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css (hunk 6 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.css:58]: Good catch, thank you.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js (hunk 8 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js:156]: To clarify, do you want the indent lines to appear when the page finishes loading, or when the student first hovers a block over the answer dropzone? Putting `drawIndentLocationLines` in `create` means the lines will be immediately visible after the page loads even before the student drags anything.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js (hunk 9 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js]: Code changed as suggested. You're right, having the lines be persistent makes more sense.

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js (hunk 7 above)
Comment (Frozemint) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js]: I removed the comments as suggested. For the `linear-gradient` issue, I had a quick look, and it looks like we are stuck with either `linear-gradient` or using SVGs to draw the line. Solid background colours are simpler, but after a quick look it looks like we'll have to add more divs acting as lines to use that approach. I can't seem to find a function that is simpler than `linear-gradient` either.

**Comment by Frozemint** [comment]
Thanks for having a look again. The major changes I made is making the lines persistent even after dragging has finished, and changing the line colour from pure black to `#4F4F4F`. I've put that shade of grey for now, as it is the first shade of grey that I could find that has sufficient contrast (7:1 contrast ratio) against the background colour `#eeeeee` for accessibility.

**Review by SethPoulsen — APPROVED** [review]

File: apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js (hunk 8 above)
Comment (SethPoulsen) [reply apps/prairielearn/elements/pl-order-blocks/pl-order-blocks.js]: yes that's right, they should always be visible before they even touch it. I went ahead and made the change myself so I could merge it. Thanks!
