### PR TITLE
Fix `group_info.sql` to not return NULL users

### LINKED ISSUE #9228: ZodError in `instructorAssessmentInstances.js`
https://prairielearn-inc.sentry.io/issues/4856604946/

```
  {
    "code": "invalid_type",
    "expected": "string",
    "received": "null",
    "path": [
      11,
      "uid_list",
      0
    ],
    "message": "Expected string, received null"
  }
```

Thrown at: https://github.com/PrairieLearn/PrairieLearn/blob/4158b0dc07463ad82c560b30529ec94ac705c607/apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.js#L56-L63

### PR DESCRIPTION
**Pull request by mwest1066**
**WARNING: Currently untested!**

Fixes #9228

The problem was that the `group_info` query used a simple LEFT JOIN and so it returns `uid_list = [NULL]` when there aren't any group users. This PR changes to a two-stage query so that it will return `uid_list = []` in this case.

This function is only used in two files:
1. `instructorAssessmentInstances.sql`, which triggered the bug in #9228: https://github.com/PrairieLearn/PrairieLearn/blob/4158b0dc07463ad82c560b30529ec94ac705c607/apps/prairielearn/src/pages/instructorAssessmentInstances/instructorAssessmentInstances.sql#L93
2. the API in two places: https://github.com/PrairieLearn/PrairieLearn/blob/4158b0dc07463ad82c560b30529ec94ac705c607/apps/prairielearn/src/api/v1/endpoints/queries.sql#L96 and https://github.com/PrairieLearn/PrairieLearn/blob/4158b0dc07463ad82c560b30529ec94ac705c607/apps/prairielearn/src/api/v1/endpoints/queries.sql#L356

None of the above calls rely on the old behavior.

### CODE REVIEW

File: apps/prairielearn/src/sprocs/group_info.sql [hunk 1]
```diff
@@ -11,22 +11,38 @@ CREATE FUNCTION
 AS $$
 BEGIN
     RETURN QUERY
+    WITH group_user_lists AS (
+        SELECT
+            g.id as id,
+            array_agg(u.uid) AS uid_list,
+            array_agg(u.name) AS user_name_list,
+            array_agg(users_get_displayed_role(u.user_id, a.course_instance_id)) as user_roles_list
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/sprocs/group_info.sql:19]: You're missing the JOIN on assessments here, needed for `a.course_instance_id`.

File: apps/prairielearn/src/sprocs/group_info.sql [hunk 2]
```diff
@@ -11,22 +11,38 @@ CREATE FUNCTION
...
-        LEFT JOIN users AS u ON (u.user_id = gu.user_id)
+        LEFT JOIN group_user_lists AS gul ON (gul.id = g.id)
     WHERE
-        gc.deleted_at IS NULL
+        gc.assessment_id = group_info.assessment_id
+        AND gc.deleted_at IS NULL
         AND g.deleted_at IS NULL
-        AND gc.assessment_id = group_info.assessment_id
     GROUP BY
         g.id;
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/sprocs/group_info.sql:47]: I don't think this `GROUP BY` is necessary anymore.

File: apps/prairielearn/src/sprocs/group_info.sql (hunk 1 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/sprocs/group_info.sql:19]: Fixed in 0c1d6b9dd9824d4022f15357364f9f70714ff939.

File: apps/prairielearn/src/sprocs/group_info.sql (hunk 2 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/sprocs/group_info.sql]: Removed in 0c1d6b9dd9824d4022f15357364f9f70714ff939.

**Review by jonatanschroeder — APPROVED** [review]
@mwest1066 this problem was messing up my tests in #9106, so I fixed the issues I mentioned myself. I tested this and it's working. @nwalters512 since this now has my changes as well do you want to double-check to make sure it's fine?
