### PR TITLE
Fix LTI 1.3 course instance linking

### LINKED ISSUE #13630: LTI 1.3 course instance linking broken
### Details

The part of the LTI 1.3 integration that lets instructors choose the course and course instance to link to the LMS isn't loading. The HTMX page that populates the dropdown for course instances is throwing a 500 server error. This was reported on Slack. The impact is courses can't create a new link from Canvas to PL.

Chrome console shows `Response Status Error Code 500 from /pl/lti13_instance/34/course_navigation/course_instances`

Which I traced to:
```
TypeError: Cannot read properties of undefined (reading 'user')
    at isDangerousFullSystemAuthz (/PrairieLearn/apps/prairielearn/src/lib/authz-data-lib.ts:178:20)
    at hasRole (/PrairieLearn/apps/prairielearn/src/lib/authz-data-lib.ts:183:7)
    at assertHasRole (/PrairieLearn/apps/prairielearn/src/lib/authz-data-lib.ts:293:8)
    at selectCourseInstancesWithStaffAccess (/PrairieLearn/apps/prairielearn/src/models/course-instances.ts:100:3)
    at courseInstancesAllowedToLink (/PrairieLearn/apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:53:34)
    at <anonymous> (/PrairieLearn/apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:95:36)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
```

Perhaps from changes from #13498?

### PR DESCRIPTION
**Pull request by nwalters512**
# Description

LTI 1.3 course instance linking was broken by #13498. This PR aims to fix that.

Closes #13630.

# Testing

I tested the linking process with a local Canvas setup.

- After selecting a course on the "navigation" page, the list of course instances is correctly loaded. On master, this errored out.
- After selecting a course instance and clicking "Connect course instance", it's connected successfully. On master, even after fixing the original issue with loading course instances, this would have errored.

### CODE REVIEW

File: apps/prairielearn/src/ee/pages/instructorInstanceAdminLti13/instructorInstanceAdminLti13.ts [hunk 1]
```diff
@@ -106,8 +106,6 @@ router.get(
       sql.select_assessments,
       {
         course_instance_id: res.locals.course_instance.id,
-        authz_data: res.locals.authz_data,
-        req_date: res.locals.req_date,
```
Comment (nwalters512) [inline apps/prairielearn/src/ee/pages/instructorInstanceAdminLti13/instructorInstanceAdminLti13.ts:110]: This errored out because of the `errorOnUnusedParameters` option in `@prairielearn/postgres`.

This regressed in #13332. Those changes were not tested at the time.

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts [hunk 2]
```diff
@@ -53,6 +54,7 @@ async function courseInstancesAllowedToLink({
   const course_instances = await selectCourseInstancesWithStaffAccess({
     course,
     authzData,
+    // TODO: Why is "Previewer" included here? And why is this "Student Data Viewer" and not "Student Data Editor"?
```
Comment (nwalters512) [inline apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts]: 👀 I don't understand the current values.

EDIT: I guess these aren't doing what I thought they were. I thought these were the permissions that were checked on the course instances that were returned, but it seems like they're checked on the `authzData` for the current course? This API feels either wrong or misleading to me.

It's not clear to me why `requiredRole` is needed here at all. I would expect a function like `selectCourseInstancesWithStaffAccess` to simply give me back the course instances that the given user has staff access to, and if they don't have any permissions, this would just be an empty list. Maybe I'm thinking about this wrong?

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts [hunk 3]
```diff
@@ -77,24 +79,32 @@ async function coursesAllowedToLink({
...
 
     const course_instances = await courseInstancesAllowedToLink({
       course,
-      authzData: res.locals.authz_data,
+      authzData: PageAuthzDataSchema.parse({
+        ...authzData,
+        authn_user: authzData.user,
+        is_administrator: res.locals.is_administrator,
+        authn_is_administrator: res.locals.authn_is_administrator,
+      } satisfies z.input<typeof PageAuthzDataSchema>),
```
Comment (nwalters512) [inline apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts]: This was necessary to make both TypeScript and runtime behavior happy. I don't like this at all, but also didn't see another way to make this work with our current suite of authz functions.

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts [hunk 4]
```diff
@@ -225,21 +242,8 @@ router.post(
...
-    });
-    const hasCourseInstanceAllowed = courseInstancesAllowed.some(
-      (ci) => ci.id === course_instance.id,
-    );
-
-    const coursesAllowed = await coursesAllowedToLink({
-      user_id: authzData.authn_user.user_id,
-      is_administrator: res.locals.is_administrator,
-    });
-    const hasCourseAllowed = coursesAllowed.some((c) => c.id === course_instance.course_id);
```
Comment (nwalters512) [inline apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:240]: I believe these checks are rendered unnecessary by the `hasRole(...)` check above, but I'd like a second set of eyes on this.

**Review by nwalters512 — COMMENTED** [review]
I have two main issues with this PR in its current form:

- The usage of `requiredRole` in `selectCourseInstancesWithStaffAccess(...)`
- the need for `PageAuthzDataSchema.parse(...)`

I'd like to discuss and address both of these before merging.

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts (hunk 2 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts]: `requiredRole` is designed to check the role of the user at call-time. So in this case, we are asserting that the current user is at least a course previewer in the current course. The design of this is to prevent this function from being called by a student.

In this specific function, this authorization check doesn't matter, since the user you look up is always yourself. However, if you imagine a similar function, like: `selectCourseInstancesWithStaffAccess({ userUid })`, you would want to prevent a student calling this function with an arbitrary `userUid`, and so requiring the caller to have at least previewer makes more sense.

---

That being said, I still want to discuss this further and don't love this pattern / fully understand if this is a good idea. This was on our dev meeting list to discuss (alongside #13530) to discuss the actual role of these functions and what we are trying to prevent. My understanding is that we have more pages where middleware auth isn't enough to distinguish the type of user: e.g. you may have a student data viewer, student data editor, and course owner on the same page. Such a page may display different data depending on the role, and the set of allowed actions may differ based on the role. 

Thus, my understood goal is that to prepare for more of these pages in the future, we want to have model functions that have no prior assumptions as to the authorization checks performed before the model function was called. In the current system of pages, many of these checks then feel redundant, but it's possible in the future they actually catch a bug.

File: apps/prairielearn/src/lib/authz-data-lib.ts [hunk 5]
```diff
@@ -312,3 +313,42 @@ export function calculateCourseInstanceRolePermissions(role: EnumCourseInstanceR
     has_course_instance_permission_edit: ['Student Data Editor'].includes(role),
   };
 }
+
+/**
+ * Converts a `PlainAuthzData` into a `PageAuthzData`. Assumes that the context
+ * in which this is called does not differentiate between authenticated user and
+ * effective user.
+ */
+export function makePageAuthzData({
```
Comment (reteps) [inline apps/prairielearn/src/lib/authz-data-lib.ts:326]: Can we add a note here that this isn't a finalized solution?

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts [hunk 6]
```diff
@@ -77,24 +77,30 @@ async function coursesAllowedToLink({
...
+    const { authzData, course } = await constructCourseOrInstanceContext({
+      user: res.locals.authn_user,
+      course_id: unsafe_course_id,
+      course_instance_id: null,
+      ip: req.ip || null,
+      req_date: res.locals.req_date,
+      is_administrator: res.locals.is_administrator,
+    });
+
+    if (!authzData || !hasRole(authzData, ['Editor'])) {
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:94]: The `hasRole(authzData, ['Editor'])` replaces `coursesAllowedToLink` right?

Comment (reteps) [reply apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:94]: I don't understand why this is not `hasRole(authzData, ['Editor', 'Student Data Editor'])`

Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:94]: We've only authed against a course, not an instance. A user will never have "Student Data Editor" permissions in a course by itself, only in a specific instance.

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts (hunk 2 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts]: I backed out my comment in the source. We can have a bigger discussion about this kind of API in the future.

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts (hunk 3 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts]: I moved this to a helper function in e9627f2. This will be good enough for now.

File: apps/prairielearn/src/lib/authz-data-lib.ts (hunk 5 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/authz-data-lib.ts:326]: Done in d49897b.

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts (hunk 6 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:94]: Of course, yeah.

File: apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts (hunk 4 above)
Comment (trombonekenny) [reply apps/prairielearn/src/ee/pages/lti13CourseNavigation/lti13CourseNavigation.ts:240]: Outsider set of eyes, but LGTM. These checks predated the `constructCourseOrInstanceContext` and `hasRole` filter.

**Comment by nwalters512** [comment]
@trombonekenny `constructCourseOrInstanceContext` is only used when you already have a course and want to authorize a given user in the context of it. It's not suitable for code that's meant to fetch a list of courses.
