### PR TITLE
Fix sort, escape and search in assessment students page

### LINKED ISSUE #10262: In Students tab, allow sorting by "Fingerprint Changes"
In the Students tab, allow sorting by "Fingerprint Changes" which makes it easier to find those who have unexpected number of Fingerprint Changes.
(Also see [discussion on pl-help](https://prairielearn.slack.com/archives/C266KEH9A/p1721372271679939))

### LINKED ISSUE #10263: In Students tab, with a group assessment, search does not find students
In Students tab, with a group assessment, search does not look into group members. So, xyz@ubc.ca does not find the xyz student.
(Also see [discussion on pl-help](https://prairielearn.slack.com/archives/C266KEH9A/p1721372271679939))

### LINKED ISSUE #10264: Assessment instances page does not escape user name/UID
If UID/name include HTML characters they are not escaped before formatting the cells. For an example of one way to do it, see the gradebook page:

https://github.com/PrairieLearn/PrairieLearn/blob/ef9758ef8b44ac76e4bd6332fb7f0a11e55fdf6b/apps/prairielearn/assets/scripts/instructorGradebookClient.ts#L86

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Fixes #10262: allows sort by fingerpring changes.
Fixes #10263: search by UID/name/role in group assessments (a custom search had to be used due to limitations in bootstrap-table).
Fixes #10264: escapes name, UID, UIN, assessment instance link text.

### CODE REVIEW

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts [hunk 1]
```diff
@@ -239,120 +331,33 @@ onDocumentReady(() => {
...
+            type="button"
+            title="Show fingerprint changes help"
+            data-toggle="modal"
+            data-target="#fingerprint-changes-help"
+          >
+            <i class="bi-question-circle-fill" aria-hidden="true"></i>
+          </button>`,
+        class: 'text-center align-middle',
+        // Hidden for groupwork by default, as it is not as relevant in that context
+        visible: !assessmentGroupWork,
```
Comment (jonatanschroeder) [inline apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:349]: Minor change: I added the fingerprint column unconditionally, but made it hidden by default for group assessments.

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts [hunk 2]
```diff
@@ -92,6 +92,19 @@ onDocumentReady(() => {
           $(this).find('.select-time-limit').trigger('change');
         });
     },
+    customSearch: (data: AssessmentInstanceRow[], searchText: string) => {
```
Comment (nwalters512) [inline apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:95]: What's the reason we can't use https://bootstrap-table.com/docs/api/column-options/#searchformatter instead of implementing a custom search function?

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts [hunk 3]
```diff
@@ -158,16 +171,97 @@ onDocumentReady(() => {
...
+      ...(assessmentGroupWork
+        ? [
+            {
+              field: 'group_name',
+              title: 'Name',
+              visible: false,
+              sortable: true,
+              class: 'align-middle',
+              switchable: true,
+              formatter: (value: string) => html`${value}`.toString(),
```
Comment (nwalters512) [inline apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:193]: Does this work if you use `escapeHtml(...)` instead? It should do the same thing, but be more explicit about why it's being done.

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:349]: Does this mean it can be toggled on via the "Columns" selector? I don't think this is a problem, just curious.

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts (hunk 3 above)
Comment (jonatanschroeder) [reply apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:193]: `escapeHtml()` receives an `HtmlSafeString` as parameter and returns an `HtmlSafeString`. Converting the return value of `escapeHtml` back to a string would escape it twice.

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts (hunk 1 above)
Comment (jonatanschroeder) [reply apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:349]: Indeed.

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts (hunk 2 above)
Comment (nwalters512) [reply apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:95]: I'm good with that! Presumably we'll move to another library before long 🙃

File: apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts (hunk 3 above)
Comment (nwalters512) [reply apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:193]: That's not true, you can prove this to yourself with this little snippet:

```js
import { escapeHtml } from '@prairielearn/html';
console.log(escapeHtml('<script>alert("hi")</script>').toString());
```

That logs the following, which is not double-escaped:

```
&lt;script&gt;alert(&#34;hi&#34;)&lt;/script&gt;
```

Comment (jonatanschroeder) [reply apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:193]: You are passing a string as the first argument, which doesn't match the function signature. This will trigger the type checker.

Comment (nwalters512) [reply apps/prairielearn/assets/scripts/instructorAssessmentInstancesClient.ts:193]: Indeed 🙃 

Maybe we should export `escapeHtmlRaw` from that library? We can do that in a future PR though.

**Review by nwalters512 — APPROVED** [review]
