### PR TITLE
Fix workspace launch race condition

### LINKED ISSUE #8648: Possible race condition when rebooting workspaces during launch
From a recent workspace launch log it looks like there might be a race condition where clicking "Reboot" at a certain point during the launch causes PL to end up with an incorrect workspace host assignment.

See https://us.prairielearn.com/pl/workspace/1257087/logs/version/1

### PR DESCRIPTION
**Pull request by nwalters512**
Closes #8648. See inline description for more details.

Note that in some sense, this is just a bandaid, and results in what is still a subpar UX: the browser will receive launching updates from both launch attempts, which might result in the image pull percentage oscillating rapidly between two values from two different hosts or other weirdness. There are various ways we could fix this. One idea when updating the workspace state message, always do the same `launch_uuid` check to determine if we're still the "current" launch attempt.

I opted not to implement that or anything else in this PR; this will be valuable on its own as it will avoid the "Error proxying workspace request" message that can only be recovered from with another request.

Note: I was unable to test how this behaves during a race, as it's actually a little difficult to force things into a bad state. I did validate that workspaces can still launch, which is what we really care about.

### CODE REVIEW

File: apps/workspace-host/src/interface.js [hunk 1]
```diff
@@ -920,11 +920,6 @@ async function initSequenceAsync(workspace_id, useInitialZip, res) {
 
     try {
       await workspaceUtils.updateWorkspaceMessage(workspace.id, 'Creating container');
-      const hostname = `${workspace_server_settings.server_to_container_hostname}:${workspace.launch_port}`;
-      await sqldb.queryAsync(sql.update_workspace_hostname, {
-        workspace_id,
-        hostname,
-      });
```
Comment (nwalters512) [inline apps/workspace-host/src/interface.js:927]: The fact that we blindly write the `hostname` potentially a long time after the launch request starts is the root problem here. In theory, another solution would be to write the hostname at the same time that we write the `launch_uuid`; I think things would behave the same in the end. We'd still have to check the `launch_uuid` before transitioning to the running state, however.

**Review by mwest1066 — APPROVED** [review]

**Comment by mwest1066** [comment]
> I opted not to implement that or anything else in this PR; this will be valuable on its own as it will avoid the "Error proxying workspace request" message that can only be recovered from with another request.

That's reasonable.
