### PR TITLE
Fix broken navbar link on public assessment page

### LINKED ISSUE #12057: Public assessment page has broken link in navbar
### Details

In the public assessment page (`/pl/public/course_instance/XXX/assessments`), the navbar has a link to the course in the navbar. That link is broken, points to `/pl/questions`.

@SethPoulsen

### PR DESCRIPTION
**Pull request by nwalters512**
## Description

Fixes the broken navbar link on public course instance pages (e.g., `/pl/public/course_instance/XXX/assessments`). The navbar was pointing to `/pl/questions` instead of the correct public questions page. 

The issue was that the `NavbarPublic` component relied on `urlPrefix` which is not set for some routes. Now the component constructs the URL directly using the course ID.

Closes #12057

## Testing

I tested the new link, it reliably leads to the course's public questions page.

### CODE REVIEW

File: apps/prairielearn/src/components/Navbar.tsx [hunk 1]
```diff
@@ -982,13 +982,13 @@ function NavbarInstructor({
...
-  const { course, urlPrefix } = resLocals;
+  const { course } = resLocals;
   return html`
     <li class="nav-item btn-group">
       <a
         class="nav-link"
         aria-label="Link to page showing all public questions for the course."
-        href="${urlPrefix}/questions"
+        href="/pl/public/course/${course?.id}/questions"
       >
```
Comment (reteps) [inline apps/prairielearn/src/components/Navbar.tsx:992]: why is course optional here?

Comment (nwalters512) [reply apps/prairielearn/src/components/Navbar.tsx:992]: This matches the defensiveness we're already using two lines down with `short_name`. This is because we're pulling out of untyped, untrusted `res.locals`.
