### PR TITLE
[Group Work] Rewrite create group

### LINKED ISSUE #3221: SQL error when trying to create new group name
https://prairielearn.slack.com/files/UGGPHFKFB/F01BT0Y06S0/bandicam_2020-09-28_23-53-45-911.mp4?origin_team=T0PHEMPRV&origin_channel=C0XBTPZMZ

image

```
{
  msg: 'more than one row returned by a subquery used as an expression',
  id: 'LTW9E2LUSYFI',
  status: 500,
  stack: 'Async Stacktrace:\n' +
    '    at /PrairieLearn/pages/studentAssessmentHomework/studentAssessmentHomework.js:157:29\n' +
    '    at handleError (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:418:13)\n' +
    '\n' +
    'error: more than one row returned by a subquery used as an expression\n' +
    '    at Parser.parseErrorMessage (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:278:15)\n' +
    '    at Parser.handlePacket (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:126:29)\n' +
    '    at Parser.parse (/PrairieLearn/node_modules/pg-protocol/dist/parser.js:39:38)\n' +
    '    at Socket.<anonymous> (/PrairieLearn/node_modules/pg-protocol/dist/index.js:8:42)\n' +
    '    at Socket.emit (events.js:315:20)\n' +
    '    at Socket.EventEmitter.emit (domain.js:483:12)\n' +
    '    at addChunk (_stream_readable.js:295:12)\n' +
    '    at readableAddChunk (_stream_readable.js:271:9)\n' +
    '    at Socket.Readable.push (_stream_readable.js:212:10)\n' +
    '    at TCP.onStreamRead (internal/stream_base_commons.js:186:23)',
  data: `{"sqlError":{"length":129,"name":"error","severity":"ERROR","code":"21000","file":"nodeSubplan.c","line":"1136","routine":"ExecSetParamPlan","message":"more than one row returned by a subquery used as an expression"},"sql":"-- BLOCK join_justcreated_group\\nWITH log AS (\\n    INSERT INTO group_users\\n        (group_id, user_id)\\n    VALUES\\n        (\\n            (SELECT id FROM groups WHERE name = $group_name AND deleted_at IS NULL),\\n            $user_id\\n        )\\n    RETURNING group_id\\n)\\nINSERT INTO group_logs\\n    (authn_user_id, user_id, group_id, action)\\nSELECT $user_id, $user_id, group_id, 'join'\\nFROM log;\\n","sqlParams":{"assessment_id":2306762,"user_id":919510,"group_name":"team5"}}`,
  referrer: 'https://prairielearn.engr.illinois.edu/pl/course_instance/118734/assessment/2306762/',
  response_id: '9bf664d4-d63e-4f08-8a6e-e01d711e804f',
  level: 'error',
  message: 'Error page',
  timestamp: '2020-09-29T04:54:09.744Z'
}
```

### PR DESCRIPTION
**Pull request by frankyhao**
fix #3221

### CODE REVIEW

File: pages/studentAssessmentHomework/studentAssessmentHomework.sql [hunk 1]
```diff
@@ -46,42 +46,39 @@ WITH log AS (
...
-        (
-            $group_name,
-            (SELECT id FROM group_configs WHERE assessment_id = $assessment_id AND deleted_at IS NULL),
-            (SELECT course_instance_id FROM group_configs WHERE assessment_id = $assessment_id AND deleted_at IS NULL)
-        )
+    (
+        SELECT 
+            $group_name, id, course_instance_id
+        FROM 
+            group_configs
```
Comment (mwest1066) [inline pages/studentAssessmentHomework/studentAssessmentHomework.sql:62]: Would you mind making this `group_configs AS gc` and putting an explicit `gc.` on the front of all column references? That's much easier for me to check, and I think it's generally safer (less likely to accidentally reference the wrong `id` column, for example).

File: pages/studentAssessmentHomework/studentAssessmentHomework.sql [hunk 2]
```diff
@@ -46,42 +46,39 @@ WITH log AS (
...
-SELECT $user_id, $user_id, id, 'create'
-FROM log;
-
--- BLOCK join_justcreated_group
-WITH log AS (
+),
+create_log AS (
+    INSERT INTO group_logs
+        (authn_user_id, user_id, group_id, action)
+    SELECT $authn_user_id, $user_id, id, 'create' FROM create_group
```
Comment (mwest1066) [inline pages/studentAssessmentHomework/studentAssessmentHomework.sql:72]: Similarly here, change to `create_group AS cg`.

File: pages/studentAssessmentHomework/studentAssessmentHomework.sql [hunk 3]
```diff
@@ -46,42 +46,39 @@ WITH log AS (
...
     INSERT INTO group_users
-        (group_id, user_id)
-    VALUES
-        (
-            (SELECT id FROM groups WHERE name = $group_name AND deleted_at IS NULL),
-            $user_id
-        )
-    RETURNING group_id
+        (user_id, group_id)
+    SELECT $user_id, id FROM create_group
```
Comment (mwest1066) [inline pages/studentAssessmentHomework/studentAssessmentHomework.sql:77]: And again `create_group AS cg`

File: pages/studentAssessmentHomework/studentAssessmentHomework.sql [hunk 4]
```diff
@@ -46,42 +46,39 @@ WITH log AS (
...
 )
 INSERT INTO group_logs
     (authn_user_id, user_id, group_id, action)
-SELECT $user_id, $user_id, group_id, 'join'
-FROM log;
+SELECT $authn_user_id, $user_id, id, 'create' FROM create_group;
```
Comment (mwest1066) [inline pages/studentAssessmentHomework/studentAssessmentHomework.sql:81]: And one last `create_group AS cg` 😄

File: pages/studentAssessmentHomework/studentAssessmentHomework.sql [hunk 5]
```diff
@@ -46,42 +46,39 @@ WITH log AS (
...
-            (SELECT course_instance_id FROM group_configs WHERE assessment_id = $assessment_id AND deleted_at IS NULL)
-        )
+    (
+        SELECT 
+            $group_name, gc.id, gc.course_instance_id
+        FROM 
+            group_configs AS gc
+        WHERE
+            gc.assessment_id = $assessment_id
+            AND deleted_at IS NULL
```
Comment (mwest1066) [inline pages/studentAssessmentHomework/studentAssessmentHomework.sql:65]:
```suggestion
            AND gc.deleted_at IS NULL
```

Comment (mwest1066) [reply pages/studentAssessmentHomework/studentAssessmentHomework.sql]: @frankyhao can you check that this change is ok?

Comment (frankyhao) [reply pages/studentAssessmentHomework/studentAssessmentHomework.sql]: Yeah, I just manually check the functionality of creating groups.
Sorry, I forgot to add "gc." before deleted_at. The previous version could still pass CI because we only have 1 table in FROM, not ambiguous. It is definitely better to have a "gc." to specific table and decrease risks in future development.

Comment (mwest1066) [reply pages/studentAssessmentHomework/studentAssessmentHomework.sql]: Thanks!
