### PR TITLE
Make errorAbandonedJobs safe for multiple servers

### LINKED ISSUE #3160: Cron errorAbandonedJobs is not multi-server safe
`cron/errorAbandonedJobs.js` calls https://github.com/PrairieLearn/PrairieLearn/blob/622417be74eb5f4f03dcf345e1dc631fd1690154/lib/server-jobs.js#L345

This checks which running jobs are not present in the _local_ server's job list: https://github.com/PrairieLearn/PrairieLearn/blob/622417be74eb5f4f03dcf345e1dc631fd1690154/lib/server-jobs.js#L349

Any missing jobs are killed.

This will kill any jobs started by a different server, because they won't be in the local server's job list.

To fix this, we should store the server `instance_id` in the `jobs` (or `job_sequences`?) table so we can only kill our own jobs. Maybe we should add a new table called `hosts` that has one row per VM instance so we can refer to them. This table could have a `heartbeat_at` column that we update every 10 seconds or so.

It would also be good to add a cron job that looks for jobs that belong to hosts that are no longer alive (last heartbeat too long ago) and kills them.

### LINKED ISSUE #6454: Error: Another user is already syncing or modifying the course:
I cant seem to finds a way to resolve the following issue after pressing Pull from remote Git Repository:
image

### PR DESCRIPTION
**Pull request by nwalters512**
This PR adds heartbeating to servers jobs so that we can properly detect when a job has been "abandoned", most likely by a server crash. Previously, we relied on an in-process list of "live" jobs, but that was only aware of jobs on that particular instance of PL; it didn't account for jobs that were running on other servers. This has caused a few unfortunate bugs, most notably stuck course locks during syncs or file edits.

Closes #3160.
Closes #6454.
Closes https://github.com/PrairieLearnInc/sysconf/issues/317.

### CODE REVIEW

File: cron/errorAbandonedJobs.js [hunk 1]
```diff
@@ -1,12 +1,7 @@
-var ERR = require('async-stacktrace');
+const util = require('util');
 
-var serverJobs = require('../lib/server-jobs');
-
-module.exports = {};
+const serverJobs = require('../lib/server-jobs');
 
 module.exports.run = function (callback) {
```
Comment (nwalters512) [inline cron/errorAbandonedJobs.js:5]: Should we introduce `runAsync` support for cron jobs?

File: lib/server-jobs.js [hunk 2]
```diff
@@ -189,19 +192,43 @@ Job.prototype.failAsync = util.promisify(Job.prototype.fail);
...
+  // Start a periodic task to heartbeat all live jobs. We don't use a cronjob
+  // for this because we want this to run for every host.
+  intervalId = setInterval(() => {
+    const jobIds = Object.keys(module.exports.liveJobs);
+    if (jobIds.length === 0) return;
+
+    sqlDb.queryAsync(sql.update_heartbeats, { job_ids: jobIds }).catch((err) => {
+      logger.error('Error updating heartbeats for live server jobs', err);
+    });
+  }, 10 * 1000);
```
Comment (nwalters512) [inline lib/server-jobs.js:209]: Should this period be configurable?

File: lib/server-jobs.sql [hunk 3]
```diff
@@ -144,6 +144,13 @@ FROM
 WHERE
     j.status = 'Running';
 
+-- BLOCK select_abandoned_jobs
+SELECT id, job_sequence_id
+FROM jobs AS j
+WHERE
+    j.status = 'Running'
+    AND j.heartbeat_at < (CURRENT_TIMESTAMP - interval '30 seconds');
```
Comment (nwalters512) [inline lib/server-jobs.sql:152]: Should this period be configurable?

File: lib/server-jobs.sql [hunk 4]
```diff
@@ -160,7 +167,7 @@ WHERE
         ) -- no running jobs and no recently finished jobs
     )
 RETURNING
-    js.*;
+    js.id;
```
Comment (nwalters512) [inline lib/server-jobs.sql:170]: I suspect that in general, things will be slightly more performant if we're only returning columns we actually need?

File: pages/partials/jobSequenceResults.ejs [hunk 5]
```diff
@@ -23,24 +23,36 @@
...
         // Join the rooms for the job_sequence and for each individual job.
         // Check return values for a change that happened since we rendered the page
         // and reload if anything changed. This avoids the race condition where
         // jobs change between page render and socket activation.
 
-        socket.emit('joinJobSequence', {job_sequence_id: <%= job_sequence.id %>}, function(msg) {
-            if (msg.job_count != '<%= job_sequence.job_count %>') {window.location.reload(true);}
+        socket.emit('joinJobSequence', {
+            job_sequence_id: '<%= job_sequence.id %>',
+            token: '<%= job_sequence.token %>',
```
Comment (nwalters512) [inline pages/partials/jobSequenceResults.ejs:40]: Most changes here were just reformatting; the addition of the `token` properties here and below should be the only functional changes.

File: cron/errorAbandonedJobs.js (hunk 1 above)
Comment (mwest1066) [reply cron/errorAbandonedJobs.js:5]: I'm definitely on board if you want to add it.

File: lib/server-jobs.js [hunk 6]
```diff
@@ -9,6 +9,9 @@ const logger = require('./logger');
 const socketServer = require('./socket-server');
 const sqldb = require('../prairielib/lib/sql-db');
 const sqlLoader = require('../prairielib/lib/sql-loader');
+const sqlDb = require('../prairielib/sql-db');
```
Comment (mwest1066) [inline lib/server-jobs.js:12]: Consistency with #6451
```suggestion
const sqldb = require('../prairielib/sql-db');
```

File: lib/server-jobs.js (hunk 2 above)
Comment (mwest1066) [reply lib/server-jobs.js:209]: I think so -- it's easy to do and can't hurt?

File: lib/server-jobs.sql (hunk 3 above)
Comment (mwest1066) [reply lib/server-jobs.sql:153]: Yep again.

File: lib/server-jobs.js [hunk 7]
```diff
@@ -492,15 +498,27 @@ module.exports.getJobSequenceAsync = util.promisify(module.exports.getJobSequenc
...
+    const jobSequenceTokenData = {
+      jobSequenceId: job_sequence_id.toString(),
+    };
+    jobSequence.token = csrf.generateToken(jobSequenceTokenData, config.secretKey);
+
+    (jobSequence.jobs ?? []).forEach((job) => {
+      // Also generate a token for each job.
+      const jobTokenData = { jobId: job.id.toString() };
+      job.token = csrf.generateToken(jobTokenData, config.secretKey);
+
```
Comment (mwest1066) [inline lib/server-jobs.js:512]: Why are we doing this here and not inside `getJobSequence()`?

**Review by mwest1066 — APPROVED** [review]

File: lib/server-jobs.js (hunk 7 above)
Comment (nwalters512) [reply lib/server-jobs.js:512]: Great question! Because I started at the pages that render the live output and walked back to this callsite and no further 😂 I'll move it to that other function.

File: cron/errorAbandonedJobs.js (hunk 1 above)
Comment (nwalters512) [reply cron/errorAbandonedJobs.js:5]: I do, but I'll save this for a separate PR.

File: lib/server-jobs.js (hunk 7 above)
Comment (nwalters512) [reply lib/server-jobs.js]: Done in cc1e319.

File: lib/server-jobs.js (hunk 2 above)
Comment (nwalters512) [reply lib/server-jobs.js]: Done in 5346f32.

File: lib/server-jobs.sql (hunk 3 above)
Comment (nwalters512) [reply lib/server-jobs.sql]: Done in 5346f32.

File: lib/server-jobs.js [hunk 8]
```diff
@@ -476,7 +483,27 @@ module.exports.getJobSequence = function (job_sequence_id, course_id, callback)
...
+      if (job.output) {
+        const ansiup = new AnsiUp();
+        job.output = ansiup.ansi_to_html(job.output);
```
Comment (mwest1066) [inline lib/server-jobs.js:502]: I think these lines should not have been copied from `getJobSequenceWithFormattedOutput()` to this location in `getJobSequence()`?

Comment (nwalters512) [reply lib/server-jobs.js]: Indeed! Removed in 7afbe51.
