### PR TITLE
fix: Return group data from the assessments API

### LINKED ISSUE #3813: Groupwork data missing
I managed to download all data files of cs233(fall2020) but found all the students data related to ''group work'' are missing.  The submission, log,  and instance questions files only record TA and instructor's data. Also students group work scores are null in gradebook.

### PR DESCRIPTION
**Pull request by nwalters512**
Started as #4850, but I opened a new PR so that I could push up the desired changes, as the original contributor was no longer interested in working on the PR.

Fixes #3813, closes #4850.

## TODO

- [x] Address feedback left on the original PR by @mwest1066 and @nwalters512

### CODE REVIEW

**Comment by nwalters512** [comment]
Unfortunately, it looks like it's non-trivial to write tests for group work, as that would require copying a ton of boilerplate from the existing group work tests. In the interest of getting this fix merged quickly, I manually tested the changes with the below workflow:

1. Sync the example course
2. As a student (`dev@illinois.edu`), create a new group for the "Group Activity Template" assessment
3. Run the following query to add a new user:
```sql
insert into users (uid, uin, name, institution_id) values ('nathan@prairielearn.com', 0000000000, 'Nathan Walters', 1);
```
4. In a different browser, make that new user the effective user
5. Add yourself to the group that was previously created
6. Start the assessment
7. Make a submission
8. Generate an API token for `dev@illinois.edu`
9. Make the following request and observe that the result contains group information:
```sh
$ curl -H 'Private-Token: $TOKEN' localhost:3000/pl/api/v1/course_instances/1/assessments/15/assessment_instances
[
  {
    "open": true,
    "points": 0.5,
    "user_id": null,
    "group_id": 1,
    "user_uid": null,
    "user_name": null,
    "user_role": "None",
    "group_name": "nathantesting",
    "max_points": 10,
    "score_perc": 5,
    "start_date": "2022-01-13T15:23:56-06",
    "assessment_id": 15,
    "highest_score": true,
    "group_uid_list": [
      "dev@illinois.edu",
      "nathan@prairielearn.com"
    ],
    "time_remaining": "Open",
    "assessment_name": "hw10-templateGroupWork",
    "assessment_label": "HW10",
    "assessment_title": "Group Activity Template",
    "duration_seconds": 25.567546,
    "max_bonus_points": 0,
    "assessment_number": "10",
    "assessment_instance_id": 1,
    "assessment_instance_number": 1,
    "assessment_set_abbreviation": "HW"
  }
]
```
10. As a student, make a submission to the "Homework Design: Best Practices" assessment.
11. Make the following request and observe that the request still works for non-group assessments:
```sh
curl -H 'Private-Token: cc339359-5562-4227-8b96-269ccd9d2f90' localhost:3000/pl/api/v1/course_instances/1/assessments/7/assessment_instances
[
  {
    "open": true,
    "points": 1,
    "user_id": 3,
    "group_id": null,
    "user_uid": "nathan@prairielearn.com",
    "user_name": "Nathan Walters",
    "user_role": "Student",
    "group_name": null,
    "max_points": 30,
    "score_perc": 0,
    "start_date": "2022-01-13T15:39:22-06",
    "assessment_id": 7,
    "highest_score": true,
    "group_uid_list": null,
    "time_remaining": "Open",
    "assessment_name": "hw02-bestPractices",
    "assessment_label": "HW2",
    "assessment_title": "Homework Design: Best Practices",
    "duration_seconds": 4.052544,
    "max_bonus_points": 0,
    "assessment_number": "2",
    "assessment_instance_id": 2,
    "assessment_instance_number": 1,
    "assessment_set_abbreviation": "HW"
  }
]
```

File: api/v1/endpoints/queries.sql [hunk 1]
```diff
@@ -65,7 +68,8 @@ WITH object_data AS (
         JOIN course_instances AS ci ON (ci.id = a.course_instance_id)
         JOIN assessment_sets AS aset ON (aset.id = a.assessment_set_id)
         JOIN assessment_instances AS ai ON (ai.assessment_id = a.id)
-        JOIN users AS u ON (u.user_id = ai.user_id)
+        LEFT JOIN group_info(a.id) AS gi ON (gi.id = ai.group_id)
+        LEFT JOIN users AS u ON (u.user_id = ai.user_id)
```
Comment (nwalters512) [inline api/v1/endpoints/queries.sql:72]: This was necessary because `assessment_instance.user_id` is null for group work.

Ultimately, group work will have non-null values for `group_id`, `group_name`, and `group_uid_list` and null values for `user_uid`, `user_name`, and `user_id`. The opposite will be true for non-group work.

The name `group_uid_list` gives us some flexibility in the future if we want to introduce a property like `group_users` that would allow us to include more information to mirror what's available for non-group assessment instances:

```json
{
  "group_users": [
    {
      "user_name": "Foo",
      "user_id": 1234,
      "user_uid": "foo@bar.com"
    }
  ]
}
```

Although now I'm thinking that `group_uids` might be better than `group_uids_list`? We don't use the `_list` suffix anywhere else in the API AFAIK.

Comment (Yucheng-Jiang) [reply api/v1/endpoints/queries.sql:72]: Is there a possible fix to this bug? I was comparing code blocks between instructurepages and API/v1, not quite familiar with the project structure. Appreciate any effort on fixing this !!! Thanks in advance.

**Review by mwest1066 — APPROVED** [review]
