### PR TITLE
Loosen CSP restrictions for embeddable PDF files

### LINKED ISSUE #10181: Preview of PDF files in file browser not working due to Content Security Policy
The instructor file browser has a mode to preview PDF files, but it's currently broken. Example: https://us.prairielearn.com/pl/course/108/course_admin/file_view/clientFilesCourse/formulas.pdf.

A console error lists:

```console
Refused to frame 'https://us.prairielearn.com/' because an ancestor violates the following Content Security Policy directive: "frame-ancestors 'none'".
```

Testing locally with a disabled content security policy shows the preview as expected.

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Fixes #10181. This allows PDF files to be embedded.

The identification of if a file is a PDF file is based on the call to `res.type`. For the instructor file browser/download case (the only page that currently sets `res.type` to a value that may be application/pdf), this is based on a type specified by a request query. This would open up the possibility of a user explicitly setting the type to PDF to bypass CSP, however I don't believe this would typically be a problem since this page only serves static files.

### CODE REVIEW

File: apps/prairielearn/src/middlewares/content-security-policy.ts [hunk 1]
```diff
@@ -12,6 +12,17 @@ router.all('/*', function (req, res, next) {
   // Added for backwards compatibility with older browsers.
   res.header('X-Frame-Options', 'DENY');
 
+  const originalResType: typeof res.type = res.type.bind(res);
+  res.type = (type) => {
```
Comment (nwalters512) [inline apps/prairielearn/src/middlewares/content-security-policy.ts:16]: This won't work for calls like `res.setHeader('Content-Type', ...)`, of which we have at least one:

https://github.com/PrairieLearn/PrairieLearn/blob/e1b0807810588231850b4ca1f57dcb2206fa6de4/apps/prairielearn/src/pages/submissionFile/submissionFile.ts#L77

While we could update this to monkey-patch `setHeader` or update the above callsite to use `res.type` instead, it's probably more robust to use something like https://github.com/jshttp/on-headers to handle this in a fully generic way.

Comment (jonatanschroeder) [reply apps/prairielearn/src/middlewares/content-security-policy.ts:16]: Done in cb9680e29.

**Review by nwalters512 — APPROVED** [review]
