### PR TITLE
Speed up instructor manual grading query

### LINKED ISSUE #6152: Manual grading page fails to render with many assessment questions
This assessment has about 1000 assessment questions: https://www.prairielearn.org/pl/course_instance/129459/instructor/assessment/2321757/manual_grading

The SQL query for that page takes about 2 minutes to execute, causing a timeout: https://github.com/PrairieLearn/PrairieLearn/blob/086854355489536054aaf53596604cac5698f32d/pages/instructorAssessmentManualGrading/assessment/assessment.sql#L1

Weirdly, running each CTE on its own is fast (below 1 second) and the main SELECT (without the JOINs on the CTEs) is also below 1 second. The JOINs seem very simple, so I don't understand why the whole query is slow.

Query plans are below. As we can see from those, the full query uses a `Seq Scan on variants v` in the inner loop of the first CTE, whereas no seq scan is used when this CTE is run standalone.

## Query plan for first CTE when executed as a standalone query

```
                                                                                                                QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 CTE Scan on instance_questions_with_submission  (cost=8416095.77..8416243.01 rows=7362 width=104) (actual time=95.881..109.512 rows=520 loops=1)
   CTE instance_questions_with_submission
     ->  GroupAggregate  (cost=1002.73..8416095.77 rows=7362 width=104) (actual time=95.879..108.522 rows=520 loops=1)
           Group Key: iq.assessment_question_id
           ->  Gather Merge  (cost=1002.73..8415801.29 rows=7362 width=115) (actual time=95.415..106.286 rows=892 loops=1)
                 Workers Planned: 2
                 Workers Launched: 2
                 ->  Nested Loop Left Join  (cost=2.70..8413951.51 rows=3068 width=115) (actual time=91.081..100.241 rows=297 loops=3)
                       ->  Nested Loop Left Join  (cost=2.41..8402439.32 rows=3068 width=70) (actual time=91.073..99.166 rows=297 loops=3)
                             ->  Nested Loop Semi Join  (cost=2.12..8390923.67 rows=3068 width=25) (actual time=91.057..98.063 rows=297 loops=3)
                                   ->  Nested Loop  (cost=0.99..1525222.36 rows=57930 width=33) (actual time=90.976..93.985 rows=304 loops=3)
                                         ->  Parallel Index Scan using assessment_questions_pkey on assessment_questions aq  (cost=0.42..630487.46 rows=505 width=8) (actual time=90.928..91.312 rows=318 loops=3)
                                               Filter: (assessment_id = 2321757)
                                               Rows Removed by Filter: 109901
                                         ->  Index Scan using instance_questions_assessment_question_id_assessment_instan_key on instance_questions iq  (cost=0.56..1766.27 rows=548 width=33) (actual time=0.003..0.005 rows=1 loops=954)
                                               Index Cond: (assessment_question_id = aq.id)
                                   ->  Nested Loop  (cost=1.13..124.35 rows=36 width=8) (actual time=0.011..0.011 rows=1 loops=912)
                                         ->  Index Scan using variants_instance_question_id_number_key on variants v  (cost=0.56..33.88 rows=27 width=16) (actual time=0.004..0.004 rows=1 loops=912)
                                               Index Cond: (instance_question_id = iq.id)
                                         ->  Index Only Scan using submissions_variant_id_idx on submissions s  (cost=0.57..2.99 rows=36 width=8) (actual time=0.004..0.004 rows=1 loops=910)
                                               Index Cond: (variant_id = v.id)
                                               Heap Fetches: 892
                             ->  Index Scan using users_pkey on users agu  (cost=0.29..3.75 rows=1 width=45) (actual time=0.001..0.001 rows=0 loops=892)
                                   Index Cond: (user_id = iq.assigned_grader)
                       ->  Index Scan using users_pkey on users lgu  (cost=0.29..3.75 rows=1 width=45) (actual time=0.001..0.001 rows=0 loops=892)
                             Index Cond: (user_id = iq.last_grader)
 Planning Time: 2.787 ms
 Execution Time: 110.044 ms
(28 rows)
```

## Query plan for full query

```
                                                                                                                QUERY PLAN
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 Result  (cost=14091293.77..14091509.28 rows=821 width=1451) (actual time=405066.145..405100.050 rows=954 loops=1)
   CTE instance_questions_with_submission
     ->  GroupAggregate  (cost=14071895.85..14072208.74 rows=7362 width=104) (actual time=404937.742..404940.481 rows=520 loops=1)
           Group Key: iq.assessment_question_id
           ->  Sort  (cost=14071895.85..14071914.26 rows=7362 width=115) (actual time=404937.700..404938.402 rows=892 loops=1)
                 Sort Key: iq.assessment_question_id
                 Sort Method: quicksort  Memory: 94kB
                 ->  Hash Left Join  (cost=11626325.88..14071422.99 rows=7362 width=115) (actual time=401782.800..404936.374 rows=892 loops=1)
                       Hash Cond: (iq.last_grader = lgu.user_id)
                       ->  Hash Left Join  (cost=11623152.78..14067436.56 rows=7362 width=70) (actual time=401661.510..404813.135 rows=892 loops=1)
                             Hash Cond: (iq.assigned_grader = agu.user_id)
                             ->  Hash Semi Join  (cost=11619979.67..14063522.13 rows=7362 width=25) (actual time=401536.980..404686.340 rows=892 loops=1)
                                   Hash Cond: (iq.id = v.instance_question_id)
                                   ->  Nested Loop  (cost=0.99..2153571.98 rows=139032 width=33) (actual time=0.024..8.659 rows=912 loops=1)
                                         ->  Index Scan using assessment_questions_assessment_id_idx on assessment_questions aq_1  (cost=0.42..4436.46 rows=1213 width=8) (actual time=0.012..1.138 rows=954 loops=1)
                                               Index Cond: (assessment_id = 2321757)
                                         ->  Index Scan using instance_questions_assessment_question_id_assessment_instan_key on instance_questions iq  (cost=0.56..1766.27 rows=548 width=33) (actual time=0.003..0.005 rows=1 loops=954)
                                               Index Cond: (assessment_question_id = aq_1.id)
                                   ->  Hash  (cost=10413224.18..10413224.18 rows=73554520 width=8) (actual time=401518.208..401518.217 rows=73249362 loops=1)
                                         Buckets: 131072  Batches: 1024  Memory Usage: 3888kB
                                         ->  Hash Join  (cost=6281709.83..10413224.18 rows=73554520 width=8) (actual time=128499.395..333874.842 rows=73809123 loops=1)
                                               Hash Cond: (s.variant_id = v.id)
                                               ->  Index Only Scan using submissions_variant_id_idx on submissions s  (cost=0.57..3097469.30 rows=73554520 width=8) (actual time=0.009..66171.853 rows=73809123 loops=1)
                                                     Heap Fetches: 9307506
                                               ->  Hash  (cost=5333614.56..5333614.56 rows=54542056 width=16) (actual time=128493.055..128493.058 rows=56596648 loops=1)
                                                     Buckets: 131072  Batches: 1024  Memory Usage: 3609kB
                                                     ->  Seq Scan on variants v  (cost=0.00..5333614.56 rows=54542056 width=16) (actual time=0.027..71731.830 rows=56596648 loops=1)
                             ->  Hash  (cost=1671.38..1671.38 rows=70538 width=45) (actual time=124.441..124.443 rows=71474 loops=1)
                                   Buckets: 65536  Batches: 2  Memory Usage: 3302kB
                                   ->  Seq Scan on users agu  (cost=0.00..1671.38 rows=70538 width=45) (actual time=0.014..60.221 rows=71474 loops=1)
                       ->  Hash  (cost=1671.38..1671.38 rows=70538 width=45) (actual time=121.199..121.202 rows=71474 loops=1)
                             Buckets: 65536  Batches: 2  Memory Usage: 3302kB
                             ->  Seq Scan on users lgu  (cost=0.00..1671.38 rows=70538 width=45) (actual time=0.005..56.715 rows=71474 loops=1)
   CTE open_instances
     ->  Aggregate  (cost=1225.43..1225.44 rows=1 width=8) (actual time=0.046..0.049 rows=1 loops=1)
           ->  Index Scan using assessment_instances_assessment_id_user_id_number_key on assessment_instances ai  (cost=0.56..1224.91 rows=208 width=0) (actual time=0.043..0.044 rows=0 loops=1)
                 Index Cond: (assessment_id = 2321757)
                 Filter: open
                 Rows Removed by Filter: 24
   ->  Sort  (cost=17859.60..17861.65 rows=821 width=1419) (actual time=405063.532..405064.314 rows=954 loops=1)
         Sort Key: aq.number
         Sort Method: quicksort  Memory: 338kB
         ->  WindowAgg  (cost=17805.49..17819.85 rows=821 width=1419) (actual time=405059.716..405062.343 rows=954 loops=1)
               ->  Sort  (cost=17805.49..17807.54 rows=821 width=1411) (actual time=405059.701..405060.425 rows=954 loops=1)
                     Sort Key: ag.number
                     Sort Method: quicksort  Memory: 322kB
                     ->  Nested Loop Left Join  (cost=11524.59..17765.75 rows=821 width=1411) (actual time=405044.506..405058.547 rows=954 loops=1)
                           ->  Nested Loop  (cost=11524.59..17749.32 rows=821 width=1403) (actual time=405044.451..405054.026 rows=954 loops=1)
                                 ->  Hash Right Join  (cost=11524.17..11699.20 rows=821 width=1399) (actual time=405044.417..405049.602 rows=954 loops=1)
                                       Hash Cond: (iqs.assessment_question_id = aq.id)
                                       ->  CTE Scan on instance_questions_with_submission iqs  (cost=0.00..147.24 rows=7362 width=104) (actual time=404937.747..404941.324 rows=520 loops=1)
                                       ->  Hash  (cost=11513.91..11513.91 rows=821 width=1303) (actual time=106.657..106.664 rows=954 loops=1)
                                             Buckets: 1024  Batches: 1  Memory Usage: 213kB
                                             ->  Hash Join  (cost=4448.73..11513.91 rows=821 width=1303) (actual time=72.397..105.577 rows=954 loops=1)
                                                   Hash Cond: (q.id = aq.question_id)
                                                   ->  Seq Scan on questions q  (cost=0.00..6916.94 rows=56470 width=59) (actual time=0.009..59.394 rows=56476 loops=1)
                                                         Filter: (deleted_at IS NULL)
                                                         Rows Removed by Filter: 11018
                                                   ->  Hash  (cost=4436.46..4436.46 rows=981 width=1244) (actual time=2.195..2.197 rows=954 loops=1)
                                                         Buckets: 1024  Batches: 1  Memory Usage: 150kB
                                                         ->  Index Scan using assessment_questions_assessment_id_idx on assessment_questions aq  (cost=0.42..4436.46 rows=981 width=1244) (actual time=0.022..1.254 rows=954 loops=1)
                                                               Index Cond: (assessment_id = 2321757)
                                                               Filter: (deleted_at IS NULL)
                                 ->  Index Scan using alternative_groups_pkey on alternative_groups ag  (cost=0.42..7.37 rows=1 width=12) (actual time=0.002..0.002 rows=1 loops=954)
                                       Index Cond: (id = aq.alternative_group_id)
                           ->  CTE Scan on open_instances oi  (cost=0.00..0.02 rows=1 width=8) (actual time=0.001..0.002 rows=1 loops=954)
 Planning Time: 2.398 ms
 Execution Time: 405101.983 ms
(68 rows)
```

### PR DESCRIPTION
**Pull request by mwest1066**
Fixes #6152 

This reduces the query execution time in #6152 from 2 minutes to 80 milliseconds.

The key change here was to move from the EXISTS sub-query over variants+submissions to JOINing over variants+submissions and then using DISTINCT to select one row per instance question.

I also moved the "only select instance questions with submissions" part of the query into its own separate CTE at the top. I don't think this was necessary but it made it easier to explore what was going on.

I don't understand why the query planner has trouble with the EXISTS sub-query, but I do personally find the new query to be "safer" in the sense that it's just a big sequence of JOINs that I know the query planner can handle without trouble.

## Bad CTE that uses a sequential scan:

```sql
selected_instance_questions AS (
    SELECT
        iq.*
    FROM
        assessment_questions aq
        JOIN instance_questions iq ON (iq.assessment_question_id = aq.id)
    WHERE aq.assessment_id = $assessment_id
          AND EXISTS(SELECT 1
                     FROM variants AS v JOIN submissions AS s ON (s.variant_id = v.id)
                     WHERE v.instance_question_id = iq.id)
),
```

## Good CTE that only uses index scans:

```sql
selected_instance_questions AS (
    SELECT DISTINCT ON (iq.id)
        iq.*
    FROM
        assessment_questions aq
        JOIN instance_questions iq ON (iq.assessment_question_id = aq.id)
        JOIN variants AS v ON (v.instance_question_id = iq.id)
        JOIN submissions AS s ON (s.variant_id = v.id)
    WHERE aq.assessment_id = $assessment_id
),
```

### CODE REVIEW

File: pages/instructorAssessmentManualGrading/assessment/assessment.sql [hunk 1]
```diff
@@ -9,14 +20,11 @@ WITH instance_questions_with_submission AS (
         JSONB_AGG(DISTINCT jsonb_build_object('user_id', agu.user_id, 'name', agu.name, 'uid', agu.uid)) FILTER (WHERE iq.requires_manual_grading AND iq.assigned_grader IS NOT NULL) AS assigned_graders,
         JSONB_AGG(DISTINCT jsonb_build_object('user_id', lgu.user_id, 'name', lgu.name, 'uid', lgu.uid)) FILTER (WHERE iq.last_grader IS NOT NULL) AS actual_graders
     FROM
-        assessment_questions aq
+        selected_assessment_questions aq
```
Comment (nwalters512) [inline pages/instructorAssessmentManualGrading/assessment/assessment.sql:23]: I'm probably missing something obvious, but this one is `selected_assessment_questions`, whereas the first CTE is now named `selected_instance_questions`? I'd also expect the `LEFT JOIN instance_questions_with_submission iqs` in the final `SELECT` at the end of this whole query to change.

Comment (mwest1066) [reply pages/instructorAssessmentManualGrading/assessment/assessment.sql]: Ugh, thanks, this is what happens when I manually copy bits from my working test query. Fixed in 25986610f8734f72d4edf1c352a9693dbf6de75b

We don't need to change the final `LEFT JOIN instance_questions_with_submission iqs` because this new query still computes exactly the same `instance_questions_with_submission` CTE, it just does it more efficiently. Or am I misunderstanding what you mean?

Comment (nwalters512) [reply pages/instructorAssessmentManualGrading/assessment/assessment.sql]: And *this* is what happens when I review PRs too early in the morning 😂 you're absolutely correct, ignore that second part.

Comment (mwest1066) [reply pages/instructorAssessmentManualGrading/assessment/assessment.sql]: Hahaha, between the two of us we are almost managing to have one functioning brain.

File: pages/instructorAssessmentManualGrading/assessment/assessment.sql [hunk 2]
```diff
@@ -1,5 +1,16 @@
 -- BLOCK select_questions_manual_grading
-WITH instance_questions_with_submission AS (
+WITH
+selected_instance_questions AS (
+    SELECT DISTINCT ON (iq.id)
+        iq.*
```
Comment (nwalters512) [inline pages/instructorAssessmentManualGrading/assessment/assessment.sql:5]: With the whole "CTEs are optimization boundaries" thing, would we benefit from being more selective with which columns we actually read here? I'll admit I don't have a great understanding of how Postgres is actually executing this.

Comment (mwest1066) [reply pages/instructorAssessmentManualGrading/assessment/assessment.sql:5]: My understanding is that it is materializing the CTE (storing it in a temporary table) so it probably _would_ be more efficient, as you say.

I think @jonatanschroeder is working on an alternative fix, so let me wait on that before I mess around with this one any further.

Comment (jonatanschroeder) [reply pages/instructorAssessmentManualGrading/assessment/assessment.sql:5]: In essence this entire subquery can be replaced with checking if status is different than unanswered. The status is set to unanswered on insert (default), and then changed to saved when a submission is created, and never changed back to unanswered. The only difference would be if there were a way to delete submissions, which I don't think there is at this point.

File: pages/instructorAssessmentManualGrading/assessment/assessment.sql [hunk 3]
```diff
@@ -10,13 +21,10 @@ WITH instance_questions_with_submission AS (
         JSONB_AGG(DISTINCT jsonb_build_object('user_id', lgu.user_id, 'name', lgu.name, 'uid', lgu.uid)) FILTER (WHERE iq.last_grader IS NOT NULL) AS actual_graders
     FROM
         assessment_questions aq
-        JOIN instance_questions iq ON (iq.assessment_question_id = aq.id)
+        JOIN selected_instance_questions iq ON (iq.assessment_question_id = aq.id)
         LEFT JOIN users agu ON (agu.user_id = iq.assigned_grader)
         LEFT JOIN users lgu ON (lgu.user_id = iq.last_grader)
     WHERE aq.assessment_id = $assessment_id
```
Comment (jonatanschroeder) [inline pages/instructorAssessmentManualGrading/assessment/assessment.sql:27]:
```suggestion
        JOIN instance_questions iq ON (iq.assessment_question_id = aq.id)
        LEFT JOIN users agu ON (agu.user_id = iq.assigned_grader)
        LEFT JOIN users lgu ON (lgu.user_id = iq.last_grader)
    WHERE aq.assessment_id = $assessment_id
      AND iq.status != 'unanswered'
```
and get rid of the `selected_instance_questions` subquery altogether.

Comment (mwest1066) [reply pages/instructorAssessmentManualGrading/assessment/assessment.sql]: Excellent point! Done in 635fbae596a69024ab112ff4f9468eb2dd241f88

**Review by jonatanschroeder — APPROVED** [review]
