### PR TITLE
Java grader: support for output based on TestReporter

### LINKED ISSUE #9388: Java grader: allow instructor to set the output of individual tests
As per discussion with @nicholasdehnen. Currently the Java grader only lists additional output if a test fails, and only the string representation of the exception (typically an assertion exception) that caused the test to fail. However occasionally an instructor may want to provide additional context to a test, including what was tested and what was the result. There should be a mechanism for setting the description/message/output of a test, preferably in a way that only allows instructors (not students) to access them.

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Resolves #9388. Uses TestReporter as a means to publish output from the test.

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
@nicholasdehnen could you (unofficially) review this and let me know if it works for you?

File: graders/java/JUnitAutograder.java [hunk 1]
```diff
@@ -157,6 +162,26 @@ public synchronized void dynamicTestRegistered(TestIdentifier test) {
...
+
+        for (Map.Entry<String, String> pair : entry.getKeyValuePairs().entrySet()) {
+            // "value" is the key used by TestReporter if only a value is provided (without a key)
+            // https://junit.org/junit5/docs/5.9.1/api/org.junit.jupiter.api/org/junit/jupiter/api/TestReporter.html#publishEntry(java.lang.String)
+            if (pair.getKey().equals("value"))
+                autograderTest.output += pair.getValue() + "\n";
+            else
+                autograderTest.output += pair.getKey() + ": " + pair.getValue() + "\n";
+        }
+    }
```
Comment (nwalters512) [inline graders/java/JUnitAutograder.java:183]: Nit (this is how it'd be in JS, maybe it's foolish to aim for consistency with that though):

```suggestion
        if (!test.isTest()) {
            return;
        }

        AutograderTest autograderTest = tests.get(test);
        if (autograderTest == null) {
            return;
        }

        for (Map.Entry<String, String> pair : entry.getKeyValuePairs().entrySet()) {
            // "value" is the key used by TestReporter if only a value is provided (without a key)
            // https://junit.org/junit5/docs/5.9.1/api/org.junit.jupiter.api/org/junit/jupiter/api/TestReporter.html#publishEntry(java.lang.String)
            if (pair.getKey().equals("value")) {
                autograderTest.output += pair.getValue() + "\n";
            } else {
                autograderTest.output += pair.getKey() + ": " + pair.getValue() + "\n";
            }
        }
    }
```

File: graders/java/JUnitAutograder.java [hunk 2]
```diff
@@ -98,9 +99,9 @@ public void runTests() throws UngradableException {
 
         for (String classSrcName : testClasses) {
             String className = classSrcName
-                .replaceFirst("^/grade/tests/junit/", "")
-                .replaceFirst("\\.java$", "")
-                .replaceAll("/", ".");
+                    .replaceFirst("^/grade/tests/junit/", "")
+                    .replaceFirst("\\.java$", "")
+                    .replaceAll("/", ".");
```
Comment (nwalters512) [inline graders/java/JUnitAutograder.java:104]: Maybe this is just my lack of familiarity with Java conventions, but why is this indented 8 spaces when everything is indented 4?

File: docs/java-grader/index.md [hunk 3]
```diff
@@ -108,6 +108,22 @@ import org.prairielearn.autograder.AutograderInfo;
...
+    @DisplayName("Test addition of values 1 and 1")
+    void addition(TestReporter reporter) {
+        // Produce a single line of output
+        reporter.publishEntry("Calculating the addition of 1 and 1, which should result in 2");
+        // Alternatively, multiple key-value entries may be provided instead
+        reporter.publishEntry("TEST", "Adding 1 plus 1");
+        reporter.publishEntry("EXPECTED", "2");
+        reporter.publishEntry("RESULT", calculator.add(1, 1).toString());
+        assertEquals(2, calculator.add(1, 1));
+    }
```
Comment (nwalters512) [inline docs/java-grader/index.md:124]: I don't think this needs to be indented 4 spaces.

**Review by nwalters512 — APPROVED** [review]
Several formatting nits, nothing I'll block on.

File: graders/java/JUnitAutograder.java (hunk 1 above)
Comment (jonatanschroeder) [reply graders/java/JUnitAutograder.java:183]: I'm using [checkstyle](https://checkstyle.org/contributing.html#Build) for style, and this is not enforced. I'd prefer to keep it as is.

File: docs/java-grader/index.md (hunk 3 above)
Comment (jonatanschroeder) [reply docs/java-grader/index.md:124]:
```suggestion
@Test
@DisplayName("Test addition of values 1 and 1")
void addition(TestReporter reporter) {
    // Produce a single line of output
    reporter.publishEntry("Calculating the addition of 1 and 1, which should result in 2");
    // Alternatively, multiple key-value entries may be provided instead
    reporter.publishEntry("TEST", "Adding 1 plus 1");
    reporter.publishEntry("EXPECTED", "2");
    reporter.publishEntry("RESULT", calculator.add(1, 1).toString());
    assertEquals(2, calculator.add(1, 1));
}
```

File: graders/java/JUnitAutograder.java (hunk 1 above)
Comment (nwalters512) [reply graders/java/JUnitAutograder.java:183]: https://dwheeler.com/essays/apple-goto-fail.html 😉 🤷

Comment (jonatanschroeder) [reply graders/java/JUnitAutograder.java:183]: Seems like I misconfigured checkstyle, I checked the documentation and it's supposed to enforce that too. Updates coming.

Comment (jonatanschroeder) [reply graders/java/JUnitAutograder.java]: Turns out getting this configured in VSCode is harder than I anticipated. I also don't want to get into the complexities of setting up Eclipse or IntelliJ for just two files, and Emacs does not support this. The checkstyle CLI is pretty clumsy. I added the braces you suggested and I'll take a bit of time to figure out a better way to handle style.

File: graders/java/JUnitAutograder.java (hunk 2 above)
Comment (jonatanschroeder) [reply graders/java/JUnitAutograder.java:104]: This is usually the case when it's the continuation of a long line/statement instead of a block indentation.

File: graders/java/JUnitAutograder.java (hunk 1 above)
Comment (jonatanschroeder) [reply graders/java/JUnitAutograder.java]: I managed to get checkstyle working, and it found a few other issues that I fixed, such as adding final modifiers where appropriate, using braces in all while/for/if blocks, and removing unnecessary imports. I ignored concerns about line lengths and missing javadocs.

File: graders/java/JUnitAutograder.java [hunk 4]
```diff
@@ -176,49 +207,54 @@ public synchronized void executionFinished(TestIdentifier test, TestExecutionRes
...
         if (maxPoints - testMaxPoints > 0.01) {
             resultsTests.add(new AutograderTest("Incomplete tests", maxPoints - testMaxPoints,
-                                                "The number of points achieved by the autograder tests was not enough to reach \n" +
-                                                "the full amount of tests required for full marks. This is typically caused by \n" +
-                                                "failing early tests, or by an early autograder crash.")
-                             .toJson());
+                    """
+                            The number of points achieved by the autograder tests was not enough to reach\s
+                            the full amount of tests required for full marks. This is typically caused by\s
+                            failing early tests, or by an early autograder crash.""")
```
Comment (nwalters512) [inline graders/java/JUnitAutograder.java:256]: TIL about triple-quote strings in Java! In case anyone else has this question: leading spaces are stripped in this case. I found this helpful to understand how this works: https://www.baeldung.com/java-text-blocks

**Review by nwalters512 — APPROVED** [review]
This is somewhat of a rubber stamp given my lack of Java muscle memory at this point, though I didn't see anything that looked glaringly wrong.

**Comment by jonatanschroeder** [comment]
I have had this image active in one of my assessments (with a pretty complex JUnit class), with my students submitting dozens of cases without issues, so I'm confident that this is safe without a review from another Java reviewer. I'm merging.
