### PR TITLE
Fix reference to encoded data in values retrieved via web socket

### LINKED ISSUE #8621: Fix rendering question footer asynchronously
When rendering the question footer outside of a normal request/response cycle, such as during external grading live updates, we've observed some errors. Namely, `submitRateFooter.ejs` fails to render because `encoded_data` is not defined. This happens because we only attach `encoded_data` to `res.locals` during normal requests:

https://github.com/PrairieLearn/PrairieLearn/blob/7b742611b43f4d0ac01ad5aedf8ec806ee212b4d/apps/prairielearn/src/server.js#L140

Note that this is only reproducible for questions where rate-limiting is in effect; otherwise this part of the question footer doesn't render at all.

We should try to add Sentry error handling here so that we can more quickly catch future problems:

https://github.com/PrairieLearn/PrairieLearn/blob/7b742611b43f4d0ac01ad5aedf8ec806ee212b4d/apps/prairielearn/src/lib/externalGradingSocket.js#L69

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Resolves #8621.

### CODE REVIEW

File: apps/prairielearn/src/lib/externalGradingSocket.js [hunk 1]
```diff
@@ -32,7 +33,14 @@ module.exports.connection = function (socket) {
     socket.join(`variant-${msg.variant_id}`);
 
     module.exports.getVariantSubmissionsStatus(msg.variant_id, (err, submissions) => {
-      if (ERR(err, (err) => logger.error('Error getting variant submissions status', err))) return;
+      if (
+        ERR(err, (err) => {
+          logger.error('Error getting variant submissions status', err);
+          Sentry.captureException(err);
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/lib/externalGradingSocket.js:39]: I followed the procedure used in other parts of the code regarding Sentry, I hope this is correct. I don't know how to test this. To confirm, would this require additional initialization as well, since it's not part of a "normal request" flow? I see that cron doesn't require the init, so I assume this one doesn't either.

Comment (nwalters512) [reply apps/prairielearn/src/lib/externalGradingSocket.js:39]: Yep, this is all you have to do - Sentry uses a global singleton-ish instance.

**Review by nwalters512 — APPROVED** [review]
