### PR TITLE
Fix Issues tab link for questions with spaces in QID

### LINKED ISSUE #13610: Issue with Issues in PL for questions with spaces in path
### Details

We have found what seems to be a bug in PL. If there is a space in the path of a question then PL can not find the issue except when you look at all open issues. That is if you go to the assignment that that the question was from it will have a flag that there is an issue but if you click on it you don’t see the issue. Issue #788213 here is an example of this problem. You see it here https://us.prairielearn.com/pl/course_instance/192442/instructor/course_admin/issues but not if you click here https://us.prairielearn.com/pl/course_instance/192442/instructor/assessment/2613653/questions .

### PR DESCRIPTION
**Pull request by jonatanschroeder**
# Description

As reported on Slack. When a QID has a space in its name, the "Issues" tab will have the proper issue count, but opening it will not show issues associated to that QID. This is because the link generates a query without escaping the QID, which causes the query to be misinterpreted. The same issue is found in other issue badges, such as those in the assessment questions page, the questions table page, the assessments page, or the assessment switcher modal.

This PR uses the same library used in the issues page to parse a search string to also escape it appropriately. This should take care of weird characters in the QID, such as spaces, quotes, colons, commas, and any other character that the search-string library has a special meaning for.

Resolves #13610.

# Testing

Using the terminal, rename the QID of some test question to a string that includes spaces and/or quotes (note that you can't use the UI for this, as the UI enforces a QID pattern that doesn't include spaces). Then open the question and create an issue for it. Then click on the issues tab, it should open the issues page and show the issue you created. Similar for other badges pointing to the same question.

### CODE REVIEW

File: apps/prairielearn/assets/scripts/lib/questionsTable.tsx [hunk 1]
```diff
@@ -94,17 +95,16 @@ onDocumentReady(() => {
 
     text += html`
       <a class="formatter-data" href="${urlPrefix}/question/${question.id}/preview">
-        ${prefix}${question.qid}
-      </a>
+        ${prefix}${question.qid}</a
+      >
```
Comment (jonatanschroeder) [inline apps/prairielearn/assets/scripts/lib/questionsTable.tsx:99]: Drive-by fix: the space at the end of the QID becomes part of the link, which looks weird when there is an issue badge.

File: apps/prairielearn/src/lib/uri-util.shared.ts [hunk 2]
```diff
@@ -13,3 +15,19 @@ export function encodePathNoNormalize(originalPath: string): string {
     return '';
   }
 }
+
+/**
+ * Encodes a set of query parameters into a URI component string to be used with search query strings.
+ * @param entries Record of query parameter names and values
+ * @returns Encoded query parameter string
+ */
+export function encodeQueryParams(entries: Record<string, string | null | undefined>): string {
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/uri-util.shared.ts]: Nit: we (and a lot of the web ecosystem) use "query params" to mean generically the key/values at the end of the URL. This is not using it in that sense, this is very specific to this `search-string` library.

Should we call this something like `encodeSearchString` instead?

File: apps/prairielearn/src/lib/uri-util.test.ts [hunk 3]
```diff
@@ -51,4 +51,30 @@ describe('uri-util', () => {
...
+      const params = { qid: 'abc123/def456', aid: 'A1/B2/C3' };
+      const result = encodeQueryParams(params);
+      assert.equal(decodeURIComponent(result), 'qid:abc123/def456 aid:A1/B2/C3');
+    });
+
+    it('encodes qid/aid with quotes', () => {
+      const params = { qid: 'abc"def', aid: 'A1"B2' };
+      const result = encodeQueryParams(params);
+      assert.equal(decodeURIComponent(result), 'qid:abc\\"def aid:A1\\"B2');
+    });
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/uri-util.test.ts:66]: I thought of this case when prompting Copilot, we currently have zero questions that have quotes in them (thank goodness). It's fine/nice that we handle this case though.

File: apps/prairielearn/src/lib/uri-util.shared.ts (hunk 2 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/lib/uri-util.shared.ts]: Done in 17ca6d0633cc973c1010e98fbcc87ed6e040bbda. This was originally a placeholder, but I ended up focusing on functionality and the name stuck.

File: apps/prairielearn/src/lib/uri-util.test.ts (hunk 3 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/lib/uri-util.test.ts:66]: My thought process was mainly to ensure that we consider everything that search-string considers a special character (which includes commas, which I didn't originally anticipate), and thus relying on search-string's own encoding to avoid anything else that may come in the future. The quotes came as bonus.
