### PR TITLE
Agentic question generation

### LINKED ISSUE #11454: Ensure revise button stays disabled when revision is in-flight
Steps to reproduce the issue here:

- On the AI question generation editor page, submit a revision.
- While the revision is in progress, edit the revision textbox.
- Observe that the "revise" button becomes active again.

We should probably just disable the textbox as a whole while the revision is in progress.

### LINKED ISSUE #11456: Improve or change chat interface in AI question generation
The current "chat" interface used in AI question generation doesn't actually follow the behavior that people have come to expect from LLM chat interfaces. Namely, you can't _actually_ have a conversation with the LLM: you can just issue commands, and those commands are expected to produce responses that contain updates to the question HTML or Python. You won't ever see actual responses from the LLM.

In user testing, this has caused some issues. People will try to say things like "thank you" or ask followup questions, neither of which will produce new HTML or Python, which in turn is interpreted as an error by the revision process.

We should consider if a chat interface is actually the way to go. I sort of like chat, as in theory it means you can ask questions to clarify your understanding of something, or to ask to revise something that might not even have been present in the original prompt. But it could be that we're better off with a UI that just gives a single textbox for a prompt that you can just keep editing and regenerating with.

### LINKED ISSUE #13551: Agentic AI question generation
This tracks progress towards an agentic AI question generation system.

### PR DESCRIPTION
**Pull request by nwalters512**
# Description

This is an exploratory rewrite of our AI question generation process to use an agentic loop instead of RAG + manual multi-shot reprompting.

Closes #13551, closes #11456, closes #11454

Remaining tasks for an MVP:

- [x] Fix layout/scrolling
- [x] Fix streaming on creation
- [x] Streaming rendering of text deltas
Special-case creation workflow to hide empty questions/files
- [x] Prompt improvements
  - [x] Differentiating between "question exists" and "editing existing question"
- [x] Teach client to render Markdown
- [x] Show message where history is lost (old prompts are present, new ones are not)
- [x] Auto-refresh of preview to new variant after response
- [x] Add "stop generating" functionality
  - This is sort of a substitute for better error handling
- [x] Updated rate limiting: don't check if we would go over, check if we have
- [x] Context management
  - Keep last 5 interactions?
- [x] Keep editor tabs in sync without requiring a page reload
- [x] Remove course settings tabs from the top of the generation page
- [x] Show side nav, force it to be collapsed by default
- [x] Tell it which Python libraries are available (or make a tool call to get `requirements.txt`)
- [x] Add thinking bar/spinner
- [x] De-emphasize tool calls and thinking
  - [x] Consider something like this: https://ai-sdk.dev/elements/components/reasoning
- [x] Updated usage/cost tracking (needs multi-model support)
  - [x] Support multiple models, including tracking models in the database to allow switching models mid-conversation
  - [x] Account for cached/uncached input tokens and reasoning/other output tokens
- [x] Add support for `<pl-answer-panel>`: https://github.com/PrairieLearn/PrairieLearn/pull/13930
- [x] Change toggle below input to "Refresh question preview after changes"
- [x] Redirect a missing draft ("Draft question not found") back to the main drafts page: https://github.com/PrairieLearn/PrairieLearn/pull/13947
- [x] Render user prompts without markdown formatting, a la ChatGPT
- [x] Improve context management by adding `include_in_context` boolean to messages

# Testing

All functionality has been manually tested.

### CODE REVIEW

**Comment by reteps** [comment]
Excited for this!

File: apps/prairielearn/src/lib/editors.ts [hunk 1]
```diff
@@ -509,7 +509,8 @@ export abstract class Editor {
     const idSplit = id.split(path.sep);
 
     // Start deleting subfolders in reverse order
-    const reverseFolders = idSplit.slice(0, -1).toReversed();
+    // eslint-disable-next-line unicorn/no-array-reverse
+    const reverseFolders = idSplit.slice(0, -1).reverse();
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/editors.ts]: This was needed because our various `tsconfig` files don't agree on `lib`:

- `apps/prairielearn/assets/scripts/tsconfig.json` (for client-side code) uses `ES2022`
- `packages/tsconfig/tsconfig.base.json` (default, ends up being used for server-side code) uses `ES2024`

`toReversed()` is part of `ES2023`, and thus can't be used in code that's type-checked under client rules; but we have a lint rule that mandates that `toReversed()` be used instead of `reversed()`. Something has to change here.

File: apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql [hunk 2]
```diff
@@ -0,0 +1,33 @@
+-- TODO: remove before merging.
+DROP TABLE IF EXISTS ai_question_generation_parts;
+
+DROP TABLE IF EXISTS ai_question_generation_messages;
+
+DROP TYPE IF EXISTS enum_ai_question_generation_message_role;
+
+DROP TYPE IF EXISTS enum_ai_question_generation_message_status;
```
Comment (nwalters512) [inline apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql]: Adding a review comment so I don't forget about this.

File: apps/prairielearn/src/lib/editors.ts (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/editors.ts]: Discussed today: we'll drop the lint rule that forces `toReversed()` and friends.

Comment (nwalters512) [reply apps/prairielearn/src/lib/editors.ts]: We also think we can unify to `ES2022` on both server and client.

Comment (nwalters512) [reply apps/prairielearn/src/lib/editors.ts]: This will be resolved by https://github.com/PrairieLearn/PrairieLearn/pull/13561.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.html.tsx [hunk 3]
```diff
@@ -1,435 +1,99 @@
...
-          </Hydrate>,
-        )}
-      </div>
-    </div>
-  `;
-}
+  const cancelCsrfToken = generateCsrfToken({
+    url: `${resLocals.urlPrefix}/ai_generate_editor/${question.id}/chat/cancel`,
+    authnUserId: resLocals.authn_user.id,
+  });
```
Comment (nwalters512) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.html.tsx]: We should take advantage of path prefix CSRF tokens here.

File: apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql [hunk 4]
```diff
@@ -0,0 +1,39 @@
+CREATE TYPE enum_ai_question_generation_message_role AS ENUM('system', 'user', 'assistant');
```
Comment (nwalters512) [inline apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql]: Is `system` in use? If not, remove. If so, reconcile with constraints below.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.html.tsx (hunk 3 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.html.tsx]: Done in 0ad15d9.

File: apps/prairielearn/src/migrations/20260204011658_ai_question_generation__revamp.sql [hunk 5]
```diff
@@ -0,0 +1,39 @@
...
+CREATE TYPE enum_ai_question_generation_message_status AS ENUM(
+  'pending',
+  'streaming',
+  'completed',
+  'errored',
+  'canceled'
+);
+
+CREATE TABLE IF NOT EXISTS ai_question_generation_messages (
+  id BIGSERIAL PRIMARY KEY,
```
Comment (reteps) [inline apps/prairielearn/src/migrations/20260204011658_ai_question_generation__revamp.sql:6]: One thought I had for threads was to have a 'parent_message_id' which would allow for hierarchical structures. We want a very flexible data model here i feel like. Nothing actionable though.

File: apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql (hunk 4 above)
Comment (reteps) [inline apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql]: Is there any reason to differentiate a message from the ai to the user vs the ai to the ai (tool call)?

File: database/tables/ai_question_generation_messages.pg [hunk 6]
```diff
@@ -0,0 +1,26 @@
+columns
```
Comment (reteps) [inline database/tables/ai_question_generation_messages.pg:1]: If we ever need to delete messages, will those be hard deleted? I don't see `deleted_at`.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts [hunk 7]
```diff
@@ -0,0 +1,675 @@
+import assert from 'node:assert';
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:5]: consider a file-level comment explaining that this is the core logic of the agentic question generation.

File: apps/prairielearn/src/lib/editors.ts [hunk 8]
```diff
@@ -1661,72 +1668,107 @@ export class QuestionRenameEditor extends Editor {
...
 
-    debug(
-      `For each assessment, read/write infoAssessment.json to replace ${this.question.qid} with ${this.qid_new}`,
-    );
-    for (const assessment of assessments) {
-      assert(
-        assessment.course_instance_directory !== null,
-        'course_instance_directory is required',
+    if (qidChanging) {
+      debug(`Move files from ${oldPath} to ${newPath}`);
```
Comment (reteps) [inline apps/prairielearn/src/lib/editors.ts]: nit: consider pulling this out into a helper.

File: apps/prairielearn/src/lib/ai-util.ts [hunk 9]
```diff
@@ -47,21 +47,17 @@ export function calculateResponseCost({
...
-  const cachedInputTokens = usage.inputTokenDetails.cacheReadTokens ?? 0;
   const inputTokens = usage.inputTokenDetails.noCacheTokens ?? 0;
+  const cacheReadTokens = usage.inputTokenDetails.cacheReadTokens ?? 0;
+  const cacheWriteTokens = usage.inputTokenDetails.cacheWriteTokens ?? 0;
   const outputTokens = usage.outputTokens ?? 0;
 
-  const cachedInputTokenCost = modelPricing.cachedInput / 10 ** 6;
-  const inputTokenCost = modelPricing.input / 10 ** 6;
-  const outputTokenCost = modelPricing.output / 10 ** 6;
+  const inputCost = inputTokens * (modelPricing.input / 1e6);
```
Comment (reteps) [inline apps/prairielearn/src/lib/ai-util.ts:116]: nit: can you add a small comment about why 1e6? `// Convert from X unit to dollars`

File: apps/prairielearn/assets/stylesheets/instructorAiGenerateDraftEditor.css [hunk 10]
```diff
@@ -149,3 +113,36 @@ body,
...
+}
+
+.spinner-border-text {
+  margin: 0.1em;
+  --bs-spinner-width: 0.8em;
+  --bs-spinner-height: 0.8em;
+  --bs-spinner-border-width: 0.15em;
+}
+
+.bi-fw {
```
Comment (reteps) [inline apps/prairielearn/assets/stylesheets/instructorAiGenerateDraftEditor.css:141]: nit: should this `bi-fw` be moved out into a class we can use on other pages if needed?

File: apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts [hunk 11]
```diff
@@ -0,0 +1,58 @@
...
+import { selectQuestionById } from '../../../../models/question.js';
+import { privateProcedure } from '../../trpc.js';
+
+/**
+ * Returns base64-encoded `question.html` and `server.py` files for a question.
+ *
+ * This function does not perform any authorization checks. It's up to the caller
+ * to ensure that it's safe to call this function for a given course and question.
+ */
+export const getQuestionFiles = privateProcedure
```
Comment (reteps) [inline apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts:19]: Do we want some sort of `unsafe*` prefix for tRPC calls that are unauthorized? Or do you think this comment is sufficient.

File: apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts [hunk 12]
```diff
@@ -0,0 +1,58 @@
...
+    assert(question.course_id === course.id);
+    assert(question.qid);
+
+    const questionPath = path.join(course.path, 'questions', question.qid);
+
+    const files: Record<string, string> = {};
+
+    // In the future, we should support more than just these two files. For now,
+    // this is sufficient.
+    if (await pathExists(path.join(questionPath, 'question.html'))) {
```
Comment (reteps) [inline apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts]: In another PR, you wanted a more defensive pattern (try,catch). Any reason you didn't do that here?

Comment (reteps) [inline apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts]: nit: this could be a loop over an array

File: apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts [hunk 13]
```diff
@@ -243,50 +241,70 @@ export async function benchmarkAiQuestionGeneration({
...
         }
-        job.error('\n');
+      });
+
+      const messages = await selectAiQuestionGenerationMessages(result.question.id);
+      const userMessage = messages.at(0);
+      const assistantMessage = messages.at(-1);
+
+      if (userMessage?.role !== 'user') {
+        job.error(`No user message found for question ${result.question.id}`);
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts:268]: It only checks the first/last message, am I misunderstanding? the error messages seem a little misleading.

File: apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts [hunk 14]
```diff
@@ -323,25 +341,22 @@ export async function benchmarkAiQuestionGeneration({
...
 }: {
   model: LanguageModel;
-  originalSystemPrompt: string | null;
-  userPrompt: string;
+  userMessageContents: string;
+  assistantMessageContents: string;
   html: string;
   python: string;
 }): Promise<QuestionGenerationEvaluation | null> {
   const systemPrompt = [
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts]: Why this over a template string?

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts [hunk 15]
```diff
@@ -0,0 +1,675 @@
...
+export type QuestionGenerationUIMessage = UIMessage<
+  QuestionGenerationUIMessageMetadata,
+  UIDataTypes,
+  QuestionGenerationUIMessageTools
+>;
+
+export type QuestionGenerationToolUIPart = ToolUIPart<QuestionGenerationUIMessageTools>;
+
+function makeSystemPrompt({ isExistingQuestion }: { isExistingQuestion: boolean }) {
+  return formatPrompt([
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:209]: nit: I wonder if it makes sense to organize all our ai prompts from our codebase together, to make them easy to iterate on together.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts [hunk 16]
```diff
@@ -0,0 +1,675 @@
...
+
+  // Insert the agent's message into the `messages` table.
+  const messageRow = await queryRow(
+    sql.insert_initial_assistant_message,
+    { question_id: question.id, job_sequence_id: serverJob.jobSequenceId, model: modelId },
+    AiQuestionGenerationMessageSchema,
+  );
+
+  // Create SSE transform stream before starting background job
+  const sseStream = new JsonToSseTransformStream();
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:585]: This is a pretty low-level primitive as I understand, (e.g. https://ai-sdk.dev/docs/reference/ai-sdk-ui/create-ui-message-stream-response wraps this). This is intentional, right.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts [hunk 17]
```diff
@@ -0,0 +1,675 @@
...
+      isExistingQuestion,
+      hasCoursePermissionEdit,
+      messageId: messageRow.id,
+    });
+
+    const args = await run(async () => {
+      if (messages) {
+        // Naive context management: keep the first message and the last 10 messages.
+        // This will probably result in cache misses - this is just a simple first implementation.
+        const trimmedMessages = [messages[0], ...messages.slice(Math.max(messages.length - 10, 1))];
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts]: We discussed that this context management is a little too naive.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts [hunk 18]
```diff
@@ -0,0 +1,675 @@
...
+
+        return getErrorMessage(error);
+      },
+    });
+
+    await stream.pipeTo(sseStream.writable);
+
+    const steps = await res.steps.then(
+      (steps) => steps,
+      () => [],
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts]: Claude flagged this:

```
  1. Promise Rejections Silently Swallowed in Agent Stream Processing

  [silent-failure-hunter] agent.ts:630-640

  const steps = await res.steps.then(
    (steps) => steps,
    () => [],  // Silently converts failure to empty array
  );

  Impact: AI API failures, network issues, or memory errors are completely hidden. Users see "completed" jobs even when critical failures occurred. Token usage won't be tracked.

  Fix: Log errors in rejection handlers or propagate them
  ```

File: apps/prairielearn/src/lib/db-types.ts [hunk 19]
```diff
@@ -255,6 +271,24 @@ export const AiGradingJobSchema = z.object({
 });
 export type AiGradingJob = z.infer<typeof AiGradingJobSchema>;
 
+export const AiQuestionGenerationMessageSchema = z.object({
+  created_at: DateFromISOString,
+  id: IdSchema,
+  job_sequence_id: IdSchema.nullable(),
+  model: z.string().nullable(),
+  parts: z.array(z.any()),
```
Comment (reteps) [inline apps/prairielearn/src/lib/db-types.ts:284]: From Claude:

```
parts: z.array(z.any()) - Zero Type Safety for Message Content

  [type-design-analyzer] db-types.ts AiQuestionGenerationMessageSchema

  The parts field (the most important data - actual message content) has no schema validation. Tool calls, text, and reasoning parts are untyped.

  Fix: Create discriminated union schemas for message parts mirroring the AI SDK's UIMessage structure.
```

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts [hunk 20]
```diff
@@ -0,0 +1,675 @@
+import assert from 'node:assert';
+import fs from 'node:fs/promises';
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:6]: From Claude:

```
  Unlike aiQuestionGeneration.ts, the agent has no Sentry error tracking. Production issues won't trigger alerts.
  ```

File: apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts [hunk 21]
```diff
@@ -0,0 +1,58 @@
...
+import { IdSchema } from '@prairielearn/zod';
+
+import { selectCourseById } from '../../../../models/course.js';
+import { selectQuestionById } from '../../../../models/question.js';
+import { privateProcedure } from '../../trpc.js';
+
+/**
+ * Returns base64-encoded `question.html` and `server.py` files for a question.
+ *
+ * This function does not perform any authorization checks. It's up to the caller
```
Comment (reteps) [inline apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts]: The 'caller' in this case is the callsite that mounts this, right? I want to make sure that no one can just call this endpoint.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx [hunk 22]
```diff
@@ -121,6 +124,12 @@ const RichTextEditor = ({
   const [rawHtml, setRawHtml] = useState<string | null>(null);
   const [debugMode, setDebugMode] = useState<boolean>(false);
 
+  // Set read-only mode when generating
+  useEffect(() => {
+    // eslint-disable-next-line react-you-might-not-need-an-effect/no-pass-data-to-parent, react-you-might-not-need-an-effect/no-derived-state
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx]: I may be thinking about this wrong, but wouldn't `isGenerating` trigger a re-render of this component when it's passed? Thus this could just be set in the initial options for the editor?

File: apps/prairielearn/src/ee/models/ai-question-generation-message.ts [hunk 23]
```diff
@@ -0,0 +1,13 @@
+import { loadSqlEquiv, queryRows } from '@prairielearn/postgres';
+
+import { AiQuestionGenerationMessageSchema } from '../../lib/db-types.js';
+
+const sql = loadSqlEquiv(import.meta.url);
+
+export async function selectAiQuestionGenerationMessages(question_id: string) {
```
Comment (reteps) [inline apps/prairielearn/src/ee/models/ai-question-generation-message.ts]: pass in a full question object?

File: apps/prairielearn/src/ee/lib/context-parsers/pyproject.ts [hunk 24]
```diff
@@ -0,0 +1,34 @@
...
+let cachedPythonLibraries: string[] | null = null;
+
+export async function getPythonLibraries(): Promise<string[]> {
+  if (cachedPythonLibraries !== null) return cachedPythonLibraries;
+
+  const data = await fs.readFile(path.join(REPOSITORY_ROOT_PATH, 'pyproject.toml'), {
+    encoding: 'utf-8',
+  });
+
+  const { parse } = await import('smol-toml');
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/context-parsers/pyproject.ts]: Why inline import?

File: apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts [hunk 25]
```diff
@@ -42,18 +41,17 @@ import { RedisRateLimiter } from '../../lib/redis-rate-limiter.js';
...
 
 const sql = loadSqlEquiv(import.meta.url);
 
-// We're still using `4o` for question generation as it seems to have better
-// cost/performance characteristics. We'll revisit moving to a newer model in
-// the future.
-export const QUESTION_GENERATION_OPENAI_MODEL = 'gpt-4o-2024-11-20' satisfies OpenAIModelId;
+export type QuestionGenerationModelId = keyof (typeof config)['costPerMillionTokens'];
+
+export const QUESTION_GENERATION_OPENAI_MODEL: QuestionGenerationModelId = 'gpt-5.2-2025-12-11';
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts:51]: Should this live in `config.ts`?

File: apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts [hunk 26]
```diff
@@ -112,7 +110,7 @@ function promptPreamble(context: string): string {
   ]);
 }
 
-async function checkRender(
+export async function checkRender(
```
Comment (reteps) [inline apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts:110]: I don't like the `locals as any` typecast, can that be improved at all?

File: apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts [hunk 27]
```diff
@@ -0,0 +1,69 @@
...
+    z.object({
+      status: z.union([z.literal('success'), z.literal('error')]),
+      job_sequence_id: IdSchema,
+    }),
+  )
+  .mutation(async (opts) => {
+    const course = await selectCourseById(opts.input.course_id);
+    const question = await selectQuestionById(opts.input.question_id);
+
+    const { user, authn_user } = await selectUsers({
```
Comment (reteps) [inline apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts:39]: Why aren't we just passing authz_data here? This seems like some extra hoops to jump through.

File: apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts [hunk 28]
```diff
@@ -0,0 +1,69 @@
...
+import { QuestionRenameEditor } from '../../../../lib/editors.js';
+import { selectCourseById } from '../../../../models/course.js';
+import { selectQuestionById } from '../../../../models/question.js';
+import { privateProcedure, selectUsers } from '../../trpc.js';
+
+export const renameQuestion = privateProcedure
+  .input(
+    z.object({
+      // Context.
+      course_id: IdSchema,
```
Comment (reteps) [inline apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts:16]: I was personally thinking that tRPC would deal with camelCase. Thoughts?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx [hunk 29]
```diff
@@ -0,0 +1,758 @@
...
+    part.state === 'approval-requested' ||
+    part.state === 'approval-responded' ||
+    part.state === 'output-denied'
+  ) {
+    // We don't currently use or support these states.
+    return null;
+  }
+
+  const statusText = run(() => {
+    if (part.type === 'tool-getElementDocumentation') {
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: Can we use a switch case here? And maybe point an agent at if we can shrink this implementation at all (e.g. wrap in `<span>` at the end)

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx [hunk 30]
```diff
@@ -0,0 +1,758 @@
...
+        return <span>Error reading available Python libraries</span>;
+      }
+    }
+
+    return <span>{toolName}</span>;
+  });
+
+  return (
+    <ToolCallStatus state={part.state} statusText={statusText}>
+      {/* <>
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: do you want some sort of debug flag?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx [hunk 31]
```diff
@@ -0,0 +1,758 @@
...
+            {' '}
+            View job logs{' '}
+          </a>
+        )}
+      </div>
+    );
+  });
+}
+
+class RateLimitError extends Error {}
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx:450]: A docstring about this would be good, it also could be pulled into a lib/somewhere more noticable

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx [hunk 32]
```diff
@@ -0,0 +1,758 @@
...
+
+function useShowSpinner({
+  status,
+  messages,
+}: {
+  status: string;
+  messages: QuestionGenerationUIMessage[];
+}) {
+  const [showSpinner, setShowSpinner] = useState(false);
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: Again, won't a prop change trigger a re-render of the component/hook?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx [hunk 33]
```diff
@@ -0,0 +1,758 @@
...
+    // Currently, we assume one chat per question. This should change in the future.
+    id: questionId,
+    messages: initialMessages,
+    resume: true,
+    transport: new DefaultChatTransport({
+      api: `${urlPrefix}/ai_generate_editor/${questionId}/chat`,
+      headers: { 'X-CSRF-Token': chatCsrfToken },
+      prepareReconnectToStreamRequest: ({ id }) => {
+        return {
+          api: `${urlPrefix}/ai_generate_editor/${id}/chat/stream`,
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx:535]: We have a growing collection of url helpers in `lib/client/url.ts`, consider adding to that

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx [hunk 34]
```diff
@@ -0,0 +1,758 @@
...
+  const stickToBottom = useStickToBottom({
+    initial: 'smooth',
+    // The experience with animated collapsible sections is currently janky.
+    // Ideally a fix to this comment would allow us to improve things:
+    // https://github.com/stackblitz-labs/use-stick-to-bottom/issues/19#issuecomment-3457630069
+    resize: 'smooth',
+  });
+
+  // Chat width resizing
+  useEffect(() => {
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx:622]: I think I wrote this, but we should really consider extracting this out or refactoring away from this DOM-oriented approach IMO.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationEditor.tsx [hunk 35]
```diff
@@ -0,0 +1,136 @@
...
+  const [isGenerating, setIsGenerating] = useState(false);
+  const [questionFiles, setQuestionFiles] = useState(initialQuestionFiles);
+  const [hasUnsavedChanges, setHasUnsavedChanges] = useState(false);
+  const newVariantRef = useRef<NewVariantHandle>(null);
+
+  const refreshFiles = useCallback(async () => {
+    try {
+      const response = await fetch(`${urlPrefix}/ai_generate_editor/${question.id}/files`);
+      if (!response.ok) {
+        console.error('Failed to fetch files:', response.status);
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationEditor.tsx]: does this need better error handling back to the client?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/MemoizedMarkdown.tsx [hunk 36]
```diff
@@ -0,0 +1,34 @@
...
+  ({ content }: { content: string }) => {
+    return <ReactMarkdown>{content}</ReactMarkdown>;
+  },
+  (prevProps, nextProps) => {
+    if (prevProps.content !== nextProps.content) return false;
+    return true;
+  },
+);
+
+MemoizedMarkdownBlock.displayName = 'MemoizedMarkdownBlock';
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/MemoizedMarkdown.tsx:23]: Why do both of these need a display name? only the top level rendered component needs one, right?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/QuestionAndFilePreview.tsx [hunk 37]
```diff
@@ -0,0 +1,239 @@
...
+  variantCsrfToken,
+}: {
+  variantUrl: string;
+  variantCsrfToken: string;
+}) {
+  const wrapperRef = useRef<HTMLDivElement>(null);
+
+  const handleSubmit = useCallback(
+    (e: Event) => {
+      const target = e.target as HTMLElement;
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/QuestionAndFilePreview.tsx:172]: currentTarget ?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.ts [hunk 38]
```diff
@@ -184,25 +140,49 @@ router.get(
...
+          })
+        : [];
+
+    const courseFilesClient = getCourseFilesClient();
+    const { files: questionFiles } = await courseFilesClient.getQuestionFiles.query({
+      course_id: res.locals.course.id,
+      question_id: res.locals.question.id,
+    });
 
     const variant_id = req.query.variant_id ? IdSchema.parse(req.query.variant_id) : null;
```
Comment (reteps) [inline apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.ts:216]: Question generation is NOT feature flagged, right? I don't see a check for that here.

File: apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql (hunk 4 above)
Comment (nwalters512) [reply apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql]: Those aren't conceptually "messages", they're "parts" of the same message.

File: database/tables/ai_question_generation_messages.pg (hunk 6 above)
Comment (nwalters512) [reply database/tables/ai_question_generation_messages.pg:1]: If/when we want to do deletion, we can consider adding that then. I think soft deletion is sensible so we can keep records of token usage.

File: apps/prairielearn/src/migrations/20260204011658_ai_question_generation__revamp.sql (hunk 5 above)
Comment (nwalters512) [reply apps/prairielearn/src/migrations/20260204011658_ai_question_generation__revamp.sql:6]: We build v1 with this in mind and ultimately realized we do _not_ in fact want that (branching conversations and such). I'm happy to reconsider but I don't think this PR is the place to do that. Going to resolve this thread.

File: apps/prairielearn/src/lib/editors.ts (hunk 8 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/editors.ts]: For reuse, or keeping the function body shorter? This is the only place this is implemented/used.

File: apps/prairielearn/assets/stylesheets/instructorAiGenerateDraftEditor.css (hunk 10 above)
Comment (nwalters512) [reply apps/prairielearn/assets/stylesheets/instructorAiGenerateDraftEditor.css:141]: I'm generally of the opinion that we should move things to shared locations once they're used at least twice, often 3x+. I will move it if you ask me to but we don't yet have a need for this anywhere else. Resolving; please unresolve if you'd like me to do this.

File: apps/prairielearn/src/lib/ai-util.ts (hunk 9 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/ai-util.ts:116]: Done in 7fdf8a3.

File: apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts (hunk 11 above)
Comment (nwalters512) [reply apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts:19]: The general approach we (at least I) have been taking is that the internal router used here should lean on callers to authenticate, since they can do so cheaply and easily. The exception is routes that use the "editor" machinery, I think we've been passing along the `_edit` flag because it's easy and the editor classes expect them.

I'm leaning towards doing nothing for now. The likelihood of misuse here is very low IMO.

File: apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts (hunk 12 above)
Comment (nwalters512) [reply apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts]: Old habits die hard 🙂 refactored in bc2cef5.

Comment (nwalters512) [reply apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts]: Refactored in bc2cef5.

File: apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts (hunk 14 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts]: I refactored this to use `formatPrompt(...)` in b229528, which is consistent with how we do things elsewhere.

As to why `formatPrompt` exists: I've found it easier to use if when constructing highly dynamic prompts. That's more relevant in AI grading, but we're now doing the same in other places for consistency.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 15 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:209]: Probably not? We only really have two classes of prompts, both of which have nothing to do with each other: AI grading, and AI question generation. I'm not sure when we'd want to iterate on them in once place.

If you'd like to reorganize, let's open an issue for a discussion. Include why you think this would be a valuable change.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 17 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts]: This has been improved in 2a7b58b. Going to leave this thread unresolved to serve as a reminder that this new code needs to be reviewed.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 16 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:585]: Yes, this is intentional. This is needed so that we can divorce the creation of the stream from the call to `toUIMessageStreamResponse`, which happens in the server job.

File: apps/prairielearn/src/lib/db-types.ts (hunk 19 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/db-types.ts:284]: I see no reason to do this in Zod or to re-implement the AI SDK's validation. We'll do the validation we need higher up in the stack. Grep for `validateUIMessages`.

File: apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts (hunk 21 above)
Comment (nwalters512) [reply apps/prairielearn/src/api/trpc/routers/course-files/getQuestionFiles.ts]: The "caller" in this context is another PrairieLearn server. This is our pre-existing tRPC stuff that's used for server-to-server communication. See `privateProcedure` in `apps/prairielearn/src/api/trpc/trpc.ts` for where auth is done.

File: apps/prairielearn/src/ee/lib/context-parsers/pyproject.ts (hunk 24 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/context-parsers/pyproject.ts]: Resolved in a9b75e9.

File: apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts (hunk 25 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts:51]: We currently have no plans to change this independently of a deploy, or have it vary from deploys to deploys, so I think this is fine where it is. We can reconsider in a future PR.

File: apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts (hunk 26 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/aiQuestionGeneration.ts:110]: Improved in cc5ed89.

File: apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts (hunk 27 above)
Comment (nwalters512) [reply apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts:39]: For the same reason this function receives `course_id`/`question_id` and not `course`/`questions`: I've generally been taking the approach that internal RPC calls should include just IDs. I'm happy to reconsider this if you'd like.

File: apps/prairielearn/src/ee/models/ai-question-generation-message.ts (hunk 23 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/models/ai-question-generation-message.ts]: Done in e859d39.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/QuestionAndFilePreview.tsx (hunk 37 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/QuestionAndFilePreview.tsx:172]: No - read the comment on the next line.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.ts (hunk 38 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/instructorAiGenerateDraftEditor.ts:216]: Grep for `features.enabledFromLocals` in this file, you'll find it.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/MemoizedMarkdown.tsx (hunk 36 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/MemoizedMarkdown.tsx:23]: Read the comment at the top of the file:

```
// The approach taken here comes from this part of the AI SDK docs:
// https://ai-sdk.dev/cookbook/next/markdown-chatbot-with-memoization
```

A display name isn't _needed_, but it's very nice when working in the React dev tools. Are you opposed to adding them?

File: apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts (hunk 28 above)
Comment (nwalters512) [reply apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts:16]: If you want to change this, open an issue for discussion and we can do it all at once across all the queries/mutations. IMO this PR is not the place to make that change.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 30 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: This was indeed left over from debugging, I removed this in 076bf4e.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 31 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx:450]: This is only used in this file, I see no reason to move it elsewhere. I added a brief comment in f8d71b0.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 33 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx:535]: This string appears in exactly one place, I don't see a compelling reason to move it.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx (hunk 22 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx]: Isn't a re-render of the component with a new prop exactly what we want to happen? We _need_ that to happen because `isGenerating` will swap true to false to true to false as the user sends messages. Maybe I'm not understanding your concern here?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 32 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: I don't understand the concern underlying this comment, can you clarify?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 34 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx:622]: If you'd like to see that happen, please open a new issue to track it and state what's wrong with the current approach and how you'd change it.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 29 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: Good call - done in 9ab8240.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 18 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts]: I added error handling in bddc1e6.

File: apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts (hunk 13 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts:268]: How so? There assertions are validating that we have a user message followed by an assistant message. Is the `at(0)` and `at(-1)` confusing? I could assert that the length is 2 and just use `[0]` and `[1]`.

File: apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql (hunk 4 above)
Comment (nwalters512) [reply apps/prairielearn/src/migrations/20251018234235_ai_question_generation__revamp.sql]: I removed the system role in 0a11991.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx (hunk 22 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx]: You don't need a `useEffect` if a prop change causes it to re-render.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 32 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: https://github.com/PrairieLearn/PrairieLearn/pull/13122#discussion_r2739250453

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx (hunk 22 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx]: i.e. the lint warnings are correct, this is an antipattern/code that isn't needed. react rerendering should handling this for us, without needing the `useEffect` AFAIK

Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx]: Is the proposal that we call `editor.setEditable(...)` directly during render? That seems wrong to me - we don't know how much work that's doing behind the scenes, what if it's expensive?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 32 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: I'm not understanding how that's relevant here - can you spell out your specific concern and what you're proposing we do instead?

File: apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts (hunk 13 above)
Comment (reteps) [reply apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts:268]: It was not obvious to me that this returns a pair of messages.

File: apps/prairielearn/src/lib/editors.ts (hunk 8 above)
Comment (reteps) [reply apps/prairielearn/src/lib/editors.ts]: Keeping function body shorter.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx (hunk 22 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx]: it's not expensive. set `editable: false,` in the `useEditor` hook. In any case, even if it was expensive, I would prefer a loading state rather than a flash of an editable state before it switched to non-editable.

https://github.com/ueberdosis/tiptap/blob/2d6de06c34c239e78fedd6bd2a0bcea42d0fdbfa/packages/core/src/Editor.ts#L284

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 32 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: The code with a useEffect triggering by a prop change is a react anti-pattern. We want to minimize the amount of useEffect hooks (https://react.dev/learn/you-might-not-need-an-effect is all about avoiding effects, they are confusing). A prop change will already re-render the component, so you don't need that useEffect.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/MemoizedMarkdown.tsx (hunk 36 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/MemoizedMarkdown.tsx:23]: I just want to make sure this is intentional. Do you use the react dev tools?

Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/MemoizedMarkdown.tsx:23]: Absolutely! They're great when debugging perf/rerendering issues or inspecting state.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx (hunk 22 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx]: Ah! It wasn't at all clear to me that `useEditor` supported an `editable` option - that was the source of my confusion. Changed in 7244417.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 32 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: Can you spell out how you'd do the "clear timeout when we get another state change" without using `useEffect`? My understanding is that `useEffect` + returning a cleanup function is the canonical way to do that.

Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]:
```ts
    const [timerElapsed, setTimerElapsed] = useState(false);

    useEffect(() => {
      if (!isActive) {
        setTimerElapsed(false);
        return;
      }
      const id = setTimeout(() => setTimerElapsed(true), 800);
      return () => clearTimeout(id);
    }, [isActive]);

    if (!isActive || !timerElapsed) return false;
```

You use it for the timer, but not for the prop change

Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: I agree that timeouts are the proper use of this

Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: I iterated on this approach with Claude a bit, see 313705d. Look good?

I'm still not happy with the lint rule - let's discuss as a team if we want to keep it enabled. Maybe this is a rare case where setting state in an effect is the right thing to do and it's best to deal with the `eslint-ignore` comments here?

File: apps/prairielearn/src/lib/editors.ts (hunk 8 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/editors.ts]: Moved to a separate function in e5fae60.

File: apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts (hunk 13 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts:268]: I updated this in e5fae60. Resolving; if you still find things confusing, please unresolve and propose changes.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 7 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:5]: Added in 05baa84.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 17 above)
Comment (reteps) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts]: It looks good, my one question was where the "4" came from. A comment / link to info about that would be good.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationEditor.tsx (hunk 35 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationEditor.tsx]: In 475ddb1 and 66b6559, I switched to using TanStack query, which made error handling easier. If loading files fails, this is now shown on the "Files" tab, and users are given an option to retry.

Screenshot 2026-01-29 at 15 14 41

(I added `throw new Error("This is broken")` to the files endpoint to get the above screenshot)

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 20 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:6]: I opened https://github.com/PrairieLearn/PrairieLearn/pull/13963 to help with this. I'll enable that flag once it lands. Leaving this unresolved to remind myself to do so.

File: apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts (hunk 27 above)
Comment (reteps) [reply apps/prairielearn/src/api/trpc/routers/course-files/renameQuestion.ts:39]: This vibe feels like it would be annoying, but lets build out this a little bit so i can try it out myself. No changes required yet in this PR.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx (hunk 32 above)
Comment (reteps) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: That looks much better. I would like a lint rule that handles some of these cases (like setTimeout) better.

Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/AiQuestionGenerationChat.tsx]: I'll let you spec that out in an issue if you want it.

File: database/enums/enum_ai_question_generation_message_role.pg [hunk 39]
```diff
@@ -0,0 +1 @@
+user, assistant
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply database/enums/enum_ai_question_generation_message_role.pg:1]: @coderabbitai What looks out of sync to you here?

File: apps/prairielearn/src/lib/ai-util.ts [hunk 40]
```diff
@@ -47,21 +47,18 @@ export function calculateResponseCost({
 
   const modelPricing = config.costPerMillionTokens[model];
 
-  // TODO: this doesn't take into account cache writes, which some providers
-  // (e.g. Anthropic) charge for.
-  const cachedInputTokens = usage.inputTokenDetails.cacheReadTokens ?? 0;
   const inputTokens = usage.inputTokenDetails.noCacheTokens ?? 0;
+  const cacheReadTokens = usage.inputTokenDetails.cacheReadTokens ?? 0;
+  const cacheWriteTokens = usage.inputTokenDetails.cacheWriteTokens ?? 0;
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/lib/ai-util.ts:112]: @coderabbitai if this were an issue, TypeScript would be complaining, right?

File: apps/prairielearn/src/lib/ai-util.ts [hunk 41]
```diff
@@ -27,14 +27,14 @@ export function logResponseUsage({
 }) {
   const usage = response.usage;
   logger.info(`Input tokens: ${usage.inputTokens ?? 0}`);
-  logger.info(`  Cached input tokens: ${usage.cachedInputTokens ?? 0}`);
+  logger.info(`  Cache read tokens: ${usage.inputTokenDetails.cacheReadTokens ?? 0}`);
+  logger.info(`  Cache write tokens: ${usage.inputTokenDetails.cacheWriteTokens ?? 0}`);
   logger.info(`Output tokens: ${usage.outputTokens ?? 0}`);
-  logger.info(`  Reasoning tokens: ${usage.reasoningTokens ?? 0}`);
-  logger.info(`Total tokens: ${usage.totalTokens ?? 0}`);
+  logger.info(`  Reasoning tokens: ${usage.outputTokenDetails.reasoningTokens ?? 0}`);
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/lib/ai-util.ts:56]: @coderabbitai if this were an issue, TypeScript would be complaining, right?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx [hunk 42]
```diff
@@ -48,15 +48,19 @@ function formatHtmlWithPrettier(html: string): Promise<string> {
...
   csrfToken: _csrfToken,
   htmlContents,
+  isGenerating,
 }: {
   htmlContents: string | null;
   csrfToken: string;
+  isGenerating: boolean;
 }) => {
   const editor = useEditor({
+    editable: !isGenerating,
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx:63]: @coderabbitai what is that assertion based on? Can you point to anything in the tiptap docs that states this is the case?

File: apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts [hunk 43]
```diff
@@ -243,50 +241,78 @@ export async function benchmarkAiQuestionGeneration({
...
-          job.info('No errors detected automatically');
+      // Wait for the job sequence to complete.
+      const jobSequence = await run(async () => {
+        while (true) {
+          const jobSequence = await getJobSequence(result.jobSequenceId, course.id);
+          if (jobSequence.status !== 'Running') return jobSequence;
+          await sleep(100);
         }
-        job.error('\n');
+      });
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation-benchmark.ts]: Changed in 31e9154, how does that look?

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDrafts/instructorAiGenerateDrafts.ts [hunk 44]
```diff
@@ -98,61 +91,29 @@ router.post(
...
-            // If the user has more tokens than the threshold of 100 tokens,
-            // they can shorten their message to avoid exceeding the rate limit.
-            canShortenMessage:
-              config.aiQuestionGenerationRateLimitDollars - intervalCost > modelPricing.input * 100,
-          }),
-        );
+      if (intervalCost > config.aiQuestionGenerationRateLimitDollars) {
+        res.send(RateLimitExceeded());
         return;
       }
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDrafts/instructorAiGenerateDrafts.ts:102]: @coderabbitai that's not how we handle rate limits elsewhere in the codebase.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx (hunk 42 above)
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx:63]: @reteps CodeRabbit is exactly correct here, and this is why I took the `useEffect` approach. I'm going to restore that.

[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/RichTextEditor/index.tsx:63]: @coderabbitai how does f775d4d look?

**Review by reteps — APPROVED** [review]
🚢 it

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 20 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts:6]: Added the new flag in 7ddf248.

File: apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts (hunk 17 above)
Comment (nwalters512) [reply apps/prairielearn/src/ee/lib/ai-question-generation/agent.ts]: I improved the comment in 62cb84e.

File: apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/QuestionCodeEditors.tsx [hunk 45]
```diff
@@ -0,0 +1,199 @@
...
+          </div>
+        ) : (
+          <div className="d-flex flex-row align-items-center justify-content-between ps-2">
+            <span>{hasChanges ? 'Unsaved changes.' : 'No unsaved changes.'}</span>
+            <form method="post">
+              <input type="hidden" name="__action" value="submit_manual_revision" />
+              <input type="hidden" name="__csrf_token" value={csrfToken} />
+              <button type="submit" className="btn btn-sm btn-primary" disabled={!hasChanges}>
+                Save edits
+              </button>
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply apps/prairielearn/src/ee/pages/instructorAiGenerateDraftEditor/components/QuestionCodeEditors.tsx:176]: @coderabbitai is your comment correct? I thought we avoid rendering that entire section while `isGenerating` is true.
