### PR TITLE
Fix computation of grading phase durations in submission info box

### LINKED ISSUE #9403: Durations in submission info modal are not properly parsed
When opening the submission info modal, the grading durations are not being parsed correctly. Example below is from https://ca.prairielearn.com/pl/course_instance/6466/instance_question/72476243/.

image

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Fixes #9403. The code assumed that the dates were strings, and explicitly parsed them, but recent updates caused Zod parsing to convert them to dates instead. ~~This is solved by parsing using `DateFromISOString`, which will properly parse if the value is string and use the Date object itself if it had already been parsed.~~ Given all cases where this function is called are already parsed with Zod, no additional parsing is needed.

This PR also fixes the handling of this box when there are timestamps still set at null. Before:

image

After:

image

### CODE REVIEW

File: apps/prairielearn/src/lib/question-render.js [hunk 1]
```diff
@@ -534,31 +534,35 @@ export async function getAndRenderVariant(variant_id, variant_seed, locals) {
...
+    const stats = {
       submitDuration: formatDiff(job.grading_requested_at, job.grading_submitted_at),
       queueDuration: formatDiff(job.grading_submitted_at, job.grading_received_at),
       prepareDuration: formatDiff(job.grading_received_at, job.grading_started_at),
       runDuration: formatDiff(job.grading_started_at, job.grading_finished_at),
       reportDuration: formatDiff(job.grading_finished_at, job.graded_at),
       totalDuration: formatDiff(job.grading_requested_at, job.graded_at, false),
-      phases,
+    };
+    const totalDuration = durations.reduce((a, b) => (a ?? 0) + (b ?? 0), 0) || 1;
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/lib/question-render.js:558]:
```suggestion
    const totalDuration = durations.reduce((a, b) => a + (b ?? 0), 0) || 1;
```
