### PR TITLE
Fix access to workspace logs page

### LINKED ISSUE #11649: Workspace logs page times out
### Details

Workspace logs pages (e.g., https://us.prairielearn.com/pl/workspace/2993127/logs) are timing out.

### PR DESCRIPTION
**Pull request by mwest1066**
Fixes #11649

### CODE REVIEW

File: apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.ts [hunk 1]
```diff
@@ -116,7 +115,7 @@ async function loadLogsForWorkspaceVersion(
 // if the instructor has access to the workspace (i.e., course instance student
 // data view permission, or access to a workspace owned by the user); that's
 // already been checked by the workspace authorization middleware.
-router.use(authzHasCoursePreviewOrInstanceView);
+router.use((await import('../../middlewares/authzHasCoursePreviewOrInstanceView.js')).default);
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.ts:118]: Not that it really matters, but I prefer non-dynamic imports whenever it makes sense. The only place I think we need dynamic imports is in `server.ts` (where we don't want to have to name 100s of imports) and when they need to be conditional, e.g. with a `isEnterprise()` check.

In other words, just change the import to this:

```ts
import authzHasCoursePreviewOrInstanceView from '../../middlewares/authzHasCoursePreviewOrInstanceView.js';
```

It's horrible that the types between the middleware and function versions are both compatible with `router.use`! We could resolve that in this case by dropping `req` from the signature of the non-middleware function, as it's unused.

**Review by nwalters512 — APPROVED** [review]
The fix looks good, I won't block on any of these comments.

File: apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.ts (hunk 1 above)
Comment (jonatanschroeder) [reply apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.ts:118]: > In other words, just change the import to this:
> 
> ```ts
> import authzHasCoursePreviewOrInstanceView from '../../middlewares/authzHasCoursePreviewOrInstanceView.js';
> ```

Given that there is a named import with that name, wouldn't this be confusing? Someone reading the code might mistake the default export for the named export.

Comment (nwalters512) [reply apps/prairielearn/src/pages/workspaceLogs/workspaceLogs.ts:118]: I buy that. I'll land this as-is 👍
