### PR TITLE
Fix broken links in source code

### LINKED ISSUE #14271: Incorrect link to access control docs
### Details

The text:
> Instructions on how to change the access rules can be found in the [PrairieLearn documentation](https://docs.prairielearn.com/accessControl/). Note that changing time limit rules does not affect assessments in progress; to change the time limit for these exams please visit the [Students tab](https://us.prairielearn.com/pl/course_instance/XXX/instructor/assessment/XXX/instances). 

links to the wrong URL for PrairieLearn documentation.

https://docs.prairielearn.com/accessControl is a 404

### PR DESCRIPTION
**Pull request by reteps**
# Description

Closes #14271. Adds a script for checking, and fixes all links. Also updates the link in the legacy popover.

# Testing

Script doesn't report 404s afterwards.

### CODE REVIEW

File: scripts/check-broken-links.sh [hunk 1]
```diff
@@ -0,0 +1,16 @@
...
+
+# Finds broken links in the source code. There are a couple of false positives, inspect manually.
+# You must install lychee to use this script (https://github.com/lycheeverse/lychee).
+set -ex
+
+lychee 'apps/prairielearn/src/**/*.ts' 'apps/prairielearn/src/**/*.tsx' \
+    --exclude-path node_modules \
+    --exclude 'localhost' \
+    --exclude '127\.0\.0\.1' \
+    --exclude 'github\.com' \
```
Comment (jonatanschroeder) [inline scripts/check-broken-links.sh:11]: Any reason why this is excluded?

Comment (reteps) [reply scripts/check-broken-links.sh:11]: rate limiting reasons
