### PR TITLE
Make multi-part file edits atomic

### LINKED ISSUE #11222: Make JSON edits/renames atomic
We discovered an interesting edge case recently: if a course was already in an invalid state (that is, sync would failed if you just clicked the "Sync" button), then trying to rename an assessment would fail. This is because we apply the edit in two phases: first we update the JSON file itself, then we move the file if we need to. If the first edit fails (and it will, because the course was already in an invalid state), the second edit won't complete.

https://github.com/PrairieLearn/PrairieLearn/blob/41ba1a1c1407c5f1ce27e1ffd7f60859cffc77a8/apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.ts#L163-L238

We'd really like to make edits atomic so that they don't partially complete. This matches the behavior of edits made directly to files via Git: even if syncing experiences errors in specific files, all other edits will be reflected on PrairieLearn correctly.

It'd probably be nice to build a generic system to compose editors together. I'm picturing something like this:

```ts
const editor = new MultiEditor([
  new FileModifyEditor(...),
  new AssessmentRenameEditor(...),
]);
```

This would then run the edits in sequence, but avoid committing/pushing/syncing/etc. til the very end.

### PR DESCRIPTION
**Pull request by nwalters512**
Closes #11222.

As proposed in that issue, this PR introduces a new `MultiEditor` that itself can execute multiple editors.

As part of this, I removed some dead code related to a `change_id` action that was since removed. I also did some refactoring of editors as a whole to improve type safety.

### CODE REVIEW

File: apps/prairielearn/src/lib/editors.ts [hunk 1]
```diff
@@ -180,8 +180,16 @@ export function getUniqueNames({
...
+interface BaseEditorOptions<ResLocals = object> {
+  locals: {
+    authz_data: Record<string, any>;
+    course: Course;
+    user: User;
+  } & ResLocals;
+}
+
+interface BaseEditorOptionsInternal extends BaseEditorOptions {
+  description: string;
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/editors.ts:192]: In practice this doesn't add any type safety to calls since `res.locals` is always a big unknown thing, but it does give us slightly more guarantees when editors are used.

File: apps/prairielearn/src/lib/editors.ts [hunk 2]
```diff
@@ -193,30 +201,24 @@ export abstract class Editor {
...
-
-  /**
-   * Determines whether or not the edit should be executed. For instance, this
-   * can check if the edit would actually modify a file and skip the write/commit/push
-   * steps if it would not.
-   */
-  protected async shouldEdit(): Promise<boolean> {
-    return true;
-  }
+  abstract write(): Promise<WriteResult | null>;
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/editors.ts:219]: Having `write()` itself determine if it needs to make an edit ended up being a bit easier to work with in `MultiEditor` and in how the editor is used when it's actually run.

File: apps/prairielearn/src/lib/editors.ts [hunk 3]
```diff
@@ -581,12 +586,18 @@ export class AssessmentCopyEditor extends Editor {
...
-  constructor(params: BaseEditorOptions) {
-    super(params);
+  constructor(
+    params: BaseEditorOptions<{ course_instance: CourseInstance; assessment: Assessment }>,
+  ) {
+    const { course_instance, assessment } = params.locals;
+
+    super({
+      ...params,
+      description: `${course_instance.short_name}: copy assessment ${assessment.tid}`,
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/editors.ts:596]: Moving `description` to the `Editor` constructor ensures we never forget to set it.

File: apps/prairielearn/src/lib/editors.ts [hunk 4]
```diff
@@ -2082,3 +2200,45 @@ export class CourseInfoCreateEditor extends Editor {
...
   }
 }
+
+export class MultiEditor extends Editor {
+  private editors: Editor[];
+
+  constructor(params: BaseEditorOptions, editors: Editor[]) {
+    super({
+      ...params,
+      description: editors.map((editor) => editor.description).join('; '),
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/editors.ts:2210]: TODO: do some more clever things to produce a nicer description.

File: apps/prairielearn/src/lib/editors.ts [hunk 5]
```diff
@@ -2082,3 +2200,45 @@ export class CourseInfoCreateEditor extends Editor {
...
+    });
+
+    this.editors = editors;
+  }
+
+  assertCanEdit() {
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/editors.ts:2216]: TODO: add call to `super.assertCanEdit()` for good measure.

File: apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.ts [hunk 6]
```diff
@@ -125,41 +128,6 @@ router.post(
       } catch {
         res.redirect(res.locals.urlPrefix + '/edit_error/' + serverJob.jobSequenceId);
       }
-    } else if (req.body.__action === 'change_id') {
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/instructorAssessmentSettings/instructorAssessmentSettings.ts:128]: This was dead code.

File: apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts [hunk 7]
```diff
@@ -80,35 +80,29 @@ router.post(
         await fs.readFile(path.join(res.locals.course.path, 'infoCourse.json'), 'utf8'),
       );
 
-      if (
-        req.body.short_name !== courseInfo.name ||
-        req.body.title !== courseInfo.title ||
-        req.body.display_timezone !== courseInfo.timezone
-      ) {
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/instructorCourseAdminSettings/instructorCourseAdminSettings.ts:87]: I realized that `FileModifyEditor` takes care of no-opping for us.

File: apps/prairielearn/src/lib/editors.ts (hunk 4 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/editors.ts]: That ended up being complicated. In ce3f39d I just forced users of `MultiEditor` to explicitly provide a description.

File: apps/prairielearn/src/lib/editors.ts (hunk 5 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/editors.ts:2213]: Done in a91240c.

File: apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts [hunk 8]
```diff
@@ -122,29 +122,14 @@ export function InstructorQuestionSettings({
...
-                </div>
                 <div class="form-group">
                   <label for="qid">QID</label>
                   ${questionGHLink
                     ? html`<a target="_blank" href="${questionGHLink}"> view on GitHub </a>`
                     : ''}
                   <input
                     type="text"
-                    class="form-control"
+                    class="form-control text-monospace"
```
Comment (nwalters512) [inline apps/prairielearn/src/pages/instructorQuestionSettings/instructorQuestionSettings.html.ts:132]: Two opportunistic changes here:

- I added `text-monospace` to the QID input
- I reordered the QID input to be first

Both of these changes make this page more consistent with the assessment settings page.

**Review by mwest1066 — APPROVED** [review]
lgtm and works locally.
