### PR TITLE
Ensure stable ordering of assessments

### LINKED ISSUE #9836: Random reordering of some assessment columns in exported gradebooks
We recently noticed an unexpected PL behaviour that causes _exported gradebook to reorder assessment columns apparently randomly_, when assessments share the same `set` and `number`. See the screenshot below.

```
"set": "Homework",
"number": "3",
```
In our case, we had two assessments both with same `set` and `number` above (the older one was incorrect and omitted). They show up under Gradebook tab as expected: always the older assessment column comes before the newer one.
When you export the gradebook, they show up as `HW3` and `HW3.1`. However, the problem is that when you **export multiple times**, which assessment will be called `HW3.1` seems to be randomly selected, as shown in the screenshot.
The links to these assessments HW3 (old) and HW3 (new) are available in the [related discussion in Slack pl-help channel](https://prairielearn.slack.com/archives/C266KEH9A/p1715289185324159).

PL_gradebook_export_BUG

### PR DESCRIPTION
**Pull request by nwalters512**
Closes #9836. This won't take effect until courses re-sync.

A fun fact: we currently pretty much always sort assessments by three columns when selecting them, for instance:

https://github.com/PrairieLearn/PrairieLearn/blob/e88d079812180315e2ce90d8605fdffbe01a8185/apps/prairielearn/src/middlewares/selectAssessments.sql#L15-L18

However, from what I can see, the `id` column will never be used, because `order_by` will always contain fully unique values, and so we'll never fall back to ordering on the `id`. AFAICT this is a relic of when we used to sort by `assessments.number` directly: https://github.com/PrairieLearn/PrairieLearn/commit/8cebe15ab7bd63ef2f3493027d2550ad2105a522.

I'm sort of inclined to go through the codebase and remove `assessments.id` as a fallback ordering for `assessments.order_by`. Thoughts?

### CODE REVIEW

File: apps/prairielearn/src/sprocs/sync_assessments.sql [hunk 1]
```diff
@@ -525,12 +525,26 @@ BEGIN
...
+                                'SQL_ASCII'
+                            ),
+                            '\x00'
+                        )
+                    FROM
+                        regexp_matches(number, '0*([0-9]+)|([^0-9]+)', 'g') r
+                ) ASC,
+                -- In case two assessments have the same number, fall back to
+                -- ordering by the ID to ensure a stable sort.
+                id ASC
```
Comment (nwalters512) [inline apps/prairielearn/src/sprocs/sync_assessments.sql:546]: In case it wasn't obvious (I had to double check), Postgres doesn't at all guarantee sort order when an `ORDER BY` clause does not uniquely order all elements:

> If sorting is not chosen, the rows will be returned in an unspecified order. The actual order in that case will depend on the scan and join plan types and the order on disk, but it must not be relied on. ([source](https://www.postgresql.org/docs/current/queries-order.html))

**Comment by mwest1066** [comment]
To make sure I'm understanding here, is the bug that we re-order assessments only _during sync_? That is, we have deterministic ordering for any given DB state, but sync may reorder assessments that have identical numbers. And this is what Mehrdad encountered? That is, he was downloading the assessments twice, with a sync in between?

That's a great catch. I couldn't see how we were re-ordering, but having a sync in between is the key!

**Review by mwest1066 — APPROVED** [review]

**Comment by mwest1066** [comment]
> However, from what I can see, the `id` column will never be used, because `order_by` will always contain fully unique values, and so we'll never fall back to ordering on the `id`. AFAICT this is a relic of when we used to sort by `assessments.number` directly: [8cebe15](https://github.com/PrairieLearn/PrairieLearn/commit/8cebe15ab7bd63ef2f3493027d2550ad2105a522).
> 
> I'm sort of inclined to go through the codebase and remove `assessments.id` as a fallback ordering for `assessments.order_by`. Thoughts?

My only hesitation here is that we don't actually have a DB constraint that guarantees unique `order_by` values. I agree that our current sync code ensures this, but it feels a bit nasty to rely on that. However, ordering is not (normally) super critical, so I also don't feel too worried about removing the `id` fallback if you prefer to eliminate it.

Of course, it would be cool to have a DB constraint for unique `order_by` but I think this isn't easy to do with our current sync code? Perhaps a deferred constraint? Probably not worth the effort.

**Comment by nwalters512** [comment]
> To make sure I'm understanding here, is the bug that we re-order assessments only during sync? That is, we have deterministic ordering for any given DB state, but sync may reorder assessments that have identical numbers. And this is what Mehrdad encountered? That is, he was downloading the assessments twice, with a sync in between?

As best as I can tell, this is what happened, yes, though I don't have concrete dates for the CSV downloads. I was never actually able to reproduce it locally, as I think this is the kind of bug that depends heavily on Postgres internals, which blocks are cached, etc.

> My only hesitation here is that we don't actually have a DB constraint that guarantees unique `order_by` values. I agree that our current sync code ensures this, but it feels a bit nasty to rely on that. However, ordering is not (normally) super critical, so I also don't feel too worried about removing the `id` fallback if you prefer to eliminate it.

Yeah, I can buy that ordering by `id` is a helpful fallback to have! It certainly doesn't cause us much harm to leave it in.

> Of course, it would be cool to have a DB constraint for unique `order_by` but I think this isn't easy to do with our current sync code? Perhaps a deferred constraint? Probably not worth the effort.

I agree, completely not worth the effort.
