### PR TITLE
Fix layout of footer on homepage

### LINKED ISSUE #13619: Homepage footer appears behind content
### Details

On the home page where you see all of your courses, if you have a large number of courses (>25 in my case), the footer is hidden behind the list of courses

Footer in question

Image

View with lots of courses (note the border and background color on the left and right side of the course)

Image

### PR DESCRIPTION
**Pull request by nwalters512**
# Description

Closes #13619.

# Testing

When the viewport is taller than the content:

Screenshot 2025-12-23 at 11 06 18

When the content is taller than the viewport (requires scrolling):

Screenshot 2025-12-23 at 11 06 32

### CODE REVIEW

File: apps/prairielearn/src/components/PageLayout.tsx
Comment (nwalters512) [inline apps/prairielearn/src/components/PageLayout.tsx:1]: I shifted the display of the footer into `PageLayout` since laying things out correctly relies on setting styles on various wrapping components that individual pages shouldn't be aware of.

File: apps/prairielearn/src/components/PageLayout.tsx [hunk 1]
```diff
@@ -277,7 +285,10 @@ export function PageLayout({
         ${sideNavEnabled ? compiledScriptTag('pageLayoutClient.ts') : ''}
       </head>
       <body
-        class="${resolvedOptions.fullHeight ? 'd-flex flex-column h-100' : ''}"
+        class="${clsx(
+          resolvedOptions.fullHeight && 'd-flex flex-column h-100',
```
Comment (reteps) [inline apps/prairielearn/src/components/PageLayout.tsx]: does clsx dedupe?

File: apps/prairielearn/src/components/PageLayout.tsx [hunk 2]
```diff
@@ -327,12 +339,7 @@ export function PageLayout({
               `
             : ''}
           <div class="${clsx(sideNavEnabled && 'app-main', resolvedOptions.fullHeight && 'h-100')}">
-            <div
-              class="${clsx(
-                sideNavEnabled ? 'app-main-container' : 'h-100 w-100',
-                'd-flex flex-column',
-              )}"
-            >
+            <div class="${clsx(sideNavEnabled && 'app-main-container', 'd-flex flex-column')}">
```
Comment (reteps) [inline apps/prairielearn/src/components/PageLayout.tsx]: Why was `h-100 w-100` removed? I thought that was needed for e.g. workspace pages

Comment (reteps) [reply apps/prairielearn/src/components/PageLayout.tsx]: CleanShot 2025-12-23 at 14 54 11@2x
CleanShot 2025-12-23 at 14 55 10@2x

**Review by reteps — CHANGES_REQUESTED** [review]
close!

File: apps/prairielearn/src/components/PageLayout.tsx (hunk 2 above)
Comment (nwalters512) [reply apps/prairielearn/src/components/PageLayout.tsx]: Great catch - these classes were causing problems when they were applied unconditionally, but yes, they're needed on this page. I think we need to make these conditional on`fullWidth`/`fullHeight`. I'll investigate.

Comment (nwalters512) [reply apps/prairielearn/src/components/PageLayout.tsx]: This was resolved in 42ef557. I tested the workspace page with the changes:

Screenshot 2025-12-23 at 14 15 32

Are there any other "weird" pages you can think of to test?

Comment (reteps) [reply apps/prairielearn/src/components/PageLayout.tsx]: Nope, I think the homepage, a question page that scrolls, a tanstack table full height, and the workspace page are the full range

File: apps/prairielearn/src/components/PageLayout.tsx (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/src/components/PageLayout.tsx]: Interestingly it does not:

```
> clsx('a', {'a': true})
'a a'
```

But that shouldn't really matter.

Comment (reteps) [reply apps/prairielearn/src/components/PageLayout.tsx]: That's unfortunate. a nit would be to rewrite it so that duplicates don't happen.

Comment (nwalters512) [reply apps/prairielearn/src/components/PageLayout.tsx]: What problem do you anticipate with duplicates?

Comment (reteps) [reply apps/prairielearn/src/components/PageLayout.tsx]: no problems, just slightly ugly html

Comment (nwalters512) [reply apps/prairielearn/src/components/PageLayout.tsx]: Fair enough! Changed in 1b265d5.
