### PR TITLE
Fix unicode bug in editor

### LINKED ISSUE #1705: Instructor file editor crashes server with invalid data
At 00:55:05 UTC today, PL crashed due to an uncaught exception in the instructor file editor:

```
/PrairieLearn/pages/instructorFileEditor/instructorFileEditor.js:250
return decodeURIComponent(Buffer.from(str, 'base64').toString().split('').map((c) => {
^
URIError: URI malformed
at decodeURIComponent (<anonymous>)
at b64DecodeUnicode (/PrairieLearn/pages/instructorFileEditor/instructorFileEditor.js:250:12)
at writeEdit (/PrairieLearn/pages/instructorFileEditor/instructorFileEditor.js:443:19)
at /PrairieLearn/pages/instructorFileEditor/instructorFileEditor.js:427:13
at /PrairieLearn/node_modules/async/dist/async.js:2952:28
at replenish (/PrairieLearn/node_modules/async/dist/async.js:444:21)
at iterateeCallback (/PrairieLearn/node_modules/async/dist/async.js:428:21)
at /PrairieLearn/node_modules/async/dist/async.js:325:20
at /PrairieLearn/node_modules/async/dist/async.js:2957:17
at /PrairieLearn/pages/instructorFileEditor/instructorFileEditor.js:422:17
at /PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:452:9
at Query.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/lib/sql-db.js:423:17)
at Query.handleReadyForQuery (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/query.js:125:10)
at Connection.<anonymous> (/PrairieLearn/node_modules/@prairielearn/prairielib/node_modules/pg/lib/client.js:244:19)
at Connection.emit (events.js:203:13)
at Connection.EventEmitter.emit (domain.js:471:20)
```

### PR DESCRIPTION
**Pull request by tbretl**
Changes the way that base64 is encoded and decoded to properly handle unicode.

Fixes #1705 and #1625.

### CODE REVIEW

File: tests/testFileEditor.js [hunk 1]
```diff
@@ -212,6 +215,20 @@ const verifyEditData = [
 describe('test file editor', function() {
     this.timeout(20000);
 
+    describe('test base64-util lib, on which file editor depends', function() {
```
Comment (nwalters512) [inline tests/testFileEditor.js]: I'd prefer a test of the editor itself with such a string so that we don't rely on current implementation details.

File: ChangeLog.md [hunk 2]
```diff
@@ -341,6 +341,8 @@
 
   * Fix flaky test cases in `pl-number-input` which didn't handle comparison options properly (Mingjie Zhao).
 
+  * Fix bug in unicode encode/decode in file editor (Tim Bretl).
```
Comment (nwalters512) [inline ChangeLog.md]: Entry should be under the **__next version__** section.

File: pages/instructorFileEditor/instructorFileEditor.js [hunk 3]
```diff
@@ -236,24 +237,8 @@ router.post('/', (req, res, next) => {
...
-function b64DecodeUnicode(str) {
-    // Going backwards: from bytestream, to percent-encoding, to original string.
-    return decodeURIComponent(Buffer.from(str, 'base64').toString().split('').map((c) => {
-        return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
-    }).join(''));
-}
-
 function getHash(contents) {
-    return b64EncodeUnicode(sha256(contents).toString());
+    return b64Util.b64EncodeUnicode(sha256(contents).toString());
```
Comment (nwalters512) [inline pages/instructorFileEditor/instructorFileEditor.js]: Not really relevant to this PR, but why is the hash base-64 encoded?

File: tests/testFileEditor.js [hunk 4]
```diff
@@ -212,6 +215,20 @@ const verifyEditData = [
...
+        it('should encode a challenging string without crashing', function() {
```
Comment (nwalters512) [inline tests/testFileEditor.js]: Nit: I think we should be more conservative with our usage `it(...)` blocks; this is the main reason our test output is so long. Not as important for just three tests, but in general I want to move towards grouping more testing inside a single `it(...)` block.

**Comment by mwest1066** [comment]
Rather than including this blob of code from MDN, could we use the `base-64` npm library [0], together with the `utf8` library [1] to first convert to UTF-8? Alternatively, we could also accept corrupted unicode using WTF-8 [2].

[0] https://www.npmjs.com/package/base-64
[1] https://github.com/mathiasbynens/utf8.js
[2] https://github.com/mathiasbynens/wtf-8

File: tests/testFileEditor.js (hunk 1 above)
Comment (tbretl) [reply tests/testFileEditor.js]: done

File: ChangeLog.md (hunk 2 above)
Comment (tbretl) [reply ChangeLog.md]: done

File: pages/instructorFileEditor/instructorFileEditor.js (hunk 3 above)
Comment (tbretl) [reply pages/instructorFileEditor/instructorFileEditor.js]: you're right, let's revisit this later ;-)

File: tests/testFileEditor.js (hunk 4 above)
Comment (tbretl) [reply tests/testFileEditor.js]: fair enough, and this test has been removed anyway
