### PR TITLE
Fix the publishing form not posting 0 seconds correctly

### LINKED ISSUE #13491: Setting scheduled start date to zero seconds causes sync error
### Details

https://github.com/user-attachments/assets/838107d5-de38-4565-ac02-0315b749c059

This is an issue with `input` and `datetime-local` and it seems like its only happening on chrome: 

https://stackoverflow.com/questions/19504018/show-seconds-on-input-type-date-local-in-chrome

My chrome version is Version 142.0.7444.176

### PR DESCRIPTION
**Pull request by reteps**
# Description

Fixes #13491 . This seems to be a chrome browser bug, we are setting step. On client side posts, I fix this on the client. On server side posts, I fix this on the server.
 

# Testing

I tested the main publishing form (server post) and the add course instance form (client post).

### CODE REVIEW

**Comment by jonatanschroeder** [comment]
Another way to address this is to accept a HH:MM format in input_date. I believe this would likely be more robust.

https://github.com/PrairieLearn/PrairieLearn/blob/aeedb63965434ccb8f6408e142ae3ef928a67ff7/apps/prairielearn/src/sprocs/input_date.sql#L16

**Comment by reteps** [comment]
> Another way to address this is to accept a HH:MM format in input_date. I believe this would likely be more robust.
> 
> https://github.com/PrairieLearn/PrairieLearn/blob/aeedb63965434ccb8f6408e142ae3ef928a67ff7/apps/prairielearn/src/sprocs/input_date.sql#L16

I would prefer to fix this as far upstream as possible -- I don't see any reason to make our parsing/internal format more lenient to account for a chrome browser bug.

I could imagine fixing it there then violates assumptions elsewhere that this date has seconds.

**Comment by jonatanschroeder** [comment]
> I would prefer to fix this as far upstream as possible -- I don't see any reason to make our parsing/internal format more lenient to account for a chrome browser bug.
> 
> I could imagine fixing it there then violates assumptions elsewhere that this date has seconds.

What about a custom Zod type, then (in @prairielearn/zod)? I assume you will eventually need this transformation in multiple places.

**Comment by reteps** [comment]
> > I would prefer to fix this as far upstream as possible -- I don't see any reason to make our parsing/internal format more lenient to account for a chrome browser bug.
> > I could imagine fixing it there then violates assumptions elsewhere that this date has seconds.
> 
> What about a custom Zod type, then (in @prairielearn/zod)? I assume you will eventually need this transformation in multiple places.

That would be a great idea, I almost did that for this PR. However, we are thinking of switching to tRPC -- I'm thinking that I want to defer that to a potential switch. I'm not sure what validation looks like there.

Edit: I split that into #13510.

File: apps/prairielearn/src/pages/instructorCopyPublicCourseInstance/instructorCopyPublicCourseInstance.ts [hunk 1]
```diff
@@ -15,8 +15,15 @@ router.post(
...
-        end_date: z.string(),
+        // This works around a bug in Chrome where seconds are omitted from the input value when they're 0.
+        // We would normally solve this on the client side, but this page does a HTML POST, so transformations
+        // done via react-hook-form don't work.
+
+        // https://stackoverflow.com/questions/19504018/show-seconds-on-input-type-date-local-in-chrome
+        // https://issues.chromium.org/issues/41159420
+
+        start_date: z.string().transform((v) => (v.length === 16 ? `${v}:00` : v)),
+        end_date: z.string().transform((v) => (v.length === 16 ? `${v}:00` : v)),
```
Comment (mylesw27) [inline apps/prairielearn/src/pages/instructorCopyPublicCourseInstance/instructorCopyPublicCourseInstance.ts:26]: Do you want to move your `normalizeDateTimeLocal` helper function to a shared location and use it here (and in `instructorInstanceAdminPublishing.tsx`)?

Comment (reteps) [reply apps/prairielearn/src/pages/instructorCopyPublicCourseInstance/instructorCopyPublicCourseInstance.ts:26]: Not really, let's defer this to a proper schema refactor.
