### PR TITLE
Include variant data in student reported issues

### LINKED ISSUE #11584: Variant data not included in student-reported issue
When a student reports an error in a question, the `variant` data is not included in the course data. It's supposed to be copied but it's not actually happening:
https://github.com/PrairieLearn/PrairieLearn/blob/ab3118c2f2f099f74abc117dd4652e1421bde7fd/apps/prairielearn/src/lib/issues.ts#L138

### PR DESCRIPTION
**Pull request by mylesw27**
Closes #11584. Currently, variant data is not being added to the `courseData` that is stored with a reported issue. This is due to a function that relies on variant data being attached to `res.locals` when it actually is not. This PR will update the `courseData` to use variant data that exists.

### CODE REVIEW

File: apps/prairielearn/src/lib/issues.ts [hunk 1]
```diff
@@ -1,6 +1,5 @@
 import * as async from 'async';
 import { type Request, type Response } from 'express';
-import _ from 'lodash';
```
Comment (mylesw27) [inline apps/prairielearn/src/lib/issues.ts:3]: This is an added bonus here.

File: apps/prairielearn/src/lib/issues.ts [hunk 2]
```diff
@@ -140,13 +139,19 @@ export async function reportIssueFromForm(
...
     courseCaused: true,
-    courseData: _.pick(res.locals, [
-      'variant',
-      'question',
-      'course_instance',
-      'course',
-      ...(studentSubmission ? ['instance_question', 'assessment_instance', 'assessment'] : []),
-    ]),
+    courseData: {
+      variant,
```
Comment (mylesw27) [inline apps/prairielearn/src/lib/issues.ts:143]: `res.locals.variant` does not actually exist. We are already using `selectAndAuthzVariant` above so using that data to populate `variant` here.

**Review by jonatanschroeder — APPROVED** [review]
