### PR TITLE
fix: Use appropriate MathJax conversion in pl-rich-text-editor

### LINKED ISSUE #6880: pl-rich-text-editor: Math does not get inserted in Safari
Reported by a student: The math/formula button does not insert anything when used in Safari. The student reported that this works in Chrome. I have tried this in Firefox (works) and Safari (does not work).

Screen Shot 2023-01-09 at 15 13 48

Safari, blank space highlighted:
Screen Shot 2023-01-09 at 15 14 37

Expected, in Firefox:
Screenshot 2023-01-09 at 15-15-38 admin_reflection1 (Preview) - CAPP 30271 wi23 PrairieLearn

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Resolves #6880. Uses the appropriate format of conversion for MathJax depending on which output is currently in use.

I don't have access to Safari to test this there, but by changing manually the format in pages/partials/mathjax.js I was able to reproduce the original error and make it run properly there. I'd appreciate if someone can actually test it in Safari.

Also, keeping in mind #6792, this may be reviewed soon as well, so it may be good to ensure that any changes that address that also test this functionality.

### CODE REVIEW

File: elements/pl-rich-text-editor/pl-rich-text-editor.js [hunk 1]
```diff
@@ -63,7 +63,10 @@ class MathFormula extends Embed {
 
   static updateNode(node, value) {
     MathJax.startup.promise.then(async () => {
-      let html = await MathJax.tex2chtmlPromise(value);
+      let html =
+        outputComponent === 'output/chtml'
```
Comment (nwalters512) [inline elements/pl-rich-text-editor/pl-rich-text-editor.js:67]: I reallllly don't want to rely on a bespoke global variable here. Could we instead inspect MathJax's configuration? `MathJax` is at least a standard and well-known global, and it looks like `MathJax.config.loader.load` can be checked for `output/chtml` or `output/svg`.

Comment (jonatanschroeder) [reply elements/pl-rich-text-editor/pl-rich-text-editor.js:67]: Sure, I can do that. I realize this was completed in a rush when I was tired, so it can certainly use a bit more care.

**Comment by echuber2** [comment]
How is CHTML on Safari (vs. SVG)? I'm going to need other people's help checking some rendering stuff soon.

File: elements/pl-rich-text-editor/pl-rich-text-editor.js (hunk 1 above)
Comment (jonatanschroeder) [reply elements/pl-rich-text-editor/pl-rich-text-editor.js]: Resolved in 4c7a53c in a more elegant way, using the existence of the function itself as a signal.

File: elements/pl-rich-text-editor/pl-rich-text-editor.js [hunk 2]
```diff
@@ -63,8 +63,8 @@ class MathFormula extends Embed {
 
   static updateNode(node, value) {
     MathJax.startup.promise.then(async () => {
-      let html = await MathJax.tex2chtmlPromise(value);
-      let formatted = html.innerHTML;
+      const html = await (MathJax.tex2chtmlPromise || MathJax.tex2svgPromise)(value);
```
Comment (nwalters512) [inline elements/pl-rich-text-editor/pl-rich-text-editor.js:66]: Very nice!

**Review by nwalters512 — APPROVED** [review]
