### PR TITLE
Fix fingerprint tracking when URL contains variant ID

### LINKED ISSUE #12935: Student log entries missing a fingerprint
### Details

See https://us.prairielearn.com/pl/course_instance/189010/instructor/assessment_instance/11182012

Numerous entries on the log are missing a fingerprint, including variant views and submissions.

### PR DESCRIPTION
**Pull request by nwalters512**
# Description

Closes #12935.

This regressed in #12582. After the first submission to a given question, the URL would be something like `.../instance_question/12345?variant_id=54321`. In this middleware, `req.url` would then be `/?variant_id=12345`, which would obviously pass the `!== '/'` check.

See https://github.com/PrairieLearn/PrairieLearn/pull/12582#discussion_r2258562258: over and over again we've proven to ourselves that using middleware for fingerprints is a Bad Idea. This PR is making the minimal change to get things working again until we can do a comprehensive refactor.

# Testing

- Open a homework as a student; open a question.
- Make a submission; the URL should now have a `?variant_id=...` query param.
- Make another submission.

On `master`, only the first "view variant" and "submission" events will have a fingerprint. The latter two will not.

On this branch, all "view variant" and "submission" events will have a fingerprint.

### CODE REVIEW

**Comment by mwest1066** [comment]
> See [#12582 (comment)](https://github.com/PrairieLearn/PrairieLearn/pull/12582#discussion_r2258562258): over and over again we've proven to ourselves that using middleware for fingerprints is a Bad Idea. This PR is making the minimal change to get things working again until we can do a comprehensive refactor.

So much this! Middleware that needs to carefully inspect the URLs is just so 🤮

File: apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts [hunk 1]
```diff
@@ -30,6 +31,10 @@ const router = Router({ mergeParams: true });
 
 router.use(enterpriseOnly(() => checkPlanGrantsForQuestion));
 router.use((req, res, next) => {
+  // We deliberately use `url` instead of `originalUrl`. The former is relative to
```
Comment (reteps) [inline apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts:34]: This has slightly different semantics, since `req.url` can be [overridden](https://stackoverflow.com/questions/24613816/difference-between-req-url-and-req-originalurl-in-express-js-version-4). I assume that is fine.

Comment (nwalters512) [reply apps/prairielearn/src/pages/studentInstanceQuestion/studentInstanceQuestion.ts:34]: That overriding is exactly what we want, as the comment calls out. That's why we compare with `/` and not `/pl/course_instance/.../instance_question/...`.
