### PR TITLE
Use streaming CSV stringification

### LINKED ISSUE #6523: Use streaming CSV generation
Currently, our internal [`nonblocking-csv-stringify,js`](https://github.com/PrairieLearn/PrairieLearn/blob/968fd86821e056d1ddd02c231cfcf483267a7c9b/lib/nonblocking-csv-stringify.js) lib that we use to generate CSVs is actually buffering the entire thing in memory. This causes the process to run out of memory and crash when someone tries to export a CSV that's too large, as the size of the CSV exceeds the max size of a Node string (~1GB).

To fix this, we should pipe the `csv-stringify` stream directly to the Express response. This will avoid the need to construct massive strings in memory.

We may want to look into using a cursor to read from the database (https://node-postgres.com/api/cursor).

Making these changes should allow us to close https://github.com/PrairieLearn/PrairieLearn/issues/1155.

### PR DESCRIPTION
**Pull request by nwalters512**
I originally thought that we'd be able to use `require('csv-stringify').stringify` directly, but AFAICT it will still try to write every item synchronously, which will block the event loop. So, I kept our existing `nonblockingStringify` function, but instead of immediately collecting the chunks, it now returns the `Stringifier` instance for the caller to `.pipe(...)` as needed.

I did not update any code to user cursors, If folks still think that would be of high value, I'll split that out into another issue.

Closes #6523; closes #6855.

### CODE REVIEW

**Review by mwest1066 — DISMISSED** [review]
This PR is clearly a benefit over the current state of the code and I'm happy to have it merged as is. However:
* At some point we need to pull this out into a separate package (PT also wants to consume this). Maybe this is a good chance to do this? I'm fine to leave this for a separate PR of course.
* I'm not convinced that this is going to solve #1155 without also adding streaming for both the DB query (using cursors) and `rowsToCsv()`. I think most of our CSV generation is fine (things like Gradebook downloads) but the bad large queries come in `instructorAssessmentDownloads.js` from the queries `submissions_for_manual_grading` and `assessment_instance_submissions`. These are the queries that will return submission data as a CSV, which is where our huge CSVs are coming from (afaik). Again, it's fine to leave a fully-streaming implementation to a future PR.

**Comment by jonatanschroeder** [comment]
> * I'm not convinced that this is going to solve #1155 without also adding streaming for both the DB query (using cursors) and `rowsToCsv()`. I think most of our CSV generation is fine (things like Gradebook downloads) but the bad large queries come in `instructorAssessmentDownloads.js` from the queries `submissions_for_manual_grading` and `assessment_instance_submissions`. These are the queries that will return submission data as a CSV, which is where our huge CSVs are coming from (afaik). Again, it's fine to leave a fully-streaming implementation to a future PR.

https://github.com/PrairieLearn/PrairieLearn/pull/6855#issuecomment-1371202288 (and following comments)

File: pages/instructorQuestionStatistics/instructorQuestionStatistics.js [hunk 1]
```diff
@@ -1,138 +1,106 @@
...
-router.get('/:filename', function (req, res, next) {
-  _.assign(res.locals, filenames(res.locals));
+    res.locals.question_attempts_histogram = null;
+    res.locals.question_attempts_before_giving_up_histogram = null;
+    res.locals.question_attempts_histogram_hw = null;
+    res.locals.question_attempts_before_giving_up_histogram_hw = null;
+    // res.locals.question_attempts_histogram = res.locals.result.question_attempts_histogram;
+    // res.locals.question_attempts_before_giving_up_histogram = res.locals.result.question_attempts_before_giving_up_histogram;
+    // res.locals.question_attempts_histogram_hw = res.locals.result.question_attempts_histogram_hw;
+    // res.locals.question_attempts_before_giving_up_histogram_hw = res.locals.result.question_attempts_before_giving_up_histogram_hw;
```
Comment (nwalters512) [inline pages/instructorQuestionStatistics/instructorQuestionStatistics.js:34]: 👀 any idea what's up with this?

File: packages/postgres/src/pool.ts [hunk 2]
```diff
@@ -924,7 +927,23 @@ export class PostgresPool {
...
+          writableObjectMode: true,
+          transform(chunk, _encoding, callback) {
+            for (const row of chunk) {
+              this.push(row);
+            }
+            callback();
+          },
+        });
+
+        // TODO: use native `node:stream#compose` once it's stable.
```
Comment (nwalters512) [inline packages/postgres/src/pool.ts:942]: It's currently listed as experimental and isn't present in the TypeScript types for Node, so I opted to avoid it for now.

File: pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js [hunk 3]
```diff
@@ -298,139 +291,105 @@ router.get('/:filename', function (req, res, next) {
...
+      const archive = archiver('zip');
+      const dirname = (res.locals.assessment_set.name + res.locals.assessment.number).replace(
+        ' ',
+        ''
+      );
+      const prefix = `${dirname}/`;
+      archive.append(null, { name: prefix });
+      archive.pipe(res);
+
+      for await (const rows of cursor.iterate(100)) {
```
Comment (mwest1066) [inline pages/instructorAssessmentDownloads/instructorAssessmentDownloads.js:314]: ❤️

File: tests/postgres.test.js
Comment (mwest1066) [inline tests/postgres.test.js:1]: I feel like we discussed this recently, but what's stopping us from moving (most of) this file into the `@prairielearn/postgres` package?

**Review by mwest1066 — APPROVED** [review]

File: packages/postgres/src/pool.ts [hunk 4]
```diff
@@ -924,7 +927,23 @@ export class PostgresPool {
...
+        return multipipe(Readable.from(iterator.iterate(batchSize)), transform);
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply packages/postgres/src/pool.ts:943]: `pipeline` is best suited for when you have an initial source and a final destination; `multipipe` (or `compose`, which it mirrors) lets you construct a stream that in turn will be piped elsewhere. I think the [`compose` docs](https://nodejs.org/api/stream.html#streamcomposestreams) say this best:

> Because stream.compose returns a new stream that in turn can (and should) be piped into other streams, it enables composition. In contrast, when passing streams to stream.pipeline, typically the first stream is a readable stream and the last a writable stream, forming a closed circuit.

File: packages/csv/src/index.ts [hunk 5]
```diff
@@ -0,0 +1,56 @@
...
+ * Streaming transform from an array of objects to a CSV that doesn't
+ * block the event loop.
+ */
+export function stringifyNonblocking(data: any[], options: StringifierOptions = {}): Stringifier {
+  const stringifier = new Stringifier(options);
+
+  process.nextTick(function () {
+    let j = 0;
+    function loop() {
+      for (let i = 0; i < 100; i++) {
```
[the remark this answers is not in the document]
Comment (nwalters512) [reply packages/csv/src/index.ts]: I added a `batchSize` option in a33f506,

File: tests/postgres.test.js
Comment (nwalters512) [reply tests/postgres.test.js:1]: I moved things around in #7376, so this is now resolved!

File: pages/instructorQuestionStatistics/instructorQuestionStatistics.js (hunk 1 above)
Comment (mwest1066) [reply pages/instructorQuestionStatistics/instructorQuestionStatistics.js:34]: I guess this is some leftover thing from the student who originally implemented this? I guess it was never implemented, although they do look like interesting things to be computing.

File: packages/postgres/src/pool.ts (hunk 4 above)
[the remark this answers is not in the document]
Comment (mwest1066) [reply packages/postgres/src/pool.ts:957]: Cool, thanks!

File: pages/instructorQuestionStatistics/instructorQuestionStatistics.js (hunk 1 above)
Comment (nwalters512) [reply pages/instructorQuestionStatistics/instructorQuestionStatistics.js:34]: Gotcha - I'll rip this out in another PR!
