### PR TITLE
Fix case-sensitive UUID comparison in file editor

### LINKED ISSUE #14399: Uppercase UUIDs are counted as changing a UUID
### Details

Image

The actual UUID was uppercase, it claims the UUID changed when it did not.

### PR DESCRIPTION
**Pull request by EduardoMVAz**
# Description

Closes #14399 

Use case-insensitive comparison for UUIDs in the file editor to avoid false “UUID changed” warnings when the UUID differs only in letter casing.

# Testing

Tested manually by updating the UUID value to it's upper-cased version:

image

Updated successfully:

image

### CODE REVIEW

File: apps/prairielearn/assets/scripts/instructorFileEditorClient.tsx [hunk 1]
```diff
@@ -244,7 +244,7 @@ class InstructorFileEditor {
           return { errorCode: SaveErrorCode.INVALID_JSON };
         } else if (this.fileMetadata.uuid) {
           if ('uuid' in parsedContent) {
-            if (parsedContent.uuid !== this.fileMetadata.uuid) {
+            if (String(parsedContent.uuid).toLowerCase() !== this.fileMetadata.uuid.toLowerCase()) {
```
Comment (reteps) [inline apps/prairielearn/assets/scripts/instructorFileEditorClient.tsx]: nit: do a `typeof parsedContent.uuid` instead of a cast to String. E.g. `String(undefined)` would be turned into `'undefined'`

File: testCourse/courseInstances/Sp15/infoCourseInstance.json [hunk 2]
```diff
@@ -1,5 +1,5 @@
 {
-  "uuid": "31a69dd9-81a1-4b17-b578-2098d20fb57a",
+  "uuid": "31A69DD9-81A1-4B17-B578-2098D20FB57A",
```
Comment (reteps) [inline testCourse/courseInstances/Sp15/infoCourseInstance.json]: don't commit this change please

File: apps/prairielearn/assets/scripts/instructorFileEditorClient.tsx (hunk 1 above)
Comment (EduardoMVAz) [reply apps/prairielearn/assets/scripts/instructorFileEditorClient.tsx]: Done in [0298388](https://github.com/PrairieLearn/PrairieLearn/pull/14405/commits/0298388ea060a58c1aafaf6fe8593919b8a38079)

File: testCourse/courseInstances/Sp15/infoCourseInstance.json (hunk 2 above)
Comment (EduardoMVAz) [reply testCourse/courseInstances/Sp15/infoCourseInstance.json]: Sorry!
