### PR TITLE
Store correct user for issues

### LINKED ISSUE #10700: Issues reported on manual grading page show incorrect user
Whilst manually grading questions, the staff information panel allows you to report an issue however it is reported as the student name, not the staff member who creates the issue

image

image

### PR DESCRIPTION
**Pull request by mylesw27**
Closes #10700. Previously, we were inferring the `user_id` from the user attached to the associated question variant. This was resulting in the wrong user displaying as having reported the issue if the instructor or another user reported it. This PR will explicitly pass both the `user_id` and `authn_user_id` when a new issue is created and remove the need to infer the `user_id` from the variant.

### CODE REVIEW

File: apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts [hunk 1]
```diff
@@ -48,6 +48,8 @@ export default function (options = { publicEndpoint: false }) {
         variant,
         res.locals.question,
         res.locals.course,
+        // res.locals.user.user_id is not always available during shared question preview.
+        res.locals.user ? res.locals.user.user_id : res.locals.authn_user,
```
Comment (mylesw27) [inline apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts:52]: As noted in the comment, `user.user_id` was not always available here. Instead I am using the authn_user in these cases which should only occur during question sharing preview. In those cases, I don't think there should be a difference between `authn_user` and the current user as you would need to be authorized as an instructor to reach this.

File: apps/prairielearn/src/cron/autoFinishExams.ts [hunk 2]
```diff
@@ -43,6 +43,7 @@ export async function run() {
       await gradeAssessmentInstance(
         assessment_instance.id,
         authn_user_id,
+        authn_user_id,
```
Comment (mylesw27) [inline apps/prairielearn/src/cron/autoFinishExams.ts:46]: As noted in the commented code above, grading is done by the system so users are `null`. I reused `authn_user_id` here rather than storing another `null` variable. However, reviewing now, this looks confusing.

File: apps/prairielearn/src/lib/grading.ts [hunk 3]
```diff
@@ -53,6 +53,7 @@ const VariantForSubmissionSchema = VariantSchema.extend({
 type SubmissionDataForSaving = Pick<Submission, 'variant_id' | 'auth_user_id'> &
   Pick<Partial<Submission>, 'credit' | 'mode' | 'client_fingerprint_id'> & {
     submitted_answer: NonNullable<Submission['submitted_answer']>;
+    user_id: string | null;
```
Comment (mylesw27) [inline apps/prairielearn/src/lib/grading.ts:56]: We are not storing `user_id` in the submissions table only a `authn_user_id`. Adding `user_id` to the type here which we will need to pass if we need to create an issue.

**Review by mylesw27 — COMMENTED** [review]
Left a couple self-review comments below. Current status of this PR is that is passes the `user_id` everywhere I believe we want it passed down. When starting with this PR, I started with `insertIssue` from `lib/issues.ts` and then followed all references to where I can pass a `user_id`. That may help for review as it seems like it is just `user_id` being added and passed down in all changes here.

File: apps/prairielearn/src/cron/autoFinishExams.ts (hunk 2 above)
Comment (nwalters512) [reply apps/prairielearn/src/cron/autoFinishExams.ts:46]: Yeah, consider introducing a `user_id = null` variable to make things a little clearer.

File: apps/prairielearn/src/lib/question-render.js [hunk 4]
```diff
@@ -137,9 +137,17 @@ async function render(
 
   const studentMessage = 'Error rendering question';
   const courseData = { variant, question, submission, course: variant_course };
+  const user_id = locals.user && locals.user.user_id ? locals.user.user_id : null;
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/question-render.js:140]: Nit: consider re-ordering this below the comment on the following line and update the comment to talk about user information in general.

File: apps/prairielearn/src/lib/question-testing.ts [hunk 5]
```diff
@@ -181,18 +191,21 @@ async function testVariant(
   course: Course,
   test_type: TestType,
   authn_user_id: string,
+  user_id: string,
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/question-testing.ts:194]: Nit: conventionally `user_id` will come before `authn_user_id` in the list of parameters. Don't forget to update the callsites if you change this.

File: apps/prairielearn/src/lib/question-testing.ts [hunk 6]
```diff
@@ -391,14 +425,15 @@ export async function startTestQuestion(
...
   authn_user_id: string,
 ): Promise<string> {
   let success = true;
   const test_types: TestType[] = ['correct', 'incorrect', 'invalid'] as const;
 
   const serverJob = await createServerJob({
     courseId: course.id,
-    userId: String(authn_user_id),
+    userId: String(user_id),
     authnUserId: String(authn_user_id),
```
Comment (nwalters512) [inline apps/prairielearn/src/lib/question-testing.ts:437]: AFAICT the use of the `String(...)` constructor here is unnecessary, since the types declare that this is already a string.

File: apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts:52]: Interesting... under what conditions would we not have a `user` here?

File: apps/prairielearn/src/cron/autoFinishExams.ts (hunk 2 above)
Comment (mylesw27) [reply apps/prairielearn/src/cron/autoFinishExams.ts:47]: Added a `user_id = null` in [bc258cb](https://github.com/PrairieLearn/PrairieLearn/pull/10840/commits/bc258cb63105129c9382b9367281d7b040a14698).

File: apps/prairielearn/src/lib/question-render.js (hunk 4 above)
Comment (mylesw27) [reply apps/prairielearn/src/lib/question-render.js:141]: Reordered the comment and updated to discuss general user information in [bc258cb](https://github.com/PrairieLearn/PrairieLearn/pull/10840/commits/bc258cb63105129c9382b9367281d7b040a14698).

File: apps/prairielearn/src/lib/question-testing.ts (hunk 5 above)
Comment (mylesw27) [reply apps/prairielearn/src/lib/question-testing.ts:193]: Moved `user_id` before `authn_user_id` in [bc258cb](https://github.com/PrairieLearn/PrairieLearn/pull/10840/commits/bc258cb63105129c9382b9367281d7b040a14698). This was only called once and I updated the order there as well.

File: apps/prairielearn/src/lib/question-testing.ts (hunk 6 above)
Comment (mylesw27) [reply apps/prairielearn/src/lib/question-testing.ts]: Removed `String(...)` in [bc258cb](https://github.com/PrairieLearn/PrairieLearn/pull/10840/commits/bc258cb63105129c9382b9367281d7b040a14698).

File: apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts (hunk 1 above)
Comment (mylesw27) [reply apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts:52]: There is not a `user` attached to `res.locals` when trying to download files from `generatedFilesQuestion` in the `questionSharingPreview`. To reproduce, change this line to just `res.locals.user.user_id` and run the `questionSharingPreview` test.

File: apps/prairielearn/src/lib/question-testing.ts (hunk 6 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/question-testing.ts]: Thanks! There's one on the following line as well, would be nice to clean that up while we're here.

Comment (mylesw27) [reply apps/prairielearn/src/lib/question-testing.ts]: Removed in [61115af](https://github.com/PrairieLearn/PrairieLearn/pull/10840/commits/61115af1d991178079dbce0835d46b295561be0b).

File: apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts (hunk 1 above)
Comment (nwalters512) [reply apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts:52]: Sure, I can see that that's the case, my question was about _why_ we're missing `res.locals.user` there. I dug in a bit, turns out it's because `res.locals.user` is only assigned by the `authzCourseOrInstance` middleware, which doesn't run for that route.

I'd make the following changes (note that passing `authn_user` where an ID is expected isn't valid):

```suggestion
        // `res.locals.user` isn't populated for publicly-shared question previews.
        res.locals.user?.user_id ?? res.locals.authn_user.user_id,
```

Comment (mylesw27) [reply apps/prairielearn/src/pages/generatedFilesQuestion/generatedFilesQuestion.ts]: Got it. Committed the suggested code above. Thank you for the cleanup here!

File: apps/prairielearn/src/lib/grading.ts (hunk 3 above)
Comment (nwalters512) [reply apps/prairielearn/src/lib/grading.ts:56]: I think this is OK. An alternative would be to add this as a separate parameter to functions that need it, but we're already bundling a bunch of context into this `submissionData`, so 🤷 

I think this can be made non-nullable.

Comment (mylesw27) [reply apps/prairielearn/src/lib/grading.ts]: Made `user_id` non-nullable in [f33eebc](https://github.com/PrairieLearn/PrairieLearn/pull/10840/commits/f33eebcc2cd336dd68a9f4942e2d3abac4b6855b).

**Review by nwalters512 — APPROVED** [review]
