### PR TITLE
Fix handling of relative paths in course directories config

### LINKED ISSUE #11310: Deduplicate "Load from disk" directories (course vs sync)
In #11200 the list of synced courses was merged between the database and the config file. However, in cases where the config file was a relative path (a common practice for exampleCourse and testCourse), these directories were not properly identified as the same directory. That is because the path from config is resolved against the repository directory in:

https://github.com/PrairieLearn/PrairieLearn/blob/d3688c294b28f4d90372ce82be57d454708eedb6/apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts#L42

and the resolved directory is saved into the DB, but the config remains unresolved. I suggest that the config paths should be resolved before the course paths are added to the set of courses to sync, so that these directories can be identified as the same directory.

### PR DESCRIPTION
**Pull request by jonatanschroeder**
Resolves #11310. Ensures that directories that are listed as relative paths in the config for "courseDirs" (such as exampleCourse, testCourse and templateCourse)  are not loaded twice when "Load from disk" is invoked, by using the resolved path when comparing with existing courses.

### CODE REVIEW

File: apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts [hunk 1]
```diff
@@ -34,12 +34,13 @@ async function update(locals: Record<string, any>) {
...
     // listed in the config (and listed earlier in the config) are synced first.
-    const courseDirs = new Set<string>(config.courseDirs);
+    const courseDirs = new Set<string>(
+      config.courseDirs.map((courseDir) => path.resolve(REPOSITORY_ROOT_PATH, courseDir)),
+    );
     const courses = await queryRows(sql.select_all_courses, CourseSchema);
     courses.forEach((course) => courseDirs.add(course.path));
 
     await async.eachOfSeries(Array.from(courseDirs), async (courseDir, index) => {
-      courseDir = path.resolve(REPOSITORY_ROOT_PATH, courseDir);
```
Comment (jonatanschroeder) [inline apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts:42]: I made the assumption here that all directories in the database will be absolute/resolved, so the DB paths don't need to be resolved. If that is not the case I'm happy to do the same treatment to those as well.

Comment (nwalters512) [reply apps/prairielearn/src/pages/instructorLoadFromDisk/instructorLoadFromDisk.ts:42]: Yep, that should be a safe assumption; we have code like `path.join(course.path, ...)` throughout the codebase. At any rate, this is all dev-only code, so it won't be horrible if this happens to break something.

**Review by nwalters512 — APPROVED** [review]
